package com.mindoo.domino.jna.structs.viewformat;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.mindoo.domino.jna.structs.BaseStructure;
import com.mindoo.domino.jna.structs.NotesUniversalNoteIdStruct;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesViewColumnFormat2Struct extends BaseStructure {
	/** VIEW_COLUMN_FORMAT_SIGNATURE2 */
	public short Signature;
	/** FontID of column header. */
	public int HeaderFontID;
	/**
	 * UNID of view to switch to.<br>
	 * C type : UNID
	 */
	public NotesUniversalNoteIdStruct ResortToViewUNID;
	/** 0 based index of secondary resort column. */
	public short wSecondResortColumnIndex;
	public short Flags3;
	public short wHideWhenFormulaSize;
	public short wTwistieResourceSize;
	/** V6 View Customization support */
	public short wCustomOrder;
	/** V6 View Customization support */
	public short wCustomHiddenFlags;
	/**
	 * V6 - Column Text Color<br>
	 * C type : COLOR_VALUE
	 */
	public NotesColorValueStruct ColumnColor;
	/**
	 * V6 - column header color<br>
	 * C type : COLOR_VALUE
	 */
	public NotesColorValueStruct HeaderFontColor;
	public NotesViewColumnFormat2Struct() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormat2Struct newInstance() {
		return AccessController.doPrivileged(new PrivilegedAction<NotesViewColumnFormat2Struct>() {

			@Override
			public NotesViewColumnFormat2Struct run() {
				return new NotesViewColumnFormat2Struct();
			}
		});
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("Signature", "HeaderFontID", "ResortToViewUNID", "wSecondResortColumnIndex", "Flags3", "wHideWhenFormulaSize", "wTwistieResourceSize", "wCustomOrder", "wCustomHiddenFlags", "ColumnColor", "HeaderFontColor");
	}
	public NotesViewColumnFormat2Struct(Pointer peer) {
		super(peer);
		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesViewColumnFormat2Struct newInstance(final Pointer peer) {
		return AccessController.doPrivileged(new PrivilegedAction<NotesViewColumnFormat2Struct>() {

			@Override
			public NotesViewColumnFormat2Struct run() {
				return new NotesViewColumnFormat2Struct(peer);
			}
		});
	}

	public static class ByReference extends NotesViewColumnFormat2Struct implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesViewColumnFormat2Struct implements Structure.ByValue {
		
	};
}
