package com.mindoo.domino.jna.errors.errortexts;

public interface IBsafeErr extends IGlobalErr {

	@ErrorText(text="Enter password (press the Esc key to abort): ")
	short ERR_BSAFE_PSW_PROMPT = (PKG_BSAFE+0);
	@ErrorText(text="The encrypted data has been modified or the wrong key was used to decrypt it")
	short ERR_BSAFE_BADKEY = (PKG_BSAFE+7);
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE_BADCTX = (PKG_BSAFE+8);
	@ErrorText(text="Illegal Security function code")
	short ERR_BSAFE_BADOPCODE = (PKG_BSAFE+9);
	@ErrorText(text="The encrypted data has been modified or the wrong key was used to decrypt it")
	short ERR_BSAFE_BADCHECKSUM = (PKG_BSAFE+10);
	@ErrorText(text="The encrypted data has been modified or the wrong key was used to decrypt it")
	short ERR_BSAFE_BADDATA = (PKG_BSAFE+11);
	@ErrorText(text="BSAFE package software error #1")
	short ERR_BSAFE_BUG_1 = (PKG_BSAFE+12);
	@ErrorText(text="Insufficient memory - BSAFE pool is full")
	short ERR_BSAFE_POOLFULL = (PKG_BSAFE+13);
	@ErrorText(text="Insufficient memory - BSAFE Name lookup cache is full")
	short ERR_BSAFE_CACHEFULL = (PKG_BSAFE+14);
	@ErrorText(text="Buffer used to receive cryptographic output was too small")
	short ERR_BSAFE_TOOSMALL = (PKG_BSAFE+15);
	@ErrorText(text="Inconsistent name attributes")
	short ERR_BSAFE_BAD_ATTRIBUTES = (PKG_BSAFE+16);
	@ErrorText(text="Bad Message Digest length")
	short ERR_BSAFE_MDLENGTH = (PKG_BSAFE+17);
	@ErrorText(text="Attempted encryption operation is not supported by this version of Notes.")
	short ERR_BSAFE_NOT_ALLOWED = (PKG_BSAFE+18);
	@ErrorText(text="The specified ID file may only be used inside of North America.")
	short ERR_BSAFE_ILLEGAL_IDFILE = (PKG_BSAFE+19);
	@ErrorText(text="The public key or certificate version stored in the Address Book is not supported.")
	short ERR_BSAFE_BAD_PI_VERSION = (PKG_BSAFE+20);
	@ErrorText(text="The public key or certificate stored in the Address Book has been corrupted.")
	short ERR_BSAFE_BAD_PI_CHECKSUM = (PKG_BSAFE+21);
	@ErrorText(text="There is no certificate in the Address Book.")
	short ERR_BSAFE_MISSING_PI = (PKG_BSAFE+22);
	@ErrorText(text="The supplied certificate table does not contain any hierarchical certificates")
	short ERR_BSAFE_TABLE_MUST_BE_HI = (PKG_BSAFE+23);
	@ErrorText(text="No certificates in common")
	short ERR_BSAFE_NO_COMMON_CERT = (PKG_BSAFE+24);
	@ErrorText(text="Unrecognized certificate table version")
	short ERR_BSAFE_CERTTABLE_VERSION = (PKG_BSAFE+25);
	@ErrorText(text="Illegal use of an ID generator file")
	short ERR_BSAFE_ILLUSE_GENID = (PKG_BSAFE+26);
	@ErrorText(text="Specified file is not an ID generator file")
	short ERR_BSAFE_NOT_GENID = (PKG_BSAFE+27);
	@ErrorText(text="Specified private key does not exist")
	short ERR_BSAFE_NOSUCH_PRVKEY = (PKG_BSAFE+28);
	@ErrorText(text="This version of the software does not know the key of a required escrow authority")
	short ERR_BSAFE_NOSUCH_ESCROW = (PKG_BSAFE+29);
	@ErrorText(text="WARNING: Network-based ID files should be password protected!")
	short ERR_BSAFE_NETFILE = (PKG_BSAFE+30);
	@ErrorText(text="Unsupported ID file version.")
	short ERR_BSAFE_BAD_IDFILE_VERSION = (PKG_BSAFE+31);
	@ErrorText(text="Specified public key does not exist")
	short ERR_BSAFE_NOSUCH_PUBKEY = (PKG_BSAFE+32);
	@ErrorText(text="Process has not initialized with the security package")
	short ERR_BSAFE_PROC_NOT_INITED = (PKG_BSAFE+33);
	@ErrorText(text="A sub-process cannot change to a new ID file or prompt for passwords.")
	short ERR_BSAFE_SUBPROCESS = (PKG_BSAFE+34);
	@ErrorText(text="Insufficient memory for attempted security operation.")
	short ERR_BSAFE_NOMEMORY = (PKG_BSAFE+35);
	@ErrorText(text="Invalid Cross Certificate was found for %a. This could be a possible attack, please notify your administrator. Select 'Yes' to keep the current existing Cross Certificate")
	short ERR_BSAFE_INVALID_XCERT = (PKG_BSAFE+38);
	@ErrorText(text="The ID file is a safe copy and cannot be used for that purpose.")
	short ERR_BSAFE_ILLUSE_SAFECOPY = (PKG_BSAFE+39);
	@ErrorText(text="The prompt for password was aborted by user")
	short ERR_BSAFE_USER_ABORT = (PKG_BSAFE+40);
	@ErrorText(text="Cannot access or create the ID file")
	short ERR_BSAFE_ID_PROTECTED = (PKG_BSAFE+41);
	@ErrorText(text="ID file cannot be created")
	short ERR_BSAFE_ID_CREATE = (PKG_BSAFE+42);
	@ErrorText(text="The specified ID file has been corrupted, or is not an ID file")
	short ERR_BSAFE_ID_TRUNC = (PKG_BSAFE+43);
	@ErrorText(text="The specified ID file has been corrupted, or is not an ID file")
	short ERR_BSAFE_CORRUPTIDFILE = ERR_BSAFE_ID_TRUNC;
	@ErrorText(text="Illegal ID file name: too long or uses invalid syntax")
	short ERR_BSAFE_ID_INVFILENAME = (PKG_BSAFE+44);
	@ErrorText(text="Cannot write to ID file; either it is READ-ONLY or the disk is out of space")
	short ERR_BSAFE_ID_WRITETRUNC = (PKG_BSAFE+45);
	@ErrorText(text="Invalid drive specified for ID file")
	short ERR_BSAFE_ID_INVDRIVE = (PKG_BSAFE+46);
	@ErrorText(text="The requested item does not exist")
	short ERR_BSAFE_NON_EXISTENT = (PKG_BSAFE+47);
	@ErrorText(text="You don't have any of the specified encryption keys")
	short ERR_BSAFE_NEK_NOT_FOUND = (PKG_BSAFE+48);
	@ErrorText(text="The cryptographic key was not found")
	short ERR_BSAFE_KEY_NOT_FOUND = (PKG_BSAFE+49);
	@ErrorText(text="The cryptographic key's format is invalid")
	short ERR_BSAFE_KEY_INV_FORMAT = (PKG_BSAFE+50);
	@ErrorText(text="Your ID file does not contain any encryption keys")
	short ERR_BSAFE_NO_KEYS = (PKG_BSAFE+51);
	@ErrorText(text="Unrecognized or unsupported certificate type")
	short ERR_BSAFE_UNKNOWN_CERTIFICATE = (PKG_BSAFE+52);
	@ErrorText(text="Unrecognized or unsupported ID File type")
	short ERR_BSAFE_UNKNOWN_IDFILE = (PKG_BSAFE+53);
	@ErrorText(text="Unrecognized or unsupported document encryption key type stored in the ID file")
	short ERR_BSAFE_UNKNOWN_DOCKEY = (PKG_BSAFE+54);
	@ErrorText(text="Unrecognized or unsupported user-information structure")
	short ERR_BSAFE_UNKNOWN_USERINFO = (PKG_BSAFE+55);
	@ErrorText(text="Certificate object requires more than 64K bytes")
	short ERR_BSAFE_ODSCERT_TOOBIG = (PKG_BSAFE+58);
	@ErrorText(text="Unrecognized or unsupported user-descriptor object found in the ID file")
	short ERR_BSAFE_UNKNOWN_UDO = (PKG_BSAFE+59);
	@ErrorText(text="You must first open the ID file before attempting that operation")
	short ERR_BSAFE_FILE_NOT_OPENED = (PKG_BSAFE+60);
	@ErrorText(text="The certificate was revoked")
	short ERR_BSAFE_CERTIFICATE_REVOKED = (PKG_BSAFE + 61);
	@ErrorText(text="Certificate is expired or not yet valid")
	short ERR_BSAFE_CERT_VALIDITY = (PKG_BSAFE + 62);
	@ErrorText(text="The CRL is expired or not yet valid")
	short ERR_BSAFE_CRL_VALIDITY = (PKG_BSAFE + 63);
	@ErrorText(text="A CRL was required, but not found for the certificate")
	short ERR_BSAFE_CRL_NOT_FOUND = (PKG_BSAFE + 64);
	@ErrorText(text="The certificate or chain is invalid due to a key usage violation")
	short ERR_BSAFE_KEY_USAGE = (PKG_BSAFE + 65);
	@ErrorText(text="The certificate or chain is invalid due to a basic constraints violation")
	short ERR_BSAFE_BASIC_CONSTRAINTS = (PKG_BSAFE + 66);
	@ErrorText(text="Senders' signing certificate is expired")
	short ERR_BSAFE_SENDER_SIGNING_CERT_IS_EXPIRED = (PKG_BSAFE+68);
	@ErrorText(text="Senders' signing certificate has expired after this mail was signed")
	short ERR_BSAFE_SENDER_SIGNING_CERT_HAS_SINCE_EXPIRED = (PKG_BSAFE+69);
	@ErrorText(text="An invalid Cross Certificate was found. It may be a corrupted Cross Certificate, an attack or a new public key issued. Please notify administrator of the problem")
	short ERR_BSAFE_INVALID_XCERT_NO_ARG = (PKG_BSAFE+70);
	@ErrorText(text="The requested Cross Certificate will not be issued because the subject is already trusted.")
	short ERR_BSAFE_CANT_CREATE_XCERT = (PKG_BSAFE+71);
	@ErrorText(text="The signer's public key found in the signature does not match the one stored in the directory")
	short ERR_BSAFE_WRONG_SUBJECT_KEY_IN_SIGNATURE = (PKG_BSAFE+72);
	@ErrorText(text="Password has not yet been validated")
	short ERR_BSAFE_NO_VALID_PW = (PKG_BSAFE+73);
	@ErrorText(text="Unrecognized password object or algorithm")
	short ERR_BSAFE_ILL_PW_ALG = (PKG_BSAFE+74);
	@ErrorText(text="Notes shared login failed with this ID file")
	short ERR_BSAFE_NSL_UNLOCK_FAILED = (PKG_BSAFE+75);
	@ErrorText(text="The ID File is in use elsewhere and cannot be modified")
	short ERR_BSAFE_IDFILE_LOCKED = (PKG_BSAFE+77);
	@ErrorText(text="Cannot add the encryption key to your ID file.  A key with that name already exists.")
	short ERR_BSAFE_NEK_EXISTS = (PKG_BSAFE+78);
	@ErrorText(text="The certificate(s) have not been issued to you and cannot be merged into your ID file.  They have been issued to")
	short ERR_BSAFE_MERGE_NONCOPY = (PKG_BSAFE+80);
	@ErrorText(text="The Public Key cannot be accepted since there is no matching Private Key found in the ID file.")
	short ERR_BSAFE_MERGE_NOPRVKEY = (PKG_BSAFE+81);
	@ErrorText(text="If you change the user name, this ID will lose all of its certificates.  When the name change is complete, this ID will need to be certified.  Do you want to continue?")
	short ERR_BSAFE_NONAMECHANGE = (PKG_BSAFE+82);
	@ErrorText(text="There are no certificates to be merged into your ID file")
	short ERR_BSAFE_NOMERGECERT = (PKG_BSAFE+83);
	@ErrorText(text="Your ID file has been corrupted, or is not an ID file.")
	short ERR_BSAFE_INVUSERIDFILE = (PKG_BSAFE+84);
	@ErrorText(text="The specified ID file has been corrupted, or is not an ID file.")
	short ERR_BSAFE_CORRUPTFILE = (PKG_BSAFE+85);
	@ErrorText(text="This request is not supported with the version of your ID file.  An ID file containing a hierarchical name is required.")
	short ERR_BSAFE_REQUIRES_NONFLATID = (PKG_BSAFE+86);
	@ErrorText(text="The Address Book does not contain a cross certificate capable of validating the public key.")
	short ERR_BSAFE_NO_CROSS_CERT = (PKG_BSAFE+87);
	@ErrorText(text="The certificate table does not contain enough valid certificates to verify the public key of its owner.")
	short ERR_BSAFE_INCOMPLETE_CERTTABLE = (PKG_BSAFE+88);
	@ErrorText(text="Illegal use of a Certifier ID file")
	short ERR_BSAFE_ILLUSE_CERTIFIER = (PKG_BSAFE+89);
	@ErrorText(text="The ID file is not a Certifier ID file and cannot be used to issue certificates")
	short ERR_BSAFE_MUSTBE_CERTIFIER = (PKG_BSAFE+90);
	@ErrorText(text="The ID file is write protected")
	short ERR_BSAFE_WRITEPROTECTED = (PKG_BSAFE+91);
	@ErrorText(text="This is a safe-copy version of an ID file and cannot be password protected")
	short ERR_BSAFE_NOPSW_ON_SAFECOPY = (PKG_BSAFE+92);
	@ErrorText(text="The local system cannot complete the operation because it is not running with a hierarchical name")
	short ERR_BSAFE_YOU_MUST_BE_HI = (PKG_BSAFE+93);
	@ErrorText(text="The subject's public key found in the certificate is not the one stored in our ID file for that entity.")
	short ERR_BSAFE_WRONG_SUBJECT_KEY = (PKG_BSAFE+94);
	@ErrorText(text="The supplied certificate table used to validate the signer's public key is improperly formed")
	short ERR_BSAFE_ILL_CERTTABLE = (PKG_BSAFE+95);
	@ErrorText(text="The certifier has not been assigned a hierarchical name")
	short ERR_BSAFE_CERTIFIER_MUST_BE_HI = (PKG_BSAFE+96);
	@ErrorText(text="Password Externally Supplied")
	short ERR_BSAFE_EXTERNAL_PASSWORD = (PKG_BSAFE+97);
	@ErrorText(text="Password and Data Externally Supplied")
	short ERR_BSAFE_EXTERNAL_PWD_AND_DATA = (PKG_BSAFE+98);
	@ErrorText(text="Exceeded RSA key size limit for a flat ID")
	short ERR_BSAFE_FLAT_KEY_TOO_BIG = (PKG_BSAFE+99);
	@ErrorText(text="A certificate request has been submitted")
	short ERR_BSAFE_CERTREQ_SUBMITTED = (PKG_BSAFE+100);
	@ErrorText(text="%s username and password were updated in the ID file.")
	short ERR_BSAFE_ID_EXTRA_UPDATED = (PKG_BSAFE+101);
	@ErrorText(text="%s username and password could not be updated in the ID file.")
	short ERR_BSAFE_ID_EXTRA_UPDATE_FAIL = (PKG_BSAFE+102);
	@ErrorText(text="Operation canceled")
	short ERR_BSAFE_CANCELED = (PKG_BSAFE+103);
	@ErrorText(text="%s username and password were cleared from the ID file.")
	short ERR_BSAFE_ID_EXTRA_DELETED = (PKG_BSAFE+104);
	@ErrorText(text="That name has already been associated with another language specifier.")
	short ERR_BSAFE_ASSIGNED_TO_DIFF_LANG = (PKG_BSAFE+105);
	@ErrorText(text="%s username and password could not be cleared from the ID file.")
	short ERR_BSAFE_ID_EXTRA_DELETE_FAIL = (PKG_BSAFE+106);
	@ErrorText(text="ID files cannot be merged.")
	short ERR_BSAFE_ID_FILE_MERGE_FAIL = (PKG_BSAFE+107);
	@ErrorText(text="The operation cannot be completed because the certificate contains an alternate name")
	short ERR_BSAFE_CERT_HAS_ALTNAME = (PKG_BSAFE+108);
	@ErrorText(text="Domino Controller|DB2|DB2 Default")
	short ERR_BSAFE_ID_EXTRA_TYPE = (PKG_BSAFE+109);
	@ErrorText(text="This extra item is only available on V8 servers.")
	short ERR_BSAFE_VERSION_NOT_V8 = (PKG_BSAFE+110);
	@ErrorText(text="This key may only be stored in ID files with North American licenses")
	short ERR_BSAFE_USA_KEY_ONLY = (PKG_BSAFE+111);
	@ErrorText(text="The ID file was not opened for write access")
	short ERR_BSAFE_ID_READ_ONLY = (PKG_BSAFE+112);
	@ErrorText(text="Your public key was not found in the Domino Directory")
	short ERR_BSAFE_NO_PUBLIC_INFO = (PKG_BSAFE+113);
	@ErrorText(text="You can create only as many as four Organizational Unit levels")
	short ERR_BSAFE_TOOMANY_ORG_UNITS = (PKG_BSAFE+114);
	@ErrorText(text="This request is not supported for the specified ID file.  An ID file containing a hierarchical name is required.")
	short ERR_BSAFE_MUSTBE_HIERARCHICAL = (PKG_BSAFE+115);
	@ErrorText(text="The disk drive specified for the ID file is not ready")
	short ERR_BSAFE_ID_DRIVE_NOT_READY = (PKG_BSAFE+116);
	@ErrorText(text="Cannot update the ID file; insufficient disk space")
	short ERR_BSAFE_ID_DISK = (PKG_BSAFE+117);
	@ErrorText(text="I/O error experienced while accessing the ID file")
	short ERR_BSAFE_ID_IOERROR = (PKG_BSAFE+118);
	@ErrorText(text="A password is required for this ID file")
	short ERR_BSAFE_PASSWORD_REQUIRED = (PKG_BSAFE+119);
	@ErrorText(text="The authentication code has failed the consistency check")
	short ERR_BSAFE_BAD_AUTH_CODE = (PKG_BSAFE+120);
	@ErrorText(text="The authentication code version number is not supported")
	short ERR_BSAFE_ILL_AUTH_CODE_VERSION = (PKG_BSAFE+121);
	@ErrorText(text="Cannot create certificate, resultant subject name would be too long")
	short ERR_BSAFE_NEWNAME_TOO_LONG = (PKG_BSAFE+122);
	@ErrorText(text="The certifier is not an ancestor of the subject in the certificate.")
	short ERR_BSAFE_CERT_NOT_ANCESTOR = (PKG_BSAFE+123);
	@ErrorText(text="Unrecognized or unsupported @CERTIFICATE code")
	short ERR_BSAFE_ILL_ATFUNC = (PKG_BSAFE+124);
	@ErrorText(text="A required certifier entry was not found in the Name and Address Book; consult the Notes Log for details on the specific entry")
	short ERR_BSAFE_CERTIFIER_NOT_IN_NAB = (PKG_BSAFE+125);
	@ErrorText(text="Unrecognized or unsupported Distinguished Name structure")
	short ERR_BSAFE_ILL_DISTINFO = (PKG_BSAFE+126);
	@ErrorText(text="Internal error: too few parameters passed in subroutine call")
	short ERR_BSAFE_INSUF_INPUT_ARGS = (PKG_BSAFE+127);
	@ErrorText(text="Either the certificates' issuers or the certificates' subjects don't match")
	short ERR_BSAFE_CERT_MISMATCH = (PKG_BSAFE+128);
	@ErrorText(text="A cross-certificate was illegally used as a substitute for an ordinary certificate")
	short ERR_BSAFE_ILLUSE_XCERT = (PKG_BSAFE+129);
	@ErrorText(text="Certificate table could not be constructed because there are too many certificates")
	short ERR_BSAFE_TOO_MANY_CERTS = (PKG_BSAFE+130);
	@ErrorText(text="The supplied Certificate Table is missing a required certificate to complete the operation")
	short ERR_BSAFE_TOO_FEW_CERTS = (PKG_BSAFE+131);
	@ErrorText(text="This operation is only supported for ID file's containing hierarchical names")
	short ERR_BSAFE_ID_MUST_BE_HI = (PKG_BSAFE+132);
	@ErrorText(text="Invalid KFHANDLE")
	short ERR_BSAFE_INV_KFHANDLE = (PKG_BSAFE+133);
	@ErrorText(text="The ID file is locked by another process. Try again later")
	short ERR_BSAFE_FILE_LOCKED = (PKG_BSAFE+134);
	@ErrorText(text="Only the server process is allowed to attempt that operation")
	short ERR_BSAFE_MUST_BE_SERVER = (PKG_BSAFE+135);
	@ErrorText(text="Org Unit may only be supplied when upgrading flat to hierarchical")
	short ERR_BSAFE_INAPPROPRIATE_ORGUNIT = (PKG_BSAFE+136);
	@ErrorText(text="This entity's keys have never been rolled over to a new set of keys")
	short ERR_BSAFE_KEY_NEVER_ROLLED_OVER = (PKG_BSAFE+137);
	@ErrorText(text="The subject's public key found in the cross certificate does not match the one found in the certificate table.")
	short ERR_BSAFE_WRONG_SUBJECT_KEY_X = (PKG_BSAFE+138);
	@ErrorText(text="Error processing certificate created by %A for %A")
	short ERR_BSAFE_INVCERT_DATA = (PKG_BSAFE+139);
	@ErrorText(text="The signature on the cross certificate was found to be invalid.  Check the log file for details.")
	short ERR_BSAFE_INVCROSSCERT_SIG = (PKG_BSAFE+140);
	@ErrorText(text="The certificate contains the wrong subject name")
	short ERR_BSAFE_WRONG_CERT_SUBJECT = (PKG_BSAFE+141);
	@ErrorText(text="The certificate contains the wrong issuer name")
	short ERR_BSAFE_WRONG_CERT_ISSUER = (PKG_BSAFE+142);
	@ErrorText(text="The signature on the certificate was found to be invalid.  Check the log file for details.")
	short ERR_BSAFE_INVCERT_SIG = (PKG_BSAFE+145);
	@ErrorText(text="Your home server could not be contacted or is not configured.")
	short ERR_BSAFE_SECPANEL_NO_HOME_SERVER = (PKG_BSAFE+146);
	@ErrorText(text="The subject's public key found in the certificate is not the one stored in the server's ID file for that entity.  Check the server's log file for details.")
	short ERR_BSAFE_WRONG_SUBJECT_KEY_SRV = (PKG_BSAFE+147);
	@ErrorText(text="The subject's public key found in the certificate is not the one stored in our ID file for that entity.    Check the local log file for details.")
	short ERR_BSAFE_WRONG_SUBJECT_KEY_LOC = (PKG_BSAFE+148);
	@ErrorText(text="The certifier is not an ancestor of the subject in the certificate.  Check the server's log file for details.")
	short ERR_BSAFE_CERT_NOT_ANCESTOR_SRV = (PKG_BSAFE+149);
	@ErrorText(text="The certifier is not an ancestor of the subject in the certificate.  Check the local log file for details.")
	short ERR_BSAFE_CERT_NOT_ANCESTOR_LOC = (PKG_BSAFE+150);
	@ErrorText(text="Error locating a Domino Directory entry for certifier %s")
	short ERR_BSAFE_ADDBOOK_CERT_ENTRY = (PKG_BSAFE+151);
	@ErrorText(text="Attribute type is unrecognized ")
	short ERR_BSAFE2_ATTRIBUTE_UNKNOWN = (PKG_BSAFE2+0);
	@ErrorText(text="Unable to parse certificate ")
	short ERR_BSAFE2_UNABLE_TO_PARSE_CERT = (PKG_BSAFE2+1);
	@ErrorText(text="Nonexistent or invalid recovery information")
	short ERR_BSAFE2_BAD_RECOVERY_INFO = (PKG_BSAFE2+2);
	@ErrorText(text="A cross certificate will not be made due to key usage restrictions in the input certificate.")
	short ERR_BSAFE2_KEY_USAGE_RESTRICTION = (PKG_BSAFE2+3);
	@ErrorText(text="Certificate element too large for processing.")
	short ERR_BSAFE_BIG_CERT_ELEMENT = (PKG_BSAFE2+4);
	@ErrorText(text="Unrecognized name list version.")
	short ERR_BSAFE_NAMELIST_VERSION = (PKG_BSAFE2+5);
	@ErrorText(text="The name list is improperly formed and may have been corrupted.")
	short ERR_BSAFE_NAMELIST_MALFORMED = (PKG_BSAFE2+6);
	@ErrorText(text="The requested name list element does not exist.")
	short ERR_BSAFE_NAMELIST_NOSUCH_INDEX = (PKG_BSAFE2+7);
	@ErrorText(text="Too many alternate names in the name list.")
	short ERR_BSAFE_TOO_MANY_ALTNAMES = (PKG_BSAFE2+8);
	@ErrorText(text="A name with the specified language already exits.")
	short ERR_BSAFE_LANGTAG_EXISTS = (PKG_BSAFE2+9);
	@ErrorText(text="The specified language is unknown")
	short ERR_BSAFE_LANGTAG_UNKNOWN = (PKG_BSAFE2+10);
	@ErrorText(text="An improperly formed name was encountered")
	short ERR_BSAFE_NAME_MALFORMED = (PKG_BSAFE2+11);
	@ErrorText(text="Invalid certificate contents or format")
	short ERR_BSAFE_INV_CERT = (PKG_BSAFE2+12);
	@ErrorText(text="Illegal ASN.1 Object ID field")
	short ERR_ASN1_ILL_OID = (PKG_BSAFE2+13);
	@ErrorText(text="Illegal or unexpected ASN.1 data type")
	short ERR_ASN1_ILL_DATATYPE = (PKG_BSAFE2+14);
	@ErrorText(text="Illegal or unsupported ASN.1 data length")
	short ERR_ASN1_ILL_DATALENGTH = (PKG_BSAFE2+15);
	@ErrorText(text="Unknown S/MIME error")
	short ERR_BSAFE3_TE_UNKNOWN = (PKG_BSAFE3+0);
	@ErrorText(text="Invalid signature on certificate or CRL")
	short ERR_BSAFE3_TE_ASN_SIGNATURE = (PKG_BSAFE3+1);
	@ErrorText(text="Invalid cryptographic attributes object")
	short ERR_BSAFE3_TE_ATTRIBUTES_OBJ = (PKG_BSAFE3+2);
	@ErrorText(text="End of cryptographic data stream")
	short ERR_BSAFE3_TE_EOS = (PKG_BSAFE3+3);
	@ErrorText(text="Invalid cryptographic memory object")
	short ERR_BSAFE4_TE_MEMORY_OBJ = (PKG_BSAFE3+4);
	@ErrorText(text="Cryptographic data block is too big to be processed")
	short ERR_BSAFE4_TE_OVER_32K = (PKG_BSAFE3+5);
	@ErrorText(text="Invalid parameter passed to cryptographic function")
	short ERR_BSAFE4_TE_PARAMETER = (PKG_BSAFE3+6);
	@ErrorText(text="S/MIME version not supported")
	short ERR_BSAFE5_TE_VERSION = (PKG_BSAFE3+7);
	@ErrorText(text="Error -- ")
	short ERR_BSAFE5_ERROR = (PKG_BSAFE3+8);
	@ErrorText(text="Warning -- ")
	short ERR_BSAFE5_WARNING = (PKG_BSAFE3+9);
	@ErrorText(text="%s %s")
	short ERR_BSAFE5_LOG = (PKG_BSAFE3+10);
	@ErrorText(text="Cannot establish trust in a certificate or CRL.")
	short ERR_BSAFE5_TE_UNTRUSTED_CERTS_CRLS = (PKG_BSAFE3+11);
	@ErrorText(text="The certifier key in the certificate does not match the key stored in the directory.")
	short ERR_NOCA_KEYMATCH = (PKG_BSAFE3+12);
	@ErrorText(text="The requested rename or recertify function is unknown or unsupported.")
	short ERR_ILL_RECERT_FCT = (PKG_BSAFE3+13);
	@ErrorText(text="The certifier has not yet been assigned a name associated with the proposed language.")
	short ERR_NO_ANCESTOR_LANGTAG = (PKG_BSAFE3+14);
	@ErrorText(text="This entry has not been assigned a public key suitable for use on the internet.")
	short ERR_NO_INET_KEY = (PKG_BSAFE3+15);
	@ErrorText(text="This name already exists.")
	short ERR_BSAFE_NAME_EXISTS = (PKG_BSAFE3+16);
	@ErrorText(text="You are not authorized to recover this ID file.")
	short ERR_BSAFE_INVALID_BB = (PKG_BSAFE3+17);
	@ErrorText(text="Invalid ASN.1 syntax")
	short ERR_ASN1_INV_SYNTAX = (PKG_BSAFE3+18);
	@ErrorText(text="Invalid CRL contents or format")
	short ERR_BSAFE_INV_CRL = (PKG_BSAFE3+19);
	@ErrorText(text="Invalid certificate extensions object")
	short ERR_BSAFE_INV_EXTENSIONS_OBJ = (PKG_BSAFE3+20);
	@ErrorText(text="Cryptographic error: invalid message format")
	short ERR_BSAFE_INV_MSG_FORMAT = (PKG_BSAFE3+21);
	@ErrorText(text="Invalid cryptographic key length")
	short ERR_BSAFE_BAD_KEY_LENGTH = (PKG_BSAFE3+22);
	@ErrorText(text="Could not verify cryptographic signature")
	short ERR_BSAFE_BAD_SIGNATURE = (PKG_BSAFE3+23);
	@ErrorText(text="Bad random number generator state")
	short ERR_BSAFE_BAD_RANDOM_STATE = (PKG_BSAFE3+24);
	@ErrorText(text="Certificate, private key or CRL was not found")
	short ERR_BSAFE_CERTCRL_NOT_FOUND = (PKG_BSAFE3+25);
	@ErrorText(text="A certificate chain could not be constructed")
	short ERR_BSAFE_MAKING_CERT_CHAIN = (PKG_BSAFE3+26);
	@ErrorText(text="Cryptographic error: update operation called an inappropriate number of times")
	short ERR_BSAFE_CRYPTO_UPDATE_COUNT = (PKG_BSAFE3+27);
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE_DATA_STREAM = (PKG_BSAFE3+28);
	@ErrorText(text="Certificate extension already exists")
	short ERR_BSAFE_CERT_EXT_EXISTS = (PKG_BSAFE3+29);
	@ErrorText(text="Unknown data error occurred during cryptographic processing")
	short ERR_BSAFE_GENERIC_DATA = (PKG_BSAFE3+30);
	@ErrorText(text="Cryptographic hardware error")
	short ERR_BSAFE_HARDWARE = (PKG_BSAFE3+31);
	@ErrorText(text="Unsupported certificate or CRL signature algorithm")
	short ERR_BSAFE_UNSUPPORTED_CERTCRLSIG = (PKG_BSAFE4+0);
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE_UNSUPPORTED_CRYPTO_OP = (PKG_BSAFE4+1);
	@ErrorText(text="The data supplied would generate a known weak cryptographic key")
	short ERR_BSAFE_WEAK_KEY = (PKG_BSAFE4+2);
	@ErrorText(text="The revocation status of this certificate could not be verified")
	short ERR_BSAFE_OCSP_CERT_NOT_VERIFIED = (PKG_BSAFE4+3);
	@ErrorText(text="Unknown error received from ICC")
	short ERR_BSAFE_ICC_UNKNOWN = (PKG_BSAFE4+4);
	@ErrorText(text="Unsupported operation for a Notes ID that is enabled for Notes shared login.")
	short ERR_BSAFE_NSL_UNSUPPORTED_FUNC = (PKG_BSAFE4+5);
	@ErrorText(text="ICC library could not be found or initialization failed.  Please check your configuration.")
	short ERR_BSAFE_ICC_INIT_FAILED = (PKG_BSAFE4+6);
	@ErrorText(text="Password does not meet the requirement")
	short ERR_BSAFE_INVALID_PASSWORD = (PKG_BSAFE4+7);
	@ErrorText(text="Please insert the smartcard")
	short ERR_BSAFE_INSERT_SMARTCARD = (PKG_BSAFE4+8);
	@ErrorText(text="Incorrect PIN")
	short ERR_BSAFE_SC_PIN_INVALID = (PKG_BSAFE4+9);
	@ErrorText(text="A smartcard device error has occurred. Please eject and re-insert your smartcard.")
	short ERR_BSAFE_SC_RESET = (PKG_BSAFE4+10);
	@ErrorText(text="An unknown smartcard error has occurred.")
	short ERR_BSAFE_SC_UNKNOWN = (PKG_BSAFE4+11);
	@ErrorText(text="Incomplete or incorrect smartcard configuration.")
	short ERR_BSAFE_SC_INVALID_CONFIG = (PKG_BSAFE4+12);
	@ErrorText(text="This feature is not supported by your smartcard.")
	short ERR_BSAFE_SC_UNSUPPORTED_FUNC = (PKG_BSAFE4+13);
	@ErrorText(text="Insufficient free space on smartcard. Please contact your administrator.")
	short ERR_BSAFE_SC_DEVICE_MEMORY = (PKG_BSAFE4+14);
	@ErrorText(text="Your smartcard or cryptographic device is locked. Please contact your administrator.")
	short ERR_BSAFE_SC_PIN_LOCKED = (PKG_BSAFE4+15);
	@ErrorText(text="Recovery information has been removed")
	short ERR_BSAFE_RECOVERY_INFO_REMOVED = (PKG_BSAFE4+16);
	@ErrorText(text="This smartcard has not been initialized or is incompatible with your smartcard reader.")
	short ERR_BSAFE_SC_NOT_RECOGNIZED = (PKG_BSAFE4+17);
	@ErrorText(text="This key could not be written to your smartcard.")
	short ERR_BSAFE_SC_KEY_CREATE = (PKG_BSAFE4+18);
	@ErrorText(text=" The certificate is not usable.")
	short ERR_SMIME_RECIPIENT_BAD_CERT = (PKG_BSAFE4+19);
	@ErrorText(text=" The certificate chain is not trusted.")
	short ERR_SMIME_RECIPIENT_CERT_CHAIN = (PKG_BSAFE4+20);
	@ErrorText(text=" You are not allowed to encrypt for this recipient.")
	short ERR_SMIME_RECIPIENT_ILLEGAL = (PKG_BSAFE4+21);
	@ErrorText(text=" You cannot encrypt a message to this recipient.")
	short ERR_SMIME_RECIPIENT_ADD_FAILURE = (PKG_BSAFE4+22);
	@ErrorText(text=" This recipient's email address was not found in the certificate.")
	short ERR_SMIME_RECIPIENT_BAD_EMAIL = (PKG_BSAFE4+23);
	@ErrorText(text="This recipient's certificate had been revoked.")
	short ERR_SMIME_RECIPIENT_CERT_REVOKED = (PKG_BSAFE4+24);
	@ErrorText(text=" This recipient's email address in the directory did not match what was found in the certificate.")
	short ERR_SMIME_RECIPIENT_EMAIL_MISMATCH = (PKG_BSAFE4+25);
	@ErrorText(text=" This recipient's certificate is expired.")
	short ERR_SMIME_RECIPIENT_CERT_EXPIRED = (PKG_BSAFE4+26);
	@ErrorText(text=" The certificate used to send signed mail is expired.")
	short ERR_SMIME_SENDER_SIGNING_CERT_EXPIRED = (PKG_BSAFE4+27);
	@ErrorText(text="Single Sign-On token should be renewed.")
	short ERR_LTPA_TOKEN_SHOULD_RENEW = (PKG_BSAFE4+28);
	@ErrorText(text="WARNING:  Server certificate issued to %s by %s will expire on %s. Contact your Domino administrator.  %s")
	short ERR_BSAFE_CERT_EXPIRES_SERVER = (PKG_BSAFE4+29);
	@ErrorText(text="WARNING:  Server certificate issued to %s by %s expired on %s and can no longer be used.  Contact your Domino administrator.")
	short ERR_BSAFE_CERT_EXPIRED_SERVER = (PKG_BSAFE4+30);
	@ErrorText(text="No cross certificate from %A to %A was found in the directory")
	short ERR_BSAFE_NO_CROSS_CERT_NAMES = (PKG_BSAFE4+31);
	@ErrorText(text="The recovery information was not accepted because it is the same or older than your current recovery information")
	short ERR_BSAFE_RECOVERY_INFO_TOO_OLD = (PKG_BSAFE5+0);
	@ErrorText(text="Only leaf certificates can be deleted from the ID file")
	short ERR_BSAFE_NOT_LEAF_CERT = (PKG_BSAFE5+1);
	@ErrorText(text="You must specify a name for the backup repository address")
	short ERR_BSAFE_NO_REPOSITORY_NAME = (PKG_BSAFE5+2);
	@ErrorText(text="Cannot add key from the import file.")
	short ERR_BSAFE_PKCS12_IMPORT_ADD_KEY = (PKG_BSAFE5+3);
	@ErrorText(text="Cannot add certificate from the import file.")
	short ERR_BSAFE_PKCS12_IMPORT_ADD_CERT = (PKG_BSAFE5+4);
	@ErrorText(text="The password for this ID file is not stored on a smartcard.")
	short ERR_BSAFE_SC_NO_PASSWORD = (PKG_BSAFE5+5);
	@ErrorText(text="The path or file selected for the smartcard driver is invalid.")
	short ERR_BSAFE_SC_NO_DLL_FOUND = (PKG_BSAFE5+6);
	@ErrorText(text="A certificate table item was unrecognized")
	short ERR_BSAFE_ILL_CERTTAB_ITEM = (PKG_BSAFE5+7);
	@ErrorText(text="You cannot modify the active ID file")
	short ERR_BSAFE_CANT_MODIFY_ACTIVE_ID = (PKG_BSAFE5+8);
	@ErrorText(text="The certificate table contains too many key rollover certificates")
	short ERR_BSAFE_TOO_MANY_RO_CERTIFICATES = (PKG_BSAFE5+9);
	@ErrorText(text="Pending public keys are in the wrong state for the requested operation")
	short ERR_BSAFE_KEYGEN_WRONG_STATE = (PKG_BSAFE5+10);
	@ErrorText(text="The recipient's Notes public key is not compatible with the configured encryption settings.")
	short ERR_BSAFE_INCOMPAT_PUBLIC_KEY = (PKG_BSAFE5+11);
	@ErrorText(text="Too many key rollover certificates")
	short ERR_BSAFE_ROLLOVER_TOO_MANY = (PKG_BSAFE5+12);
	@ErrorText(text="Recovery information is from a certifier that is not an ancestor of this user")
	short ERR_BSAFE_RECOVERY_CERTIFIER_NOT_ANCESTOR = (PKG_BSAFE5+13);
	@ErrorText(text="The secret key is not compatible with the configured encryption settings.")
	short ERR_BSAFE_INCOMPAT_SECRET_KEY = (PKG_BSAFE5+14);
	@ErrorText(text="Unknown key rollover object type")
	short ERR_BSAFE_ROLLOVER_UNKNOWN_TYPE = (PKG_BSAFE5+15);
	@ErrorText(text="The signer's certificate is not trusted.")
	short ERR_BSAFE_TE_UNTRUSTED_SIGNER = (PKG_BSAFE6+0);
	@ErrorText(text="Cannot accept internet certificate because the certificate authority certificate is unavailable.")
	short ERR_BSAFE_INCOMPLETE_CERT_CHAIN = (PKG_BSAFE6+1);
	@ErrorText(text="Cannot accept internet certificate because the current ID file was not used to create the original request.")
	short ERR_BSAFE_MISSING_PRIVATE_KEY = (PKG_BSAFE6+2);
	@ErrorText(text="Cannot accept internet certificate because the certificate is already in the ID file.")
	short ERR_BSAFE_CERT_ALREADY_IN_ID_FILE = (PKG_BSAFE6+3);
	@ErrorText(text="The only allowed characters for a person, server, or certifier name are letters, numbers, ampersand, apostrophe, hyphen, period, space, and underscore")
	short ERR_BSAFE_ILL_IDCHAR = (PKG_BSAFE6+4);
	@ErrorText(text="The only allowed characters for a domain name are letters, numbers, ampersand, apostrophe, hyphen, space, and underscore")
	short ERR_BSAFE_ILL_DOMAIN = (PKG_BSAFE6+5);
	@ErrorText(text="The ID was certified but there was no corresponding entry in the Address Book to be updated")
	short ERR_BSAFE_NA_ENTRY_NOT_FOUND = (PKG_BSAFE6+6);
	@ErrorText(text="Unable to perform this operation; options were selected that cannot be used with this older format Notes database.")
	short ERR_BSAFE_OLDNSF = (PKG_BSAFE6+7);
	@ErrorText(text="Cannot certify this entry because the form used to create it is not supported for this operation.")
	short ERR_BSAFE_INV_RECERT_FORM = (PKG_BSAFE6+8);
	@ErrorText(text="Operation is not yet implemented")
	short ERR_BSAFE_NOT_IMPLEMENTED = (PKG_BSAFE6+9);
	@ErrorText(text="Duplicate name found")
	short ERR_BSAFE_DUP_NAME = (PKG_BSAFE6+10);
	@ErrorText(text="You specified an illegal certifier name")
	short ERR_BSAFE_ILL_CERTIFIER_NAME = (PKG_BSAFE6+11);
	@ErrorText(text="Could not locate or process internet certificates for this ID.")
	short ERR_BSAFE_NO_INET_CERTS = (PKG_BSAFE6+12);
	@ErrorText(text="Import file could not be read.  Check file permissions.")
	short ERR_BSAFE_PKCS12_IMPORT_BAD_FILE_READ = (PKG_BSAFE6+13);
	@ErrorText(text="Unsupported PKCS12 version or content.  Check the import file.")
	short ERR_BSAFE_PKCS12_IMPORT_BAD_INFO = (PKG_BSAFE6+14);
	@ErrorText(text="Cannot handle the import file.  Check file name and file password.")
	short ERR_BSAFE_PKCS12_IMPORT_BAD_UNKNOWN = (PKG_BSAFE6+15);
	@ErrorText(text="The ID file being used is: ")
	short ERR_BSAFE_DISPLAY_IDFILE = (PKG_BSAFE_STR);
	@ErrorText(text="Prompt for certificate in UI and wait for response")
	short ERR_BSAFE_CREATECERTIFICATE_ANDWAIT = (PKG_BSAFE_STR+97);
	@ErrorText(text="Insufficient memory for attempted security operation.")
	short ERR_BSAFE3_TE_ALLOC = ERR_BSAFE_NOMEMORY;
	@ErrorText(text="Invalid ASN.1 syntax")
	short ERR_BSAFE3_TE_ATTRIBUTE_COUNT = ERR_ASN1_INV_SYNTAX;
	@ErrorText(text="Invalid ASN.1 syntax")
	short ERR_BSAFE3_TE_ATTRIBUTE_NOT_FOUND = ERR_ASN1_INV_SYNTAX;
	@ErrorText(text="Invalid ASN.1 syntax")
	short ERR_BSAFE3_TE_ATTRIBUTE_TAG = ERR_ASN1_INV_SYNTAX;
	@ErrorText(text="Attribute type is unrecognized ")
	short ERR_BSAFE3_TE_ATTRIBUTE_TYPE = ERR_BSAFE2_ATTRIBUTE_UNKNOWN;
	@ErrorText(text="Illegal or unexpected ASN.1 data type")
	short ERR_BSAFE3_TE_ATTRIBUTE_VALUE = ERR_ASN1_ILL_DATATYPE;
	@ErrorText(text="Illegal or unsupported ASN.1 data length")
	short ERR_BSAFE3_TE_ATTRIBUTE_VALUE_LEN = ERR_ASN1_ILL_DATALENGTH;
	@ErrorText(text="Cryptographic error: invalid message format")
	short ERR_BSAFE3_TE_BEGIN_PEM = ERR_BSAFE_INV_MSG_FORMAT;
	@ErrorText(text="Invalid ASN.1 syntax")
	short ERR_BSAFE3_TE_BER_ENCODING = ERR_ASN1_INV_SYNTAX;
	@ErrorText(text="Operation canceled")
	short ERR_BSAFE3_TE_CANCEL = ERR_BSAFE_CANCELED;
	@ErrorText(text="Invalid certificate contents or format")
	short ERR_BSAFE3_TE_CERT_ENCODING = ERR_BSAFE_INV_CERT;
	@ErrorText(text="Invalid certificate contents or format")
	short ERR_BSAFE3_TE_CERT_OBJ = ERR_BSAFE_INV_CERT;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE3_TE_CO_SET = ERR_BSAFE_BADCTX;
	@ErrorText(text="Invalid CRL contents or format")
	short ERR_BSAFE3_TE_CRL_ENCODING = ERR_BSAFE_INV_CRL;
	@ErrorText(text="Invalid CRL contents or format")
	short ERR_BSAFE3_TE_CRL_OBJ = ERR_BSAFE_INV_CRL;
	@ErrorText(text="Unknown data error occurred during cryptographic processing")
	short ERR_BSAFE3_TE_DATA = ERR_BSAFE_GENERIC_DATA;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE3_TE_DBASE = ERR_BSAFE_BADCTX;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE3_TE_DEK_ALG_NOT_SUPPORTED = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE3_TE_DEK_ALG_UNKNOWN = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE3_TE_DIGEST_OBJ = ERR_BSAFE_BADCTX;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE3_TE_ENHANCED_TEXT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="The cryptographic key's format is invalid")
	short ERR_BSAFE3_TE_EXPONENT_EVEN = ERR_BSAFE_KEY_INV_FORMAT;
	@ErrorText(text="The cryptographic key's format is invalid")
	short ERR_BSAFE3_TE_EXPONENT_LEN = ERR_BSAFE_KEY_INV_FORMAT;
	@ErrorText(text="Invalid certificate extensions object")
	short ERR_BSAFE3_TE_EXTENSIONS_OBJ = ERR_BSAFE_INV_EXTENSIONS_OBJ;
	@ErrorText(text="Certificate extension already exists")
	short ERR_BSAFE3_TE_EXTENSION_ALREADY_EXISTS = ERR_BSAFE_CERT_EXT_EXISTS;
	@ErrorText(text="Cryptographic hardware error")
	short ERR_BSAFE3_TE_HARDWARE = ERR_BSAFE_HARDWARE;
	@ErrorText(text="Cryptographic error: invalid message format")
	short ERR_BSAFE3_TE_HEADER = ERR_BSAFE_INV_MSG_FORMAT;
	@ErrorText(text="Invalid parameter passed to cryptographic function")
	short ERR_BSAFE3_TE_INDEX = ERR_BSAFE4_TE_PARAMETER;
	@ErrorText(text="A certificate chain could not be constructed")
	short ERR_BSAFE4_TE_CERT_CHAIN = ERR_BSAFE_MAKING_CERT_CHAIN;
	@ErrorText(text="Unknown data error occurred during cryptographic processing")
	short ERR_BSAFE4_TE_INPUT_LEN = ERR_BSAFE_GENERIC_DATA;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_INPUT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_IO = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE4_TE_LIST_OBJ = ERR_BSAFE_BADCTX;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE4_TE_ME_SET = ERR_BSAFE_BADCTX;
	@ErrorText(text="Could not verify cryptographic signature")
	short ERR_BSAFE4_TE_MESSAGE_SIGNATURE = ERR_BSAFE_BAD_SIGNATURE;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE4_TE_MIC_ALG_NOT_SUPPORTED = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE4_TE_MIC_ALG_UNKNOWN = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="Invalid cryptographic key length")
	short ERR_BSAFE4_TE_MODULUS_LEN = ERR_BSAFE_BAD_KEY_LENGTH;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE4_TE_NAME_OBJ = ERR_BSAFE_BADCTX;
	@ErrorText(text="Bad random number generator state")
	short ERR_BSAFE4_TE_NEED_RANDOM = ERR_BSAFE_BAD_RANDOM_STATE;
	@ErrorText(text="Certificate, private key or CRL was not found")
	short ERR_BSAFE4_TE_NOT_FOUND = ERR_BSAFE_CERTCRL_NOT_FOUND;
	@ErrorText(text="You cannot access portions of this document because it is encrypted and was not intended for you, or you do not have the decryption key.")
	short ERR_BSAFE4_TE_NOT_ME = (PKG_NSF+101)			/* ERR_NOT_SEALED_FOR_YOU	nsferr.h */;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE4_TE_NOT_SUPPORTED = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="Buffer used to receive cryptographic output was too small")
	short ERR_BSAFE4_TE_OUTPUT_LEN = ERR_BSAFE_TOOSMALL;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_OUTPUT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Wrong Password. (Passwords are case sensitive - be sure to use correct upper and lower case.)")
	short ERR_BSAFE4_TE_PASSWORD = (PKG_SECURE+8)			/* ERR_SECURE_BADPASSWORD	secerr.h */;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE4_TE_PBE_ALG_NOT_SUPPORTED = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="An unsupported cryptographic operation was requested")
	short ERR_BSAFE4_TE_PBE_ALG_UNKNOWN = ERR_BSAFE_UNSUPPORTED_CRYPTO_OP;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_PKCS_INPUT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_PKCS_OUTPUT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE4_TE_PKCS_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="The cryptographic key's format is invalid")
	short ERR_BSAFE4_TE_PRIVATE_KEY = ERR_BSAFE_KEY_INV_FORMAT;
	@ErrorText(text="Invalid parameter passed to cryptographic function")
	short ERR_BSAFE4_TE_PROCESS = ERR_BSAFE4_TE_PARAMETER;
	@ErrorText(text="The encrypted data has been modified or the wrong key was used to decrypt it")
	short ERR_BSAFE4_TE_PROTECTED_DATA = ERR_BSAFE_BADDATA;
	@ErrorText(text="The cryptographic key's format is invalid")
	short ERR_BSAFE4_TE_PUBLIC_KEY = ERR_BSAFE_KEY_INV_FORMAT;
	@ErrorText(text="Bad random number generator state")
	short ERR_BSAFE4_TE_RANDOM_OBJ = ERR_BSAFE_BAD_RANDOM_STATE;
	@ErrorText(text="Unsupported certificate or CRL signature algorithm")
	short ERR_BSAFE4_TE_SIGNATURE_ALG_NOT_SUPPORTED = ERR_BSAFE_UNSUPPORTED_CERTCRLSIG;
	@ErrorText(text="Unsupported certificate or CRL signature algorithm")
	short ERR_BSAFE5_TE_SIGNATURE_ALG_UNKNOWN = ERR_BSAFE_UNSUPPORTED_CERTCRLSIG;
	@ErrorText(text="Cryptographic error: invalid message format")
	short ERR_BSAFE5_TE_TEXT_ENCODING = ERR_BSAFE_INV_MSG_FORMAT;
	@ErrorText(text="Data streaming error encountered during cryptographic operation")
	short ERR_BSAFE5_TE_TEXT_STREAM = ERR_BSAFE_DATA_STREAM;
	@ErrorText(text="Invalid parameter passed to cryptographic function")
	short ERR_BSAFE5_TE_TOKEN = ERR_BSAFE4_TE_PARAMETER;
	@ErrorText(text="Your certificate has expired")
	short ERR_BSAFE5_TE_VALIDITY = (PKG_SECURE+28)			/* ERR_SECURE_EXPIRED_CERT	secerr.h */;
	@ErrorText(text="Bad Security Context information")
	short ERR_BSAFE5_TE_YOU_SET = ERR_BSAFE_BADCTX;
	@ErrorText(text="Invalid certificate contents or format")
	short ERR_CERT_MALFORMED = ERR_BSAFE_INV_CERT;
	@ErrorText(text="The ID file is not a Certifier ID file and cannot be used to issue certificates")
	short ERR_KEYRING_MUSTBE_CA = ERR_BSAFE_MUSTBE_CERTIFIER;

}
