package com.mindoo.domino.jna.errors.errortexts;

public interface IDbdrvErr extends IGlobalErr {

	@ErrorText(text="Insufficient arguments for database function")
	short ERR_DBD_INSUFF_ARGS = PKG_DBD+1;
	@ErrorText(text="Incorrect datatype for database function")
	short ERR_DBD_DATATYPE = PKG_DBD+2;
	@ErrorText(text="The necessary external database driver cannot be located")
	short ERR_DBD_CLASSDRV = PKG_DBD+3;
	@ErrorText(text="Database sessions still open - must be closed by the time Term is called")
	short ERR_DBD_SESSIONS_ACTIVE = PKG_DBD+4;
	@ErrorText(text="Cannot open specified database, no match for specified Replica ID can be found")
	short ERR_DBD_RDATABASE = PKG_DBD+5;
	@ErrorText(text="The specified database driver does not support this function")
	short ERR_DBD_FUNCTION = PKG_DBD+6;
	@ErrorText(text="Too many arguments for database function")
	short ERR_DBD_TOOMANY_ARGS = PKG_DBD+7;
	@ErrorText(text="The data types of two matching results are incompatible")
	short ERR_DBD_INCOMPAT_TYPE = PKG_DBD+8;
	@ErrorText(text="The table was modified - retry after updating")
	short ERR_DBD_MOD_RETRY = PKG_DBD+9;
	@ErrorText(text="A view of that name cannot be found in the specified database")
	short ERR_DBD_NO_VIEW = PKG_DBD+10;
	@ErrorText(text="The specified database lookup generated more than 65,000 bytes of results, which is too large for Notes to handle in this context.")
	short ERR_DBD_64K = PKG_DBD+12;
	@ErrorText(text="<Database Driver>Driver does not have capability required")
	short ERR_DBD_NOT_CAPABLE = PKG_DBD+21;
	@ErrorText(text="<Database Driver>Insufficient user privileges")
	short ERR_DBD_NOT_ALLOWED = PKG_DBD+22;
	@ErrorText(text="<Database Driver>DataLens support system not initialized")
	short ERR_DBD_NOT_INITIALIZED = PKG_DBD+23;
	@ErrorText(text="<Database Driver>Complete driver/connection failure")
	short ERR_DBD_SYSTEM_FAILURE = PKG_DBD+24;
	@ErrorText(text="<Database Driver>Unrecoverable network or IPC error")
	short ERR_DBD_TRANSPORT_ERROR = PKG_DBD+25;
	@ErrorText(text="<Database Driver>Network connection not responding")
	short ERR_DBD_TRANSPORT_FAILURE = PKG_DBD+26;
	@ErrorText(text="<Database Driver>Tried to close parent with active child")
	short ERR_DBD_CHILD_HANDLE_OPEN = PKG_DBD+27;
	@ErrorText(text="<Database Driver>Bad connection handle")
	short ERR_DBD_BAD_CONNECTION_HANDLE = PKG_DBD+28;
	@ErrorText(text="<Database Driver>Invalid browsing handle")
	short ERR_DBD_BAD_BROWSER_HANDLE = PKG_DBD+29;
	@ErrorText(text="<Database Driver>Gab couldn't allocate memory for handle")
	short ERR_DBD_NO_HANDLE_MEMORY = PKG_DBD+30;
	@ErrorText(text="<Database Driver>Bad name for driver or database")
	short ERR_DBD_BAD_NAME = PKG_DBD+31;
	@ErrorText(text="<Database Driver>Driver located but could not be loaded")
	short ERR_DBD_DRIVER_LOAD_ERROR = PKG_DBD+32;
	@ErrorText(text="<Database Driver>Not a valid collection node name")
	short ERR_DBD_NO_COLLECTION_NODE = PKG_DBD+33;
	@ErrorText(text="<Database Driver>No more records or browse items")
	short ERR_DBD_END_OF_DATA = PKG_DBD+34;
	@ErrorText(text="<Database Driver>Browser handle not positioned yet")
	short ERR_DBD_UNPOSITIONED = PKG_DBD+35;
	@ErrorText(text="<Database Driver>Returned name truncated to fit in buffer")
	short ERR_DBD_NAME_TRUNCATED = PKG_DBD+36;
	@ErrorText(text="<Database Driver>Bad user/application string")
	short ERR_DBD_BAD_USER_NAME = PKG_DBD+37;
	@ErrorText(text="<Database Driver>Bad authorization string")
	short ERR_DBD_BAD_PASSWORD = PKG_DBD+38;
	@ErrorText(text="<Database Driver>Memory allocation/deallocation error")
	short ERR_DBD_DRIVER_OUT_OF_MEMORY = PKG_DBD+39;
	@ErrorText(text="<Database Driver>Driver-specific error")
	short ERR_DBD_DRIVER_FAILURE = PKG_DBD+40;
	@ErrorText(text="<Database Driver>Can't locate driver registration list")
	short ERR_DBD_NO_REGISTRATION = PKG_DBD+41;
	@ErrorText(text="<Database Driver>Can't read browse item")
	short ERR_DBD_BAD_BROWSE_DATA = PKG_DBD+42;
	@ErrorText(text="<Database Driver>Can't read registration data")
	short ERR_DBD_BROWSE_ACCESS_ERROR = PKG_DBD+43;
	@ErrorText(text="<Database Driver>Bad argument to driver")
	short ERR_DBD_INVALID_ARGUMENT = PKG_DBD+44;
	@ErrorText(text="<Database Driver>Return handle to already open driver or database")
	short ERR_DBD_DUPLICATE_HANDLE = PKG_DBD+45;
	@ErrorText(text="<Database Driver>Warning: database opened with another userid")
	short ERR_DBD_MULTIPLE_USERS = PKG_DBD+46;
	@ErrorText(text="<Database Driver>Attempt to alter read-only data")
	short ERR_DBD_READ_ONLY = PKG_DBD+52;
	@ErrorText(text="<Database Driver>Database memory exhausted")
	short ERR_DBD_NO_ROOM = PKG_DBD+53;
	@ErrorText(text="<Database Driver>Current transaction aborted")
	short ERR_DBD_TRANSACTION_ABORT = PKG_DBD+54;
	@ErrorText(text="<Database Driver>Driver uses less restrictive model than application")
	short ERR_DBD_BAD_MEMORY_MANAGER = PKG_DBD+55;
	@ErrorText(text="<Database Driver>Database could not be located")
	short ERR_DBD_BAD_DATABASE_NAME = PKG_DBD+56;
	@ErrorText(text="<Database Driver>Database already opened by current thread")
	short ERR_DBD_OPEN_DATABASE = PKG_DBD+57;
	@ErrorText(text="<Database Driver>Cursor still open on close database request")
	short ERR_DBD_OPEN_CURSOR = PKG_DBD+58;
	@ErrorText(text="<Database Driver>Requested extension does not exist")
	short ERR_DBD_BAD_EXTENSION = PKG_DBD+59;
	@ErrorText(text="<Database Driver>Invalid action")
	short ERR_DBD_BAD_ACTION = PKG_DBD+60;
	@ErrorText(text="<Database Driver>Column does not exist")
	short ERR_DBD_BAD_COLUMN = PKG_DBD+61;
	@ErrorText(text="<Database Driver>New name for table or column is invalid")
	short ERR_DBD_BAD_NEW_NAME = PKG_DBD+62;
	@ErrorText(text="<Database Driver>Table or view does not exist")
	short ERR_DBD_BAD_TABLE = PKG_DBD+63;
	@ErrorText(text="<Database Driver>Input comment/label has been truncated")
	short ERR_DBD_TRUNCATED = PKG_DBD+64;
	@ErrorText(text="<Database Driver>Invalid index specification")
	short ERR_DBD_BAD_INDEX = PKG_DBD+65;
	@ErrorText(text="<Database Driver>Invalid column, etc. count")
	short ERR_DBD_BAD_COUNT = PKG_DBD+66;
	@ErrorText(text="<Database Driver>Invalid query specification")
	short ERR_DBD_BAD_QUERY = PKG_DBD+67;
	@ErrorText(text="<Database Driver>Invalid synonym specification")
	short ERR_DBD_BAD_SYNONYM = PKG_DBD+68;
	@ErrorText(text="<Database Driver>Invalid privilege specification")
	short ERR_DBD_BAD_PRIVILEGE = PKG_DBD+69;
	@ErrorText(text="<Database Driver>Invalid User ID specification")
	short ERR_DBD_BAD_USERID = PKG_DBD+70;
	@ErrorText(text="<Database Driver>Invalid wheretree specification")
	short ERR_DBD_BAD_WHERE = PKG_DBD+71;
	@ErrorText(text="<Database Driver>Cursor storage is full")
	short ERR_DBD_TOO_MANY_CURSORS = PKG_DBD+72;
	@ErrorText(text="<Database Driver>Invalid cursor handle")
	short ERR_DBD_BAD_CURSOR = PKG_DBD+73;
	@ErrorText(text="<Database Driver>Attempt to access unopened item")
	short ERR_DBD_NOT_OPEN = PKG_DBD+74;
	@ErrorText(text="<Database Driver>Invalid statement handle")
	short ERR_DBD_BAD_STATEMENT = PKG_DBD+75;
	@ErrorText(text="<Database Driver>Invalid xferblock format")
	short ERR_DBD_BAD_XFERBLOCK = PKG_DBD+76;
	@ErrorText(text="<Database Driver>Cursor is open")
	short ERR_DBD_NOT_CLOSED = PKG_DBD+77;
	@ErrorText(text="<Database Driver>Too few values supplied to where-parms")
	short ERR_DBD_TOO_FEW_PARAMETERS = PKG_DBD+78;
	@ErrorText(text="<Database Driver>Too many values supplied to where-parms")
	short ERR_DBD_TOO_MANY_PARAMETERS = PKG_DBD+79;
	@ErrorText(text="<Database Driver>Tried to move cursor past existing rows")
	short ERR_DBD_BAD_ROW = PKG_DBD+80;
	@ErrorText(text="<Database Driver>First record has not arrived yet")
	short ERR_DBD_NO_DATA_YET = PKG_DBD+81;
	@ErrorText(text="<Database Driver>Referenced column does not contain long data")
	short ERR_DBD_NO_LONG_DATA = PKG_DBD+82;
	@ErrorText(text="<Database Driver>Driver limit on open long data columns exceeded")
	short ERR_DBD_TOO_MANY_LONGS = PKG_DBD+83;
	@ErrorText(text="<Database Driver>Invalid buffer length")
	short ERR_DBD_BAD_LENGTH = PKG_DBD+84;
	@ErrorText(text="<Database Driver>Invalid position specified in long data column")
	short ERR_DBD_BAD_POSITION = PKG_DBD+85;
	@ErrorText(text="<Database Driver>An inserted record failed a view check")
	short ERR_DBD_BAD_VIEW_CHECK = PKG_DBD+86;
	@ErrorText(text="<Database Driver>Setting field null not permitted")
	short ERR_DBD_NO_NULLS = PKG_DBD+87;
	@ErrorText(text="<Database Driver>Can't add duplicate val to unique index")
	short ERR_DBD_NOT_UNIQUE = PKG_DBD+88;
	@ErrorText(text="<Database Driver>Data type mismatch on output")
	short ERR_DBD_BAD_DATA = PKG_DBD+89;
	@ErrorText(text="<Database Driver>Proposed statement name is invalid")
	short ERR_DBD_BAD_STATEMENT_NAME = PKG_DBD+90;
	@ErrorText(text="<Database Driver>Attempt to open a table already open")
	short ERR_DBD_ALREADY_OPEN = PKG_DBD+91;
	@ErrorText(text="<Database Driver>Isolation level cannot be altered")
	short ERR_DBD_ALREADY_ISOLATED = PKG_DBD+92;
	@ErrorText(text="<Database Driver>Invalid isolation level specification")
	short ERR_DBD_BAD_ISOLATION = PKG_DBD+93;
	@ErrorText(text="<Database Driver>Browser is not positioned at a table")
	short ERR_DBD_NO_CURRENT_TABLE = PKG_DBD+94;
	@ErrorText(text="<Database Driver>Browser is not positioned at a column")
	short ERR_DBD_NO_CURRENT_COLUMN = PKG_DBD+95;
	@ErrorText(text="<Database Driver>Second open cursor with no change to result set")
	short ERR_DBD_SAME_RESULT = PKG_DBD+96;
	@ErrorText(text="<Database Driver>Can't translate LMBCS code to native")
	short ERR_DBD_UNTRANSLATABLE_LMBCS = PKG_DBD+97;
	@ErrorText(text="<Database Driver>Cursor not at record for update or deletion")
	short ERR_DBD_NO_CURRENT_RECORD = PKG_DBD+98;
	@ErrorText(text="<Database Driver>Unacceptable string truncation")
	short ERR_DBD_STRING_TRUNCATED = PKG_DBD+99;
	@ErrorText(text="<Database Driver>Unrecoverable transfer error")
	short ERR_DBD_TRANSFER_ERROR = PKG_DBD+100;
	@ErrorText(text="<Database Driver>Driver connection block corrupted")
	short ERR_DBD_BAD_DCCB = PKG_DBD+101;
	@ErrorText(text="<Database Driver>Database connection block corrupted")
	short ERR_DBD_BAD_DDCB = PKG_DBD+102;
	@ErrorText(text="<Database Driver>Corrupted envblk")
	short ERR_DBD_BAD_ENVBLK = PKG_DBD+103;
	@ErrorText(text="<Database Driver>Invalid querytree")
	short ERR_DBD_BAD_QUERYTREE = PKG_DBD+104;
	@ErrorText(text="<Database Driver>Invalid tabname")
	short ERR_DBD_BAD_TABNAME = PKG_DBD+105;
	@ErrorText(text="<Database Driver>Invalid catalog browser")
	short ERR_DBD_BAD_CBROWSER = PKG_DBD+106;
	@ErrorText(text="<Database Driver>Invalid colid")
	short ERR_DBD_BAD_COLID = PKG_DBD+107;
	@ErrorText(text="<Database Driver>Invalid wherenode")
	short ERR_DBD_BAD_WHERENODE = PKG_DBD+108;
	@ErrorText(text="<Database Driver>New column definition is not valid")
	short ERR_DBD_BAD_NEW_DEFINITION = PKG_DBD+109;
	@ErrorText(text="<Database Driver>Scroll option with current cursor invalid")
	short ERR_DBD_SCROLLED_CURSOR = PKG_DBD+110;
	@ErrorText(text="<Database Driver>Cardinality error")
	short ERR_DBD_CARDINALITY = PKG_DBD+111;
	@ErrorText(text="<Database Driver>Back end database-specific error")
	short ERR_DBD_BACKEND_DB_ERROR = PKG_DBD+112;
	@ErrorText(text="<Database Driver>Configuration string is not valid")
	short ERR_DBD_BAD_CONFIG_STRING = PKG_DBD+113;
	@ErrorText(text="<Database Driver>Driver can't use application's platform")
	short ERR_DBD_BAD_PLATFORM = PKG_DBD+114;
	@ErrorText(text="<Database Driver>Translation table cannot be loaded")
	short ERR_DBD_CODEPAGE_LOAD_ERROR = PKG_DBD+115;
	@ErrorText(text="<Database Driver>Memory map error")
	short ERR_DBD_MAPMEM_ERROR = PKG_DBD+116;
	@ErrorText(text="<Database Driver>Required resource cannot be loaded")
	short ERR_DBD_RESOURCE_LOAD_ERROR = PKG_DBD+117;
	@ErrorText(text="<Database Driver>Error building statdef, no details")
	short ERR_DBD_STATUS_ERROR = PKG_DBD+118;
	@ErrorText(text="<Database Driver>Column type is not valid")
	short ERR_DBD_UNTRANSLATABLE_COLTYPE = PKG_DBD+119;
	@ErrorText(text="<Database Driver>Operation on statement aborted")
	short ERR_DBD_STATEMENT_ABORT = PKG_DBD+120;
	@ErrorText(text="<Database Driver>Data is too long for column")
	short ERR_DBD_DATA_TOO_LONG = PKG_DBD+121;
	@ErrorText(text="<Database Driver>Numeric value is outside accepted range")
	short ERR_DBD_BAD_NUMERIC_VALUE = PKG_DBD+122;
	@ErrorText(text="<Database Driver>Function call is not allowed in state")
	short ERR_DBD_STATE_VIOLATION = PKG_DBD+123;
	@ErrorText(text="<Database Driver>Browser still open on close driver/database")
	short ERR_DBD_DEPENDENT_BROWSER_OPEN = PKG_DBD+124;
	@ErrorText(text="Database not specified")
	short ERR_DBD_NO_DB = PKG_DBD+125;
	@ErrorText(text="<Database Access > DBD internal memory structure for database is Invalid!")
	short ERR_DBD_STRUCT_IS_INVALID = PKG_DBD+126;
	@ErrorText(text="<Database Access > DBD internal memory structure for database is NULL!")
	short ERR_DBD_STRUCT_IS_NULL = PKG_DBD+127;
	@ErrorText(text="<Data Access Application Layer>Invalid session handle")
	short ERR_DAL_BAD_SESSION = PKG_DBD+130;
	@ErrorText(text="<Data Access Application Layer>Invalid index to queue")
	short ERR_DAL_BAD_QINDEX = PKG_DBD+131;
	@ErrorText(text="<Data Access Application Layer>Invalid registration file entry")
	short ERR_DAL_REGFILE_ERROR = PKG_DBD+132;
	@ErrorText(text="<Data Access Application Layer>Too few data-source connection levels")
	short ERR_DAL_MORE_LEVELS_REQUIRED = PKG_DBD+133;
	@ErrorText(text="<Data Access Application Layer>At least one session is still open")
	short ERR_DAL_OPEN_SESSION = PKG_DBD+134;
	@ErrorText(text="<Data Access Application Layer>Unknown database command")
	short ERR_DAL_BAD_COMMAND = PKG_DBD+135;
	@ErrorText(text="<Data Access Application Layer>Too few command arguments")
	short ERR_DAL_TOO_FEW_ARGS = PKG_DBD+136;
	@ErrorText(text="<Data Access Application Layer>User ID required")
	short ERR_DAL_USERID_REQUIRED = PKG_DBD+137;
	@ErrorText(text="<Data Access Application Layer>Password required")
	short ERR_DAL_PASSWORD_REQUIRED = PKG_DBD+138;
	@ErrorText(text="<Data Access Application Layer>Too many command arguments")
	short ERR_DAL_TOO_MANY_ARGS = PKG_DBD+139;
	@ErrorText(text="<Data Access Application Layer>Driver's API version is not supported")
	short ERR_DAL_BAD_API_VERSION = PKG_DBD+140;
	@ErrorText(text="<Data Access Application Layer>Memory allocation/deallocation error")
	short ERR_DAL_MEMORY_ERROR = PKG_DBD+141	;
	@ErrorText(text="<Data Access Application Layer>Invalid command argument")
	short ERR_DAL_INVALID_ARGUMENT = PKG_DBD+142;
	@ErrorText(text="<Data Access Application Layer>Driver has insufficient capabilities")
	short ERR_DAL_DRIVER_NOT_CAPABLE = PKG_DBD+143;
	@ErrorText(text="<Data Access Application Layer>Error loading driver")
	short ERR_DAL_DRIVER_LOAD_ERROR = PKG_DBD+144;
	@ErrorText(text="<Data Access Application Layer>Requested column doesn't exist")
	short ERR_DAL_BAD_COLUMN = PKG_DBD+145;
	@ErrorText(text="<Data Access Application Layer>Unsupported data type")
	short ERR_DAL_UNSUPPORTED_TYPE = PKG_DBD+146;
	@ErrorText(text="<Data Access Application Layer>Command argument string too long")
	short ERR_DAL_ARG_TOO_LONG = PKG_DBD+147;
	@ErrorText(text="<Data Access Application Layer>Data conversion error")
	short ERR_DAL_CONVERSION_ERROR = PKG_DBD+148;
	@ErrorText(text="<Data Access Application Layer>Data-source charset out-of-range")
	short ERR_DAL_INVALID_CHARSET = PKG_DBD+149;
	@ErrorText(text="<Data Access Application Layer>Exception error")
	short ERR_DAL_EXCEPTION_ERROR = PKG_DBD+171;
	@ErrorText(text="<Data Access Application Layer>Connection cancelled")
	short ERR_DAL_CONNECTCANCEL_ERROR = PKG_DBD+172;
	@ErrorText(text="<Data Access Application Layer>Must supply ID and password in script")
	short ERR_DAL_SERVERPROCESS_ERROR = PKG_DBD+173;
	@ErrorText(text="<Data Access Application Layer>@DbCommand contains unsupported function")
	short ERR_DAL_UNSUPPORTEDFUNC_ERROR = PKG_DBD+174;
	@ErrorText(text="<Data Access Application Layer>Could not prepare SQL statement - possible invalid column or table name")
	short ERR_DAL_SQLPREPARE_ERROR = PKG_DBD+175;
	@ErrorText(text="<Data Access Application Layer>Could not execute @db function")
	short ERR_DAL_SQLEXECUTE_ERROR = PKG_DBD+176;
	@ErrorText(text="<Data Access Application Layer>Bad authorization string")
	short ERR_DAL_PASSWORD_ERROR = PKG_DBD+177;
	@ErrorText(text="<Data Access Application Layer>Null values found - cancelling @db function")
	short ERR_DAL_NULLSFOUND_ERROR = PKG_DBD+178;
	@ErrorText(text="<Data Access Application Layer>Invalid NULL replace value")
	short ERR_DAL_INVALID_NULL_REPLACE_ERROR = PKG_DBD+179;
	@ErrorText(text="The specified database lookup generated more than 65,534 results, which is too large for Notes to handle.")
	short ERR_DBD_RESULT_COUNT_LIMIT_EXCEED = PKG_DBD+180;
	@ErrorText(text="DBD cannot get the list of address books for the local server.")
	short ERR_DBD_CANT_GET_SERVER_NABS = PKG_DBD+181;

}
