package com.mindoo.domino.jna.errors.errortexts;

public interface IMiscErr extends IGlobalErr {

	@ErrorText(text="Deleting a non-empty queue")
	short ERR_QUEUE_NOT_EMPTY = PKG_MISC+1;
	@ErrorText(text="No more entries to dequeue")
	short ERR_QUEUE_EMPTY = PKG_MISC+2;
	@ErrorText(text="Invalid text pattern")
	short ERR_TEXT_PATTERN = PKG_MISC+3;
	@ErrorText(text="Entry not found in index")
	short ERR_NOT_FOUND = PKG_MISC+4;
	@ErrorText(text="Cannot convert text to a number")
	short ERR_FLOAT_CONVERSION = PKG_MISC+5;
	@ErrorText(text="No subindex available")
	short ERR_NO_SUBINDEX = PKG_MISC+6;
	@ErrorText(text="Subindex cannot be deleted while non-empty")
	short ERR_NOT_EMPTY = PKG_MISC+7;
	@ErrorText(text="Entry already in index")
	short ERR_DUPLICATE_KEY = PKG_MISC+8;
	@ErrorText(text="Output Buffer Overflow")
	short ERR_BUFFER_OVERFLOW = PKG_MISC+9;
	@ErrorText(text="Invalid International Format Specifier")
	short ERR_IFMT = PKG_MISC+10;
	@ErrorText(text="Invalid Time/Date Format Specifier")
	short ERR_TFMT = PKG_MISC+11;
	@ErrorText(text="Unable to interpret Time or Date")
	short ERR_TDI_CONV = PKG_MISC+12;
	@ErrorText(text="Invalid Time or Date Encountered")
	short ERR_TDO_CONV = PKG_MISC+13;
	@ErrorText(text="Name too long")
	short ERR_NAME_LENGTH = PKG_MISC+14;
	@ErrorText(text="Value too long")
	short ERR_VALUE_LENGTH = PKG_MISC+15;
	@ErrorText(text="TIMEDATE, not TIMEDATE_PAIR")
	short ERR_NOT_TDPAIR = PKG_MISC+16;
	@ErrorText(text="TIME must be specified, not just DATE")
	short ERR_TREQ = PKG_MISC+17;
	@ErrorText(text="Maximum interval is 24 Hours")
	short ERR_MAXINTERVAL = PKG_MISC+18;
	@ErrorText(text="There is at most 1 code with non-zero frequency")
	short ERR_HUFF0 = PKG_MISC+19;
	@ErrorText(text="Invalid Encoded Data - Attachment may be corrupted")
	short ERR_HUFF1 = PKG_MISC+20;
	@ErrorText(text="Encoded Data Checksum Mismatch - Attachment may be corrupted")
	short ERR_HUFF2 = PKG_MISC+21;
	@ErrorText(text="Corrupted Encoded Data")
	short ERR_HUFF3 = PKG_MISC+22;
	@ErrorText(text="Insufficient memory - a Notes memory pool is full (P)")
	short ERR_POOLFULL = PKG_MISC+23;
	@ErrorText(text="Pool cannot be locked or faulted")
	short ERR_DISCARDED = PKG_MISC+24;
	@ErrorText(text="Index (pool) has been corrupted - will be rebuilt automatically when database is closed or server is restarted")
	short ERR_INVALID_POOL = PKG_MISC+25;
	@ErrorText(text="Invalid pool free chain")
	short ERR_POOL_FREE_CHAIN = PKG_MISC+26;
	@ErrorText(text="Attempt to lock twice using same pool lock")
	short ERR_LOCK_POOL_TWICE = PKG_MISC+27;
	@ErrorText(text="Too many locks on pool")
	short ERR_TOO_MANY_LOCKS = PKG_MISC+28;
	@ErrorText(text="Invalid block handle")
	short ERR_INVALID_BLOCK = PKG_MISC+29;
	@ErrorText(text="Index (link) has been corrupted - will be rebuilt automatically when database is closed or server is restarted")
	short ERR_MEMBER_NUMBER = PKG_MISC+30;
	@ErrorText(text="Subindex already created")
	short ERR_ALREADY_SUBINDEX = PKG_MISC+31;
	@ErrorText(text="Access control list version is unsupported")
	short ERR_ACL_VERSION = PKG_MISC+32;
	@ErrorText(text="Access control list is corrupted")
	short ERR_ACL_CORRUPT = PKG_MISC+33;
	@ErrorText(text="The access control list is full.  If you need to add new users, place existing users into groups on the list.")
	short ERR_ACL_FULL = PKG_MISC+34;
	@ErrorText(text="The name is already in the list.")
	short ERR_ACL_INLIST = PKG_MISC+35;
	@ErrorText(text="The name is not in the list.")
	short ERR_ACL_NOENTRY = PKG_MISC+36;
	@ErrorText(text="Default cannot be deleted.")
	short ERR_ACL_UNDELETABLE = PKG_MISC+37;
	@ErrorText(text="Unrecognized DATE format specifier")
	short ERR_BAD_DATE_FMT = PKG_MISC+38;
	@ErrorText(text="Unrecognized TIME format specifier")
	short ERR_BAD_TIME_FMT = PKG_MISC+39;
	@ErrorText(text="Unrecognized ZONE format specifier")
	short ERR_BAD_ZONE_FMT = PKG_MISC+40;
	@ErrorText(text="Unrecognized date/time STRUCTURE format specifier")
	short ERR_BAD_STRUCT_FMT = PKG_MISC+41;
	@ErrorText(text="Unrecognized date/time format specifier")
	short ERR_UNKNOWN_TFMT = PKG_MISC+42;
	@ErrorText(text="Unrecognized number format specifier")
	short ERR_UNKNOWN_NFMT = PKG_MISC+43;
	@ErrorText(text="Access control list must contain at least one Manager")
	short ERR_NO_MANAGER = PKG_MISC+44;
	@ErrorText(text="Attempt to free block that is already free")
	short ERR_FREE_BLOCK_TWICE = PKG_MISC+45;
	@ErrorText(text="Server error: ")
	short ERR_SERVER_ERR_MSG = PKG_MISC+46;
	@ErrorText(text="Your name is listed to access this database, but with a different ID")
	short ERR_WRONG_LICENSE = PKG_MISC+47;
	@ErrorText(text="Error opening Character Set Translation File")
	short ERR_CTF_FILEOPEN = PKG_MISC+48;
	@ErrorText(text="Error reading Character Set Translation File")
	short ERR_CTF_FILEREAD = PKG_MISC+49;
	@ErrorText(text="Delivery time expired")
	short ERR_DELIVERY_TIMEOUT = PKG_MISC+50;
	@ErrorText(text="%ld msec%n")
	short ERR_SHOW_TIMER1 = PKG_MISC+51;
	@ErrorText(text="%ld msec total, %ld iter -> %ld usec/iter%n")
	short ERR_SHOW_TIMER2 = PKG_MISC+52;
	@ErrorText(text="Memory preceding pool block has been destroyed")
	short ERR_POOL_MARKER1 = PKG_MISC+53;
	@ErrorText(text="Memory following pool block has been destroyed")
	short ERR_POOL_MARKER2 = PKG_MISC+54;
	@ErrorText(text="%nPool block:   Length: %d     Offset: %04x%n")
	short ERR_POOL_BLOCK_DUMP = PKG_MISC+55;
	@ErrorText(text="        TRUNCATED from %d bytes to 1024%n")
	short ERR_DUMP_TRUNCATED = PKG_MISC+56;
	@ErrorText(text="%08lx %08lx %08lx %08lx:  %04x      '%s'%n")
	short ERR_DUMP_FORMAT4 = PKG_MISC+57;
	@ErrorText(text="%04x %04x %04x %04x %04x %04x %04x %04x:  %04x      '%s'%n")
	short ERR_DUMP_FORMAT2 = PKG_MISC+58;
	@ErrorText(text="OSBlockQueueInsert: block already on queue")
	short ERR_POOLQ_ALREADY_THERE = PKG_MISC+59;
	@ErrorText(text="OSBlockQueue: bad queue chain")
	short ERR_POOLQ_BAD_CHAIN = PKG_MISC+60;
	@ErrorText(text="OSBlockQueueRemove: Attempted to remove queue head")
	short ERR_POOLQ_REMOVE_HEAD = PKG_MISC+61;
	@ErrorText(text="Insufficient contiguous memory to reallocate in-place (P)")
	short ERR_POOLREALLOCFIXED = PKG_MISC+62;
	@ErrorText(text="(Pool does not support block sizes)")
	short ERR_NO_BLOCK_SIZES = PKG_MISC+63;
	@ErrorText(text="Atom table is full")
	short ERR_ATOM_TABLE_FULL = PKG_MISC+64;
	@ErrorText(text="The index is too big.  Change view to select fewer documents; or reduce number/size of columns in the view.")
	short ERR_TOO_MANY_POOLS = PKG_MISC+65;
	@ErrorText(text="Error opening dictionary file")
	short ERR_DICT_FILEOPEN = PKG_MISC+66;
	@ErrorText(text="Attempt to delete non-empty Local DPool")
	short ERR_POOL_NOT_EMPTY = PKG_MISC+67;
	@ErrorText(text="Function not allowed for Local DPool")
	short ERR_LOCAL_POOL = PKG_MISC+68;
	@ErrorText(text="-Default-")
	short ERR_ACL_DEFAULT_NAME = PKG_MISC+69;
	@ErrorText(text="Invalid translation file. Check your User Preferences to make sure that file is properly specified.")
	short ERR_CTF_INVALID = PKG_MISC+70;
	@ErrorText(text="Array is full")
	short ERR_ARRAY_FULL = PKG_MISC+71;
	@ErrorText(text="Invalid ID table")
	short ERR_IDTABLE_INVALID = PKG_MISC+72;
	@ErrorText(text="Invalid file type")
	short ERR_FILE_INVALID = PKG_MISC+73;
	@ErrorText(text="Directory does not exist")
	short ERR_DIRECTORY_INVALID = PKG_MISC+74;
	@ErrorText(text="This feature is not yet implemented")
	short ERR_NOT_YET_IMPLEMENTED = PKG_MISC+75;
	@ErrorText(text="-- %lu (0x%04lx) bytes of 0 --")
	short ERR_DUMP_ZEROS_SUPPRESSED = PKG_MISC+76;
	@ErrorText(text="Invalid Name Parsing buffer size")
	short ERR_DN_COMP_VERSION = PKG_MISC+77;
	@ErrorText(text="Entry not found in index or view's index not built")
	short ERR_ENTRY_OR_VIEW_NOT_FOUND = PKG_MISC+79;
	@ErrorText(text="Line wrap must be a numeric value greater then zero")
	short ERR_LINEWRAP = PKG_MISC+80;
	@ErrorText(text="The requested operation will be performed in the background.")
	short ERR_QUEUED_TO_BKGND = PKG_MISC+81;
	@ErrorText(text=" not found in server statistics table")
	short ERR_STAT_NOT_FOUND = PKG_MISC+82;
	@ErrorText(text="ID table checksum mismatch")
	short ERR_IDTABLE_CHECKSUM = PKG_MISC+83;
	@ErrorText(text="Insufficient memory - Statistics pool is full.")
	short ERR_STAT_POOLFULL = PKG_MISC+84;
	@ErrorText(text="Insufficient memory - a Notes memory pool is full (DP)")
	short ERR_DPOOLFULL = PKG_MISC+85;
	@ErrorText(text="Insufficient memory - a Notes memory pool is full (VP)")
	short ERR_VPOOLFULL = PKG_MISC+86;
	@ErrorText(text="Insufficient memory - a Notes memory pool is full (LDP)")
	short ERR_LDPOOLFULL = PKG_MISC+87;
	@ErrorText(text="Sorry, this database is on a server running a previous version of IBM Notes that does not support folders.")
	short ERR_FOLDER_OLDSERVER = PKG_MISC+88;
	@ErrorText(text="Unable to extend an ID table - insufficient memory.")
	short ERR_SPARE_FULL = PKG_MISC+89;
	@ErrorText(text="Invalid Signature - VPOOL structure corrupt")
	short ERR_CORRUPT_VPOOL = PKG_MISC+90;
	@ErrorText(text="Abstract: the abstract size must be greater than 0")
	short ERR_ABSTRACT_INVALID_SIZE = PKG_MISC+91;
	@ErrorText(text="Invalid ID table - unexpected opcode")
	short ERR_OPCODE = PKG_MISC+92;
	@ErrorText(text="Invalid ID table - expected Assign opcode")
	short ERR_ASSIGN = PKG_MISC+93;
	@ErrorText(text="Insufficient memory - Message Queue pool is full.")
	short ERR_MQ_POOLFULL = PKG_MISC+94;
	@ErrorText(text="Timeout occurred waiting for message.")
	short ERR_MQ_TIMEOUT = PKG_MISC+95;
	@ErrorText(text="Message Queue scan was aborted.")
	short ERR_MQSCAN_ABORT = PKG_MISC+96;
	@ErrorText(text="Message Queue name already in use.")
	short ERR_DUPLICATE_MQ = PKG_MISC+97;
	@ErrorText(text="No Message Queue with that name.")
	short ERR_NO_SUCH_MQ = PKG_MISC+98;
	@ErrorText(text="Message Queue is full.")
	short ERR_MQ_EXCEEDED_QUOTA = PKG_MISC+99;
	@ErrorText(text="Message Queue is empty.")
	short ERR_MQ_EMPTY = PKG_MISC+100;
	@ErrorText(text="Message is larger than the buffer provided.")
	short ERR_MQ_BFR_TOO_SMALL = PKG_MISC+101;
	@ErrorText(text="Quit is pending on the Message Queue")
	short ERR_MQ_QUITTING = PKG_MISC+102;
	@ErrorText(text=" cannot be reset.")
	short ERR_STAT_NOT_SET = PKG_MISC+103;
	@ErrorText(text=" was set to zero.")
	short ERR_STAT_SET = PKG_MISC+104;
	@ErrorText(text=" was not reset, please use complete statistic name (Facility.Statname).")
	short ERR_STAT_SET_COMPLETE = PKG_MISC+105;
	@ErrorText(text="Dequeue current message in enumeration")
	short ERR_MQSCAN_DEQUEUE = PKG_MISC+106;
	@ErrorText(text="Delete current message in enumeration")
	short ERR_MQSCAN_DELETE = PKG_MISC+107;
	@ErrorText(text="%A %A created list")
	short ERR_ACL_CREATED = PKG_MISC+108;
	@ErrorText(text="%A %A updated %A")
	short ERR_ACL_UPDATED = PKG_MISC+109;
	@ErrorText(text="%A %A added %A")
	short ERR_ACL_ADDED = PKG_MISC+110;
	@ErrorText(text="%A %A deleted %A")
	short ERR_ACL_DELETED = PKG_MISC+111;
	@ErrorText(text="%A %A updated role %s")
	short ERR_ACL_PRIVNAME_SET = PKG_MISC+112;
	@ErrorText(text="%A %A deleted role %s")
	short ERR_ACL_PRIVNAME_CLEARED = PKG_MISC+113;
	@ErrorText(text="%A is already in the list.")
	short STR_ACL_WHOIS_INLIST = PKG_MISC+114;
	@ErrorText(text="Too many IDs counted vs. header")
	short ERR_IDTABLE_TOOMANY = PKG_MISC+115;
	@ErrorText(text="Too few IDs counted vs. header")
	short ERR_IDTABLE_TOOLITTLE = PKG_MISC+116;
	@ErrorText(text="Same ID encountered in enumeration")
	short ERR_IDTABLE_REPEAT = PKG_MISC+117;
	@ErrorText(text="ID value encountered less than previous ID")
	short ERR_IDTABLE_BACKWARDS = PKG_MISC+118;
	@ErrorText(text="ID missing from encountered table")
	short ERR_IDTABLE_MISSING_ID = PKG_MISC+119;
	@ErrorText(text="A folder or view with this name already exists.")
	short ERR_FOLD_NAME_DUPLICATE = PKG_MISC+120;
	@ErrorText(text="You may not mix shared folders or views with private folders or views.")
	short ERR_MIX_PRIVATE_SHARED = PKG_MISC+121;
	@ErrorText(text="The name specified is too long or contains cascading items that are too long.")
	short ERR_FOLD_NAME_LENGTH = PKG_MISC+122;
	@ErrorText(text="Duplicate privilege name found.")
	short ERR_DUP_PRIV_NAME = PKG_MISC+123;
	@ErrorText(text="Adding entry will cause text list to exceed 64K. Entry not added.")
	short ERR_TEXT_LIST_TOO_BIG = PKG_MISC+126;
	@ErrorText(text="Ring buffer overflow")
	short ERR_TOO_MUCH_RING_DATA = PKG_MISC+129;
	@ErrorText(text="Time range to find will never be found.")
	short ERR_TIMEGAP_TOOBIG = PKG_MISC+130;
	@ErrorText(text="Did not deliver mail messages created by another user.  Check MAIL.BOX for further information.")
	short ERR_MAIL_FOROTHERUSER = PKG_MISC+131;
	@ErrorText(text="Operation requires handle without shared reference count")
	short ERR_MISC_HDL_NOT_DISASSOCIATED = (PKG_MISC+132);
	@ErrorText(text="Unexpected error in use of CDataPipe facility")
	short ERR_MISC_DATA_PIPE_UNEXPECTED = (PKG_MISC+133);
	@ErrorText(text="Corrupted LZ1 Encoded Data.")
	short ERR_LZ1_DECOMPRESS_BAD_DATA = (PKG_MISC+134);
	@ErrorText(text="The date and time specified is in the past.")
	short ERR_DATEISINPAST = (PKG_MISC+135);
	@ErrorText(text="Message Queue has messages outstanding.")
	short ERR_MQ_MSGSPENDING = (PKG_MISC+136);
	@ErrorText(text="String conversion failed.")
	short ERR_STR_CONVERT = (PKG_MISC+137);
	@ErrorText(text="Corrupt UUEncoded Data")
	short ERR_MISC_BAD_UUENCODED_DATA = (PKG_MISC+138);
	@ErrorText(text="Syntax error in IMAP message set")
	short ERR_IMAP_BAD_MESSAGESET = (PKG_MISC+139);
	@ErrorText(text="LDAP BPool Full")
	short ERR_LDAP_POOLFULL = (PKG_MISC+140);
	@ErrorText(text="Certificate conversion failed")
	short ERR_CERT_CONVERT_FAILED = (PKG_MISC+141);
	@ErrorText(text="Code ")
	short ERR_MISC_NOTASCII_CODE_PREFIX = (PKG_MISC+142);
	@ErrorText(text="Block size illegal for BPOOL.")
	short ERR_ILLEGAL_BLOCK_SIZE = (PKG_MISC+143);
	@ErrorText(text="Invalid Signature - BPOOL structure corrupt")
	short ERR_CORRUPT_BPOOL = (PKG_MISC+144);
	@ErrorText(text="Insufficient memory - a Notes memory pool is full (BP)")
	short ERR_BPOOLFULL = (PKG_MISC+145);
	@ErrorText(text="Could not compress buffer.")
	short ERR_LZ1FAILED = (PKG_MISC+146);
	@ErrorText(text="Invalid or NULL handle passed to compression function.")
	short ERR_LZ1NOBUFFER = (PKG_MISC+147);
	@ErrorText(text="An entry already exists.")
	short ERR_ALREADY_EXIST = (PKG_MISC+148);
	@ErrorText(text="Invalid arguments")
	short ERR_MISC_INVALID_ARGS = (PKG_MISC+149);
	@ErrorText(text="Cannot Prepend or Read from a write only stream.")
	short ERR_WRITE_ONLY = (PKG_MISC+150);
	@ErrorText(text="Return value was truncated")
	short ERR_MISC_RETURN_TRUNC = (PKG_MISC+155);
	@ErrorText(text="This database is on a server running a previous version of IBM Domino that does not support this type of view or folder.")
	short ERR_NEWVIEWTYPE_OLDSERVER = (PKG_MISC+156);
	@ErrorText(text="This database version does not support this type of view or folder.")
	short ERR_NEWVIEWTYPE_OLDODS = (PKG_MISC+157);
	@ErrorText(text="End of stream")
	short ERR_MISC_EOS = (PKG_MISC+158);
	@ErrorText(text="Category must be a single string.")
	short ERR_ONLY_ONE_CATEGORY = (PKG_MISC+159);
	@ErrorText(text="MIME part not found")
	short ERR_MISC_MIMEPART_NOT_FOUND = (PKG_MISC+160);
	@ErrorText(text="Link Info not found")
	short ERR_LINKINFO_NOT_FOUND = (PKG_MISC+161);
	@ErrorText(text="Charset info not changed")
	short ERR_MISC_CHARSET_UNCHANGED = (PKG_MISC+162);
	@ErrorText(text="No frame of specified name exists.")
	short ERR_NAMED_FRAME_NOT_FOUND = (PKG_MISC+163);
	@ErrorText(text="Nonexistent frameset specified.")
	short ERR_FRAMESET_UNKNOWN = (PKG_MISC+164);
	@ErrorText(text="Buffer size error")
	short ERR_MISC_BUFFER_SIZE = (PKG_MISC+171);
	@ErrorText(text="Unexpected internal error")
	short ERR_MISC_UNEXPECTED_ERROR = (PKG_MISC+172);
	@ErrorText(text="Insufficient Memory -- Tasks/Stats records pool is full")
	short ERR_MISC_TSRECORDS_POOL_FULL = (PKG_MISC+175);
	@ErrorText(text="Insufficient information to update view or folder design")
	short ERR_VIEW_NOFORMATITEM = (PKG_MISC+177);
	@ErrorText(text="Did not deliver mail messages created by another user.  Check SMTP.BOX for further information.")
	short ERR_MAIL_FOROTHERUSER_SMTP = PKG_MISC+179;
	@ErrorText(text="Four digit year is required for this field.")
	short ERR_MISC_4DIGIT_YEAR = (PKG_MISC+180);
	@ErrorText(text="MIME part truncated.")
	short ERR_MIME_PART_TRUNCATED = (PKG_MISC+181);
	@ErrorText(text="MIME stream has too many parts")
	short ERR_MISC_MIME_TOO_MANY_PARTS = (PKG_MISC+184);
	@ErrorText(text="CMemStr object cannot exceed 64K")
	short ERR_MISC_CMEMSTR_TOO_BIG = (PKG_MISC+185);
	@ErrorText(text="LtpaTokenFactory: class not initialized")
	short ERR_LTPA_NOT_INITED = (PKG_MISC+186);
	@ErrorText(text="Unexpected Single Sign-On error")
	short ERR_LTPA_INTERNAL_FAILURE = (PKG_MISC+187);
	@ErrorText(text="Single Sign-On token is invalid")
	short ERR_LTPA_TOKEN_INVALID = (PKG_MISC+188);
	@ErrorText(text="Single Sign-On token is expired")
	short ERR_LTPA_TOKEN_EXPIRED = (PKG_MISC+189);
	@ErrorText(text="Single Sign-On token contains an unknown WebSphere LDAP realm")
	short ERR_LTPA_WSREALM_INVALID = (PKG_MISC+190);
	@ErrorText(text="Single Sign-On configuration is invalid")
	short ERR_LTPA_NOT_CONFIGURED = (PKG_MISC+191);
	@ErrorText(text="IOR is already registered.")
	short ERR_IOR_ALREADY_EXIST = (PKG_MISC2+6);
	@ErrorText(text="IOR Table is full.")
	short ERR_IORTBL_FULL = (PKG_MISC2+7);
	@ErrorText(text="Debugger task not found on server.")
	short ERR_IOR_NOT_FOUND = (PKG_MISC2+8);
	@ErrorText(text="buffer to receive the requested IOR is too small.")
	short ERR_IOR_BUFFER_TOO_SMALL = (PKG_MISC2+9);
	@ErrorText(text="  %d statistics found%n%n")
	short ERR_STAT_COMPLETED = (PKG_MISC2+10);
	@ErrorText(text="Admin Process: Error signing hotspots in %p - (NoteID 0x%x)")
	short ERR_SIGNING_HOTSPOTS = (PKG_MISC2+13);
	@ErrorText(text="You have insufficient access to modify your ECL.")
	short ERR_ECL_NOACCESS = (PKG_MISC2+14);
	@ErrorText(text="ECL not found in cache.")
	short ERR_ECL_NOTINCACHE = (PKG_MISC2+15);
	@ErrorText(text="Alphabetic month required. ")
	short ERR_TDI_CONV_ALPHA_MONTH = (PKG_MISC2+21);
	@ErrorText(text="Hidden Task")
	short ERR_HIDDEN_TASK = (PKG_MISC2+22);
	@ErrorText(text="Cannot add role, maximum number of entries has been reached.")
	short ERR_TOO_MANY_ROLES = (PKG_MISC2+23);
	@ErrorText(text="Can't set breakpoint, program busy or ended.")
	short ERR_CANT_SET_BREAKPOshort = (PKG_MISC2+24);
	@ErrorText(text="%A %A copied acl from %A")
	short ERR_ACL_COPY = (PKG_MISC2+25);
	@ErrorText(text="The language specified for the user interface is not found in your Notes' MUI directory (it may have been uninstalled); proceeding with the default installed language.")
	short ERR_MUI_DIR_NOTFOUND = (PKG_MISC2+26);
	@ErrorText(text="MIME-CD Fatal error: note %08x, db %s, process %s (%04x:%04x)")
	short ERR_MC_EXCEPTION = (PKG_MISC2+29);
	@ErrorText(text="CD-MIME Fatal error: note %08x, db %s, process %s (%04x:%04x)")
	short ERR_CM_EXCEPTION = (PKG_MISC2+30);
	@ErrorText(text="MIME/CD converter exception -- no information available")
	short ERR_CNV_EXCEPTION_NO_INFO = (PKG_MISC2+31);
	@ErrorText(text="Invalid property specified")
	short ERR_INTL_INVALID_PROPERTY = (PKG_MISC3+1);
	@ErrorText(text="Invalid property value for this property")
	short ERR_INTL_INVALID_PROPERTY_VALUE = (PKG_MISC3+2);
	@ErrorText(text="Invalid buffer length to property value")
	short ERR_INTL_INVALID_PROPERTY_VALUE_LEN = (PKG_MISC3+3);
	@ErrorText(text="Name ambiguity (with user record %a) found during check of Internet email address.")
	short ERR_AUTH_NAME_LOOKUP_EMAIL = (PKG_MISC3+4);
	@ErrorText(text="Multiple Notes name matches found in directory")
	short ERR_AUTH_NAME_AMBIGUOUS_MATCH = (PKG_MISC3+5);
	@ErrorText(text="There are mismatched versions of program files running. Please correct this to avoid possible problems.")
	short ERR_MISMATCH_VERSION = (PKG_MISC3+6);
	@ErrorText(text="Could not hardware compress buffer.")
	short ERR_HWCFAILED = (PKG_MISC3+7);
	@ErrorText(text="Could not hardware expand buffer.")
	short ERR_HWEFAILED = (PKG_MISC3+8);
	@ErrorText(text="Could not obtain dictionary storage for hardware compression.")
	short ERR_HWCNOSTORAGE = (PKG_MISC3+9);
	@ErrorText(text="Transaction Logging hardware-assisted data compression is enabled.")
	short ERR_HWCACTIVE = (PKG_MISC3+10);
	@ErrorText(text="Feature '%s' is presently disabled by notes.ini setting: '%s'.")
	short ERR_FEATURE_DISABLED = (PKG_MISC3+11);
	@ErrorText(text="Unable to locate the Smart Upgrade database link on server %a")
	short ERR_SU_SEARCH_DB_LINK = (PKG_MISC3+12);
	@ErrorText(text="Unable to access notes.ini. Determine what application or hardware fault is preventing access. Previous cache values used.")
	short ERR_INI_FILE_UNAVAILABLE = (PKG_MISC3+13);
	@ErrorText(text="Events are being generated with a potentially non-unique PUID using this error (0x%x) '%s'")
	short ERR_DANGEROUS_PUID = (PKG_MISC3+14);
	@ErrorText(text="Error parsing Notes or LDAP Distinguished Name.")
	short ERR_DN_PARSE = (PKG_MISC3+15);
	@ErrorText(text="Buffer is already allocated.")
	short ERR_BUFFER_ALLOCATED = (PKG_MISC3+16);
	@ErrorText(text="Server %a has faulted and is now back up and running.")
	short ERR_RESTART_AFTER_FAULT = (PKG_MISC3+17);
	@ErrorText(text="Custom Error 0x%04x\n%s")
	short ERR_OVERRIDE_TEXT = (PKG_MISC3+18);
	@ErrorText(text="Query Views: duplicate NoteID.")
	short ERR_DB2_QV_DUP_NOTEID = (PKG_MISC3+19);
	@ErrorText(text="Query Views: row limit enforced.")
	short ERR_DB2_QV_MAX_ROWS = (PKG_MISC3+20);
	@ErrorText(text="Internet lockout view is invalid")
	short ERR_IL_VIEW_INVALID = (PKG_MISC3+21);
	@ErrorText(text="Internet password lockout function failed")
	short ERR_IL_FUNCFAILED = (PKG_MISC3+22);
	@ErrorText(text="Null ID Table handle passed as a parameter")
	short ERR_NULL_IDTABLE = (PKG_MISC3+27);
	@ErrorText(text="Unable to receive a message from the '%s' queue")
	short ERR_GENERIC_QUEUE_GET = (PKG_MISC3+28);
	@ErrorText(text="Unable to send a message to the '%s' queue")
	short ERR_GENERIC_QUEUE_PUT = (PKG_MISC3+29);
	@ErrorText(text="%s")
	short ERR_GENERIC_INTERNAL_DIAGNOSTIC = (PKG_MISC3+30);
	@ErrorText(text="Numeric string argument is too large for conversion")
	short ERR_OVERFLOW = (PKG_MISC3+31);
	@ErrorText(text="Unable to update calendar entry '%s' from list '%s' for '%a'.  Error returned: \n")
	short ERR_MAIL_POLICY_UPDATE_API_PROCESS_FAILURE = PKG_MISC_STR+47;
	@ErrorText(text="Unable to update calendar entry '%s' for '%a'.  Error returned: \n")
	short ERR_MAIL_POLICY_UPDATE_API_LOCKLIST_FAILURE = PKG_MISC_STR+48;
	@ErrorText(text="You cannot create a query view based on these styles :\n %s     or \n %s")
	short ERR_QUERYVIEW_INVALID_VIEWTYPE = (PKG_MISC_STR+57);
	@ErrorText(text="Single Sign-On token has a creation time in the future.  Single Sign-On servers may need to have clocks synchronized.")
	short ERR_LTPA_TOKEN_FUTURE_TIME = (PKG_MISC_STR+61);
	@ErrorText(text="The Policy Setting document has been deleted.  No policy settings will be pushed down.  Please notify your administrator.")
	short ERR_POLICY_DOC_DELETED = (PKG_MISC_STR+62);
	@ErrorText(text="The sort function has exceeded the allotted stack recursion limit. The sort did not complete.")
	short ERR_SORT_STACK_OVERFLOW = (PKG_MISC_STR+63);
	@ErrorText(text="Rebuilding DbDir Index due to error: %e")
	short ERR_DBDIR_INDEX_REBUILD = PKG_MISC_STR+64;
	@ErrorText(text="Temporary .DTF file not found and may have been deleted.")
	short ERR_TMP_FILE_ERROR = PKG_MISC_STR+65;
	@ErrorText(text="The Single Sign-On token type does not match the configuration.")
	short ERR_LTPA_TOKENTYPE_CONFIG_ISSUE = (PKG_MISC_STR+68);
	@ErrorText(text="Single Sign-On is not configured for the server.")
	short ERR_SSO_SERVERCONFIG_ISSUE = (PKG_MISC_STR+69);
	@ErrorText(text="Unable to delete policy control item %s from calendar profile for '%a' in mailfile '%p'.  Error Returned: \n")
	short ERR_MAIL_POLICY_DELITEM_FAILURE = (PKG_MISC_STR+70);
	@ErrorText(text="Successfully removed all policy control items from the calendar profile for '%a' in mailfile %p")
	short ERR_MAIL_POLICY_SUCCESSFUL_REMOVAL = (PKG_MISC_STR+71);
	@ErrorText(text="Unable to update %s entry '%s' for '%a'.  Error returned: \n")
	short ERR_POLICY_UPDATE_API_LOCKLIST_FAILURE = PKG_MISC_STR+74;
	@ErrorText(text="Identity cannot be verified:  Windows account is locked. If you need help to unlock the Windows account, contact your Windows administrator.")
	short ERR_WIN_LOCKED_OUT = (PKG_MISC_STR+75);
	@ErrorText(text="An error occurred during the backup of files during roaming enablement.   Please reboot and try launching Notes again to continue with roaming enablement")
	short ERR_MISC_ROAMING_UPGRADE_RENAME_FAILED = (PKG_MISC_STR+77);
	@ErrorText(text="Prefix list version not supported")
	short ERR_PREFIX_VER_NOT_SUPPORTED = (PKG_MISC_STR+80);
	@ErrorText(text="Prefix list signature invalid")
	short ERR_PREFIX_SIGNATURE = (PKG_MISC_STR+81);
	@ErrorText(text="Prefix list time invalid")
	short ERR_PREFIX_TIME = (PKG_MISC_STR+82);
	@ErrorText(text="NSD either failed to run or passed its number of times run limit")
	short ERR_NSD_NOT_RUN = (PKG_MISC_STR+84);
	@ErrorText(text="You are not the intended recipient of the exported Encryption Key")
	short ERR_MISC_NOT_NEK_RECIPIENT = (PKG_MISC_STR+100);
	@ErrorText(text="The IDP URL was not correctly formed")
	short ERR_MISC_NFL_BAD_IDP_URL = (PKG_MISC_STR+109);
	@ErrorText(text="Mail body item is not found in this native MIME mail Note.")
	short ERR_BODY_ITEM_NOT_FOUND = PKG_DB2_STR+112;
	@ErrorText(text="Unexpected parsing RFC2231 header error")
	short ERR_MISC_UNEXPECTED_RFC2231_ERROR = PKG_MISC_STR+115;

}
