package com.mindoo.domino.jna.errors.errortexts;

public interface INetErr extends IGlobalErr {

	@ErrorText(text="Insufficient network or adapter resources.  Consult Network documentation to increase the maximum number of sessions.")
	short ERR_NO_MORE_SESSIONS = PKG_NETWORK+1;
	@ErrorText(text="Remote system no longer responding")
	short ERR_SESSION_CLOSED = PKG_NETWORK+2;
	@ErrorText(text="Another system is using the same server name as this system")
	short ERR_NAME_IN_USE = PKG_NETWORK+3;
	@ErrorText(text="Network error due to transient network condition or hardware failure")
	short ERR_NET_FLAKY = PKG_NETWORK+4;
	@ErrorText(text="Network adapter not installed or not functioning")
	short ERR_NET_HARDWARE = PKG_NETWORK+5;
	@ErrorText(text="Internal network software problem (or hardware malfunction)")
	short ERR_NET_SOFTWARE = PKG_NETWORK+6;
	@ErrorText(text="Network operation did not complete in a reasonable amount of time; please retry")
	short ERR_TIMEOUT = PKG_NETWORK+7;
	@ErrorText(text="Network operation was cancelled")
	short ERR_NET_CMD_CANCELLED = PKG_NETWORK+8;
	@ErrorText(text="(Retry command)")
	short ERR_RETRY = PKG_NETWORK+9;
	@ErrorText(text="Remote system not responding")
	short ERR_NOT_RESPONDING = PKG_NETWORK+10;
	@ErrorText(text="Network name already in use on this system")
	short ERR_NAME_IN_USE_HERE = PKG_NETWORK+11;
	@ErrorText(text="Network error: insufficient data received")
	short ERR_INSUF_RCVD_DATA = PKG_NETWORK+12;
	@ErrorText(text="Network error: message has incorrect sequence number")
	short ERR_SEQUENCE_NUMBER = PKG_NETWORK+13;
	@ErrorText(text="(Network error: buffer was too small)")
	short ERR_BFR_TOO_SMALL = PKG_NETWORK+14;
	@ErrorText(text="NETBIOS not loaded or not running")
	short ERR_NO_NETBIOS = PKG_NETWORK+15;
	@ErrorText(text="Specified port(s) currently in use")
	short ERR_WRONG_SERVER = PKG_NETWORK+16;
	@ErrorText(text="Disconnected from Server")
	short ERR_DISCONNECTED = PKG_NETWORK+17;
	@ErrorText(text="Network Session Table is full. Increase maximum number of sessions with MAX_NETWORK_SESSIONS Notes.INI")
	short ERR_SESSION_TABLE_FULL = PKG_NETWORK+18;
	@ErrorText(text="(Port successfully terminated)")
	short ERR_TERMINATED = PKG_NETWORK+19;
	@ErrorText(text="Port not ready or carrier not established")
	short ERR_WRONG_STATE = PKG_NETWORK+20;
	@ErrorText(text="Remote phone was busy")
	short ERR_REMOTE_BUSY = PKG_NETWORK+21;
	@ErrorText(text="Remote phone did not answer")
	short ERR_NO_ANSWER = PKG_NETWORK+22;
	@ErrorText(text="Remote phone did not answer or modem could not detect carrier")
	short ERR_NO_CARRIER = PKG_NETWORK+23;
	@ErrorText(text="Modem could not detect dial tone")
	short ERR_NO_DIALTONE = PKG_NETWORK+24;
	@ErrorText(text="Invalid port initialization argument list")
	short ERR_BADPORT_ARGS = PKG_NETWORK+25;
	@ErrorText(text="Received unrecognizable response from modem")
	short ERR_MODEM_RESPONSE = PKG_NETWORK+26;
	@ErrorText(text="Modem does not respond")
	short ERR_MODEM_NORESP = PKG_NETWORK+27;
	@ErrorText(text="Could not establish dialog with remote system")
	short ERR_HANDSHAKE = PKG_NETWORK+28;
	@ErrorText(text="Session is not yet opened")
	short ERR_SESS_NOT_READY = PKG_NETWORK+29;
	@ErrorText(text="Communications port hardware not present or in use by another device.")
	short ERR_NO_SUCH_UNIT = PKG_NETWORK+30;
	@ErrorText(text="Device or unit number already in use")
	short ERR_DEVICE_IN_USE = PKG_NETWORK+31;
	@ErrorText(text="Driver already in use")
	short ERR_DRIVER_IN_USE = PKG_NETWORK+32;
	@ErrorText(text="Driver could not allocate memory for communications buffers")
	short ERR_NO_RING_BUFFER = PKG_NETWORK+33;
	@ErrorText(text="Unable to allocate network buffer(s)")
	short ERR_NO_BUFFERS = PKG_NETWORK+34;
	@ErrorText(text="Invalid driver initialization parameters")
	short ERR_BADDEV_PARAMS = PKG_NETWORK+35;
	@ErrorText(text="Unrecognized response from system request")
	short ERR_BAD_RESPONSE = PKG_NETWORK+36;
	@ErrorText(text="Notes Port Driver unavailable")
	short ERR_NO_SUCH_PORT = PKG_NETWORK+37;
	@ErrorText(text="No such session or session has been closed")
	short ERR_NO_SUCH_SESSION = PKG_NETWORK+38;
	@ErrorText(text="Other servers are not known by this system")
	short ERR_SERVERS_UNKNOWN = PKG_NETWORK+39;
	@ErrorText(text="A port with that name already exists")
	short ERR_DUPL_PORTNAME = PKG_NETWORK+40;
	@ErrorText(text="Message queue is empty")
	short ERR_MSGQUEUE_EMPTY = PKG_NETWORK+41;
	@ErrorText(text="Structure is not a message queue head")
	short ERR_NOT_QUEUE = PKG_NETWORK+42;
	@ErrorText(text="Not enough parameters specified in NOTES.INI to initialize port driver")
	short ERR_INSUFF_ARGS = PKG_NETWORK+43;
	@ErrorText(text="Insufficient network or adapter resources.  Consult Network documentation to increase those resources.")
	short ERR_INSUFF_ADAP_RES = PKG_NETWORK+44;
	@ErrorText(text="Function not implemented on this port")
	short ERR_NO_PORT_FUNC = PKG_NETWORK+45;
	@ErrorText(text="no progress in time allotted (but i/o still active)")
	short ERR_NO_PROGRESS = PKG_NETWORK+46;
	@ErrorText(text="Network package has not been initialized")
	short ERR_NET_NOT_INIT = PKG_NETWORK+48;
	@ErrorText(text="Yield, then call back with same NETBFR")
	short ERR_NETBFR_YIELD = PKG_NETWORK+49;
	@ErrorText(text="Use NETBFR to issue a receive")
	short ERR_NETBFR_ISSUERCV = PKG_NETWORK+50;
	@ErrorText(text="Use NETBFR to issue a transmit")
	short ERR_NETBFR_ISSUEXMT = PKG_NETWORK+51;
	@ErrorText(text="Yield, then call back with same NETBFR quickly")
	short ERR_NETBFR_PTYIELD = PKG_NETWORK+52;
	@ErrorText(text="Address Book database contains no Connection document for that server")
	short ERR_NO_SERVER_INFO = PKG_NETWORK+54;
	@ErrorText(text="No ports specified in connection document found in the Address Book (to reach the server) are configured on this system")
	short ERR_NO_PORT_FROM_DB = PKG_NETWORK+55;
	@ErrorText(text="Site is unknown")
	short ERR_NO_SUCH_SITE = PKG_NETWORK+56;
	@ErrorText(text="Mail probe to %s has failed due to error")
	short ERR_MAIL_PROBE_FAILED = PKG_NETWORK+57;
	@ErrorText(text="Connections database has no information for that application")
	short ERR_UNKNOWN_APPL = PKG_NETWORK+58;
	@ErrorText(text="Connections database contains too many different applications")
	short ERR_TOO_MANY_APPLS = PKG_NETWORK+59;
	@ErrorText(text="The LANMAN process limit has been exceeded.  This cannot be increased.  Reduce usage by limiting clients (see SERVER_MAXSESSIONS parameter in Notes Admin Guide).")
	short ERR_LANMAN_PROC_LIMIT = PKG_NETWORK+60;
	@ErrorText(text="Continue operation.")
	short ERR_NET_CONTINUE = PKG_NETWORK+61;
	@ErrorText(text="Mail probe to %s has timed out.")
	short ERR_MAIL_PROBE_TIMEDOUT = PKG_NETWORK+62;
	@ErrorText(text="Link notification table is full")
	short ERR_LINK_TABLE_FULL = PKG_NETWORK+63;
	@ErrorText(text="The network port driver is an incompatible version")
	short ERR_NET_PORT_VERSION = PKG_NETWORK+64;
	@ErrorText(text="Name & Address Book contains a Connection entry with no schedule information")
	short ERR_NO_SCHED_INFO = PKG_NETWORK+65;
	@ErrorText(text="Mail probe to %s was successful")
	short ERR_MAIL_PROBE_SUCCESS = PKG_NETWORK+66;
	@ErrorText(text="Modem lost carrier")
	short ERR_NET_CARRIER_DOWN = PKG_NETWORK+67;
	@ErrorText(text=" bits per second connection established")
	short ERR_NET_CARRIER_UP = PKG_NETWORK+68;
	@ErrorText(text="Some changes may require a restart to take effect")
	short ERR_NET_PORT_REINIT = PKG_NETWORK+69;
	@ErrorText(text="Make call to server ")
	short ERR_DIAL_QUERY1 = PKG_NETWORK+70;
	@ErrorText(text=" on port ")
	short ERR_DIAL_QUERY2 = PKG_NETWORK+71;
	@ErrorText(text="?")
	short ERR_DIAL_QUERY3 = PKG_NETWORK+72;
	@ErrorText(text="Remote computer is not currently accessible")
	short ERR_DIAL_QUERY_NO = PKG_NETWORK+73;
	@ErrorText(text="Could not detect carrier or dialtone; or phone was busy or did not answer")
	short ERR_1200_DIAL_ERROR = PKG_NETWORK+74;
	@ErrorText(text="Modem reported command error.  Check: (1) That the command file selected is correct; (2) If editing a command file, that all commands conform to modem vendor documentation of supported AT commands.")
	short ERR_MODEM_BADCMD = PKG_NETWORK+75;
	@ErrorText(text="String resource not provided")
	short ERR_STRING_RESOURCE = PKG_NETWORK+76;
	@ErrorText(text="Clearing modem's DTR")
	short ERR_NET_CLEARING_DTR = PKG_NETWORK+77;
	@ErrorText(text="Error encountered while answering an incoming call")
	short ERR_NET_ANSWERING_PHONE = PKG_NETWORK+78;
	@ErrorText(text="No such task known")
	short ERR_NO_SUCH_TASK = PKG_NETWORK+79;
	@ErrorText(text="Call Timer expired")
	short ERR_DIAL_TIMER_EXPIRED = PKG_NETWORK+80;
	@ErrorText(text="Unknown LAN Manager error")
	short ERR_UNKNOWN_LANMAN = PKG_NETWORK+81;
	@ErrorText(text="Network not started")
	short ERR_NET_NOT_STARTED = PKG_NETWORK+82;
	@ErrorText(text="Internal error in network operating system")
	short ERR_INTERNAL_LANMAN = PKG_NETWORK+83;
	@ErrorText(text="Invalid network driver or semaphore handle")
	short ERR_DRIVER_HANDLE = PKG_NETWORK+84;
	@ErrorText(text="NETBIOS unit/lana number specified in NOTES.INI is not valid on this system, or a network is not started")
	short ERR_BAD_UNIT_NUM = PKG_NETWORK+85;
	@ErrorText(text="Insufficient operating system resources")
	short ERR_INSUFF_OS_RES = PKG_NETWORK+86;
	@ErrorText(text="Probe of %s port on %s has timed out")
	short ERR_ISPY_PROBE_TIMEDOUT = PKG_NETWORK+87;
	@ErrorText(text="Network adapter too busy to handle request")
	short ERR_ADAP_BUSY = PKG_NETWORK+88;
	@ErrorText(text="Unable to open log file")
	short ERR_NOLOGFILE = PKG_NETWORK+89;
	@ErrorText(text="Network driver has not been initialized")
	short ERR_DRIVER_NOT_INIT = PKG_NETWORK+90;
	@ErrorText(text="LogEntry out of range")
	short ERR_LOGENTRY_INVALID = PKG_NETWORK+91;
	@ErrorText(text="LogEntry not allocated")
	short ERR_LOG_NULLHANDLE = PKG_NETWORK+92;
	@ErrorText(text="The DDM names have not been modified since the time specified")
	short ERR_NO_DDM_NAMES_MOD = PKG_NETWORK+93;
	@ErrorText(text="(No item name)")
	short ERR_NO_ITEM_NAME = PKG_NETWORK+94;
	@ErrorText(text=" via Network Dialup using connection info ")
	short ERR_DIAL_QUERY2_REMOTE_LAN = PKG_NETWORK+95;
	@ErrorText(text="Network adapter not working; check cable")
	short ERR_ADAP_CABLE = PKG_NETWORK+96;
	@ErrorText(text="Network name cannot be used")
	short ERR_ADAP_NAME_TABLE = PKG_NETWORK+97;
	@ErrorText(text="Additional ports may not be enabled while the server is running")
	short ERR_CANT_ENABLE_PORTS = PKG_NETWORK+98;
	@ErrorText(text="Illegal or unrecognized request code")
	short ERR_ILL_REQ_CODE = PKG_NETWORK+99;
	@ErrorText(text="")
	short ERR_SCHEDULE_RELOADED = PKG_NETWORK+100;
	@ErrorText(text="-_ ")
	short ERR_PORT_NAME_CHARS = PKG_NETWORK+101;
	@ErrorText(text="The only allowed characters for a port name are letters, numbers, hyphen, and underscore")
	short ERR_INVALID_NET_PORT_NAME = PKG_NETWORK+102;
	@ErrorText(text="Request failed because the requested port is inactive")
	short ERR_INACTIVE_PORT = PKG_NETWORK+103;
	@ErrorText(text="The data in a buffer was too small or was corrupted (file %s, line %d)")
	short ERR_BAD_BUFFER = PKG_NETWORK+104;
	@ErrorText(text="Bad buffer - please report this error.  See log.nsf for more info.")
	short ERR_BAD_BUFFER_POST_MSG = PKG_NETWORK+105;
	@ErrorText(text="The port specified is currently disabled")
	short ERR_PORT_DISABLED = PKG_NETWORK+107;
	@ErrorText(text="Mail probe to %s was successful, but slow")
	short ERR_MAIL_PROBE_SLOW = PKG_NETWORK+108;
	@ErrorText(text="This function is only available when used on a Domino Server")
	short ERR_SERVER_ONLY = PKG_NETWORK+121;
	@ErrorText(text="Insufficient memory - NetBfr Pool is full.")
	short ERR_NETBFR_POOLFULL = PKG_NETWORK+129;
	@ErrorText(text="Asynchronous notification message too large")
	short ERR_ANQ_SIZE = PKG_NETWORK+135;
	@ErrorText(text="Insufficient memory - Group Cache Pool is full.")
	short ERR_NET_GROUP_POOLFULL = PKG_NETWORK+137;
	@ErrorText(text="Insufficient memory - Scheduling Database Pool is full.")
	short ERR_NET_SCHEDULE_POOLFULL = PKG_NETWORK+138;
	@ErrorText(text="Insufficient memory - Job Scheduling Pool is full.")
	short ERR_NET_JS_POOLFULL = PKG_NETWORK+139;
	@ErrorText(text="Insufficient memory - Network Pool is full.")
	short ERR_NET_POOLFULL = PKG_NETWORK+140;
	@ErrorText(text="Insufficient memory - Network Task Pool is full.")
	short ERR_TASK_POOLFULL = PKG_NETWORK+141;
	@ErrorText(text="Insufficient memory - Session Pool is full.")
	short ERR_SESSION_POOLFULL = PKG_NETWORK+142;
	@ErrorText(text="Maximum number of in-memory log entries exceeded; cannot create another until some are flushed to the log database")
	short ERR_LOG_QUOTA_EXCEEDED = PKG_NETWORK+143;
	@ErrorText(text="Probe of %s port%s on %s has completed")
	short ERR_ISPY_PROBE_COMPLETED = PKG_NETWORK+169;
	@ErrorText(text="Program shutdown in progress")
	short ERR_QUIT = PKG_NETWORK+197;
	@ErrorText(text="The specified network service type or name is not appropriate for this request")
	short ERR_ILL_SVCTYPE = PKG_NETWORK+225;
	@ErrorText(text="Error opening modem command file")
	short ERR_OPEN_MDMSCRIPT = PKG_NETWORK+226;
	@ErrorText(text="The server that answered does not have the expected name")
	short ERR_WRONG_SERVERNAME = PKG_NETWORK+227;
	@ErrorText(text="Queue is full")
	short ERR_EXCEED_QUOTA = PKG_NETWORK+228;
	@ErrorText(text="Call timer expired")
	short ERR_DIALTIMER_EXPIRED = PKG_NETWORK+229;
	@ErrorText(text="Cannot locate required login information")
	short ERR_LOGIN_INIT = PKG_NETWORK+230;
	@ErrorText(text="Initializing...")
	short ERR_NET_MODEM_INIT = PKG_NETWORK+231;
	@ErrorText(text="Calling %a at %s...")
	short ERR_NET_MODEM_DIALING = PKG_NETWORK+232;
	@ErrorText(text="Unable to load Network Dialup %s adapter (%e). Check that the %s dialer is installed on this system")
	short STR_RLAN_CANT_LOAD = PKG_NETWORK+233;
	@ErrorText(text="Mail probe configuration does not specify a recipient")
	short ERR_MAIL_PROBE_NO_RECIPIENT = PKG_NETWORK+234;
	@ErrorText(text="INet Task table is full")
	short ERR_INETTASK_TABLEFULL = PKG_NETWORK+235;
	@ErrorText(text="AsyncIO Request outstanding")
	short ERR_NETIO_PENDING = PKG_NETWORK+236;
	@ErrorText(text="Insufficient memory - INetTask Pool")
	short ERR_INETTASK_POOLFULL = PKG_NETWORK+237;
	@ErrorText(text="Doesn't match originating Connection Document")
	short ERR_NON_PREFERRED_CONNREC = PKG_NETWORK+238;
	@ErrorText(text="Async Status Event Posted")
	short ERR_NETIO_EVENT = PKG_NETWORK+239;
	@ErrorText(text="Connection document has blank Network Dialup Service Name")
	short ERR_REMOTE_LAN_NO_SVC_NAME = PKG_NETWORK+240;
	@ErrorText(text="This Network Dialup operation is not supported")
	short ERR_REMOTE_LAN_NOT_SUPPORTED = PKG_NETWORK+249;
	@ErrorText(text="Dial-up Networking is not installed on this system.")
	short ERR_REMOTE_LAN_NOT_INSTALLED = PKG_NETWORK+250;
	@ErrorText(text="Log Purge Task is active|Log Purge Task is idle")
	short ERR_TASK_DESC_LOGPURGE = (PKG_NETWORK2+2);
	@ErrorText(text="Probe of WebSphere Services for %s %s on %s, has timed out")
	short ERR_ISPY_PROBE_WEBSPHERE_TIMEOUT = PKG_NETWORK2+9;
	@ErrorText(text="Network Dialup service is not available")
	short ERR_REMOTE_LAN_SERVICE_NOT_AVAIL = PKG_NETWORK2+21;
	@ErrorText(text="Error initializing Network Dialup service")
	short ERR_REMOTE_LAN_SERVICE_INITIALIZATION = PKG_NETWORK2+22;
	@ErrorText(text="%s Error %d: %s")
	short ERR_REMOTE_LAN_KNOWN_ERROR = PKG_NETWORK2+23;
	@ErrorText(text="Unknown %s error %d")
	short ERR_REMOTE_LAN_UNKNOWN_ERROR = PKG_NETWORK2+24;
	@ErrorText(text="Error returned from remote access dialer. See Notes log on this system for additional information")
	short ERR_REMOTE_LAN_ERROR = PKG_NETWORK2+25;
	@ErrorText(text="Calling remote LAN")
	short ERR_REMOTE_LAN_STARTING_CONNECTION = PKG_NETWORK2+26;
	@ErrorText(text="Connected to remote LAN")
	short ERR_REMOTE_LAN_PHYSICALLY_CONNECTED = PKG_NETWORK2+27;
	@ErrorText(text="Authenticating with remote LAN")
	short ERR_REMOTE_LAN_AUTHENTICATING = PKG_NETWORK2+28;
	@ErrorText(text="Authenticated")
	short ERR_REMOTE_LAN_AUTHENTICATED = PKG_NETWORK2+29;
	@ErrorText(text="Waiting for call back")
	short ERR_REMOTE_LAN_WAITING_FOR_CALLBACK = PKG_NETWORK2+30;
	@ErrorText(text="Network Dialup link established")
	short ERR_REMOTE_LAN_LINK_ESTABLISHED = PKG_NETWORK2+31;
	@ErrorText(text="Network Dialup link failed")
	short ERR_REMOTE_LAN_LINK_FAILED = PKG_NETWORK2+32;
	@ErrorText(text="We are already connected to that remote LAN")
	short ERR_REMOTE_LAN_ALREADY_CONNECTED = PKG_NETWORK2+33;
	@ErrorText(text="Unable to find path to pass-through server")
	short ERR_CANT_FIND_PT_SERVER = PKG_NETWORK2+64;
	@ErrorText(text="A previous attempt to reach the server was unsuccessful.")
	short ERR_CONNECT_FAILED_EARLIER = PKG_NETWORK2+71;
	@ErrorText(text="Unable to open Name and Address Book (%s), due to error '%e'.  Locations cannot be used until the problem has been corrected.")
	short ERR_NOLOC_NABOOKNOTFOUND = PKG_NETWORK2+75;
	@ErrorText(text="Unable to create any locations, '%s' does not contain a required view.  Please replace the design with the Address book template.  After the design is replaced, restarting Notes will create default locations.")
	short ERR_NOLOC_NABOOKBADDESIGN = PKG_NETWORK2+76;
	@ErrorText(text="Unable to create locations due to error '%e'.  Locations cannot be used until the problem has been corrected.")
	short ERR_NOLOC_OTHERERROR = PKG_NETWORK2+77;
	@ErrorText(text="Terminating Network Dialup link")
	short ERR_REMOTE_LAN_HANGING_UP = PKG_NETWORK2+79;
	@ErrorText(text="Network Dialup link terminated")
	short ERR_REMOTE_LAN_HANGUP_COMPLETE = PKG_NETWORK2+80;
	@ErrorText(text="ports may not be disabled while the server is running")
	short ERR_CANT_DISABLE_PORTS = PKG_NETWORK2+81;
	@ErrorText(text="Unable to connect to server because user hung up the phone line.")
	short ERR_CONNECT_DISALLOWED = PKG_NETWORK2+83;
	@ErrorText(text="Probe of WebSphere Services: Application %s is stopped on %s.")
	short ERR_ISPY_PROBE_WEBSPHERE_APP_STOPPED = PKG_NETWORK2+84;
	@ErrorText(text="Log note has exceeded size limits.")
	short ERR_LOG_NOTE_LIMIT = PKG_NETWORK2+85;
	@ErrorText(text="Server name format is not recognized by protocol")
	short ERR_NAME_FORMAT_NOT_RECOGNIZED = PKG_NETWORK2+98;
	@ErrorText(text="A $$LDAPAccessGroups-returned group already appears in the names list")
	short ERR_LDAPACCESSGROUPS_CONFLICT = (PKG_NETWORK2+99);
	@ErrorText(text="No profiles for user %a")
	short ERR_NET_NO_PROFILES = PKG_NETWORK2+103;
	@ErrorText(text="A previous attempt to reach this remote access server was unsuccessful.")
	short ERR_RLAN_CONNECT_FAILED_EARLIER = PKG_NETWORK2+104;
	@ErrorText(text="All Com ports are in use.")
	short ERR_COM_PORTS_IN_USE = PKG_NETWORK2+105;
	@ErrorText(text="A connection record has been created for %A.")
	short ERR_CREATECONNREC_DONE = PKG_NETWORK2+106;
	@ErrorText(text="Make call to ")
	short ERR_DIAL_QUERY1_ALT = PKG_NETWORK2+107;
	@ErrorText(text="DNS resolver error")
	short ERR_NET_RESOLVER = PKG_NETWORK2+115;
	@ErrorText(text="Unknown host")
	short ERR_NET_RES_HOST_NOT_FOUND = PKG_NETWORK2+116;
	@ErrorText(text="Host name lookup failure")
	short ERR_NET_RES_TRY_AGAIN = PKG_NETWORK2+117;
	@ErrorText(text="Unknown server error")
	short ERR_NET_RES_NO_RECOVERY = PKG_NETWORK2+118;
	@ErrorText(text="No address associated with name")
	short ERR_NET_RES_NO_ADDRESS = PKG_NETWORK2+119;
	@ErrorText(text="Network Dialup service not responding.  Please restart system or re-install service.")
	short ERR_REMOTE_LAN_NORESPONSE = PKG_NETWORK2+120;
	@ErrorText(text="The connection attempt has failed. The modems did not connect properly. Please try again.")
	short ERR_REMOTE_LAN_CONNECT_FAILED = PKG_NETWORK2+121;
	@ErrorText(text="Network Dialup link was dropped outside of Notes")
	short ERR_REMOTE_LAN_LINK_DROPPED = PKG_NETWORK2+122;
	@ErrorText(text="Insufficient memory - Location Pool is full.")
	short ERR_LOC_POOLFULL = PKG_NETWORK2+123;
	@ErrorText(text="There is no incoming Internet mail server specified for this location.")
	short ERR_LOC_INC_SERVER_ERROR = (PKG_NETWORK2+125);
	@ErrorText(text="There is no SMTP account specified for this location.")
	short ERR_LOC_OUT_SERVER_ERROR = (PKG_NETWORK2+126);
	@ErrorText(text="Error creating remote address pool. Memory probably full.")
	short ERR_RA_CREATE_POOL = (PKG_NETWORK2+127);
	@ErrorText(text="Organization structures have not been initialized")
	short ERR_ORGNAME_NOT_INITIALIZED = (PKG_NETWORK3+3)					;
	@ErrorText(text="Multiple Organizations in Internet Site documents with the same IP address")
	short ERR_ADDRESS_CONFLICT = (PKG_NETWORK3+4);
	@ErrorText(text="Reached the maximum size allowed for an activity note")
	short ERR_ACTIVITY_MAX_NOTE_SIZE = (PKG_NETWORK3+23);
	@ErrorText(text="Activity item type does not match schema")
	short ERR_ACTIVITY_ITEM_TYPE_MISMATCH = (PKG_NETWORK3+25);
	@ErrorText(text="Invalid activity type. See Notes API reference for details.")
	short ERR_ACTIVITY_INVALID_TYPE = (PKG_NETWORK3+26);
	@ErrorText(text="Array List Hashtable (ALHT) BPool Full")
	short ERR_ALHT_BPOOL_FULL = (PKG_NETWORK3+27);
	@ErrorText(text="Record name length exceeded maximum of 128 characters")
	short ERR_ACTIVITY_RECORDNAME_TRUNCATED = (PKG_NETWORK3+28);
	@ErrorText(text="Exceeded the maximum of 254 activity record definitions")
	short ERR_ACTIVITY_RECORDDESC_MAX = (PKG_NETWORK3+29);
	@ErrorText(text="Unknown Activity item definition encountered.")
	short ERR_ACTIVITY_ITEMDEF_UNKNOWN = (PKG_NETWORK3+30);
	@ErrorText(text="Activity record descriptor not defined in activity schema")
	short ERR_ACTIVITY_UNKNOWN_RECORDDESC = (PKG_NETWORK3+31);
	@ErrorText(text="Description index found in activity record is not defined in activity schema")
	short ERR_ACTIVITY_INVALID_DESC_IDX = (PKG_NETWORK4+1);
	@ErrorText(text="Item name is invalid. Must be less than 32 characters in length and must start with a letter")
	short ERR_ACTIVITY_INVALID_ITEM_NAME = (PKG_NETWORK4+2);
	@ErrorText(text="Unable to write activity data")
	short ERR_ACTIVITY_WRITE_FAILED = (PKG_NETWORK4+3);
	@ErrorText(text="Item type is incorrect for activity data")
	short ERR_ACTIVITY_INVALID_ITEM_TYPE = (PKG_NETWORK4+4);
	@ErrorText(text="Unable to load Organization Name: IP Addr: %s")
	short ERR_ORGNAME_BADIPADDR = (PKG_NETWORK4+5);
	@ErrorText(text="Lookup of IP address for host %s failed")
	short ERR_DNS_LOOKUP_ERROR = (PKG_NETWORK4+6);
	@ErrorText(text="Unable to add IP Address: %s, Subnet Mask: %s to loopback adapter")
	short ERR_LOOPBACK_OVERFLOW = (PKG_NETWORK4+10);
	@ErrorText(text="Activity log data was created by a different version of Notes")
	short ERR_ACTIVITY_WRONG_VERSION = (PKG_NETWORK4+11);
	@ErrorText(text="No primary key specified for a checkpointed record")
	short ERR_ACTIVITY_PRIKEY_MISSING = (PKG_NETWORK4+12);
	@ErrorText(text="Log database does not contain a required view. Please update the design with the latest template")
	short ERR_ACTIVITY_LOG_TEMPLATE = (PKG_NETWORK4+13);
	@ErrorText(text="Activity log buffer is corrupt")
	short ERR_ACTVITIY_BUFFER_CORRUPT = (PKG_NETWORK5+0);
	@ErrorText(text="Activity record is corrupt")
	short ERR_ACTIVITY_RECORD_CORRUPT = (PKG_NETWORK5+1);
	@ErrorText(text="Found bad activity data at note ID %x, Stream position %u:")
	short ERR_ACTIVITY_BAD_RECORD = (PKG_NETWORK5+2);
	@ErrorText(text="Done enumerating activity data")
	short ERR_ACTIVITY_ENUM_COMPLETE = (PKG_NETWORK5+3);
	@ErrorText(text="Duplicate AsyncIO request outstanding")
	short ERR_NETIO_OUTSTANDING = PKG_NETWORK5+4;
	@ErrorText(text="Attempted to read past end of activity stream")
	short ERR_ACTIVITY_END_OF_STREAM = (PKG_NETWORK5+5);
	@ErrorText(text="Skipping activity data note ID %x:")
	short ERR_ACTIVITY_SKIPPING_NOTE = (PKG_NETWORK5+6);
	@ErrorText(text="Organization Name Cache Refresher is idle")
	short ERR_TASK_DESC_ORGNAME_IDLE = (PKG_NETWORK5+7);
	@ErrorText(text="Organization Name Cache Refresher is checking cache")
	short ERR_TASK_DESC_ORGNAME = (PKG_NETWORK5+8);
	@ErrorText(text="Failed to create an IOCP port")
	short ERR_IOCP_CREATE = (PKG_NETWORK5+9);
	@ErrorText(text="Failed to associate an IOCP port")
	short ERR_IOCP_ASSOCIATE = (PKG_NETWORK5+10);
	@ErrorText(text="Failed to post a user event to an IOCP port")
	short ERR_IOCP_POST = (PKG_NETWORK5+11);
	@ErrorText(text="Add IP address to Internet Site cache: %s")
	short ERR_ORGIP_ADDED_TO_CACHE = (PKG_NETWORK5+12);
	@ErrorText(text="Purge IP address from Internet Site cache: %s ")
	short ERR_ORGIP_PURGE_FROM_CACHE = (PKG_NETWORK5+13);
	@ErrorText(text="Asynchronous Network IO event is not complete")
	short ERR_NETIO_COMPLETE = PKG_NETWORK5+17;
	@ErrorText(text="Mail probe to %s has failed. %s")
	short ERR_MAIL_PROBE_FAILURE = PKG_NETWORK5+31;

}
