package com.mindoo.domino.jna.errors.errortexts;

public interface IRegErr extends IGlobalErr {

	@ErrorText(text="Insufficient information supplied for requested registration function.")
	short ERR_REG_INC_CONTEXT = PKG_REG + 1;
	@ErrorText(text="Unable to update existing document in your Domino Directory")
	short ERR_REG_ADDRBOOK_ENTRY_EXISTS = PKG_REG + 2;
	@ErrorText(text="Unable to modify existing User ID file")
	short ERR_REG_USERID_EXISTS = PKG_REG + 3;
	@ErrorText(text="A Domino Directory entry for %A already exists.")
	short ERR_REG_LOG_ADDRBOOK_EXISTS = PKG_REG + 10;
	@ErrorText(text="The name cannot be registered.  More than one entry was found in the Domino Directory with this name")
	short ERR_REG_TOO_MANY_ENTRIES = PKG_REG + 14;
	@ErrorText(text="No ID file name specified")
	short ERR_REG_NO_IDFILE_NAME = PKG_REG + 16;
	@ErrorText(text="No mail server or mail database name specified")
	short ERR_REG_NO_MAIL_INFO = PKG_REG + 17;
	@ErrorText(text="No last name specified")
	short ERR_REG_NO_LASTNAME = PKG_REG + 18;
	@ErrorText(text="No server name specified")
	short ERR_REG_NO_SERVER_NAME = PKG_REG + 19;
	@ErrorText(text="No certifier specified")
	short ERR_REG_NO_CERTIFIER = PKG_REG + 20;
	@ErrorText(text="No password specified")
	short ERR_REG_NO_PASSWORD = PKG_REG + 21;
	@ErrorText(text="Could not open the certifier log")
	short ERR_REG_OPEN_CERTLOG = PKG_REG + 22;
	@ErrorText(text="You are not allowed to update the certifier log")
	short ERR_REG_ACCESS_CERTLOG = PKG_REG + 23;
	@ErrorText(text="Error attempting to update the certifier log")
	short ERR_REG_UPDATE_CERTLOG = PKG_REG + 24;
	@ErrorText(text="User or server name not found in Domino Directory")
	short ERR_REG_USER_NOT_FOUND = PKG_REG + 27;
	@ErrorText(text="ID file not found in Domino Directory")
	short ERR_REG_IDFILE_NOT_FOUND = PKG_REG + 28;
	@ErrorText(text="User name not found in Domino Directory")
	short ERR_REG_NOSUCHUSER = PKG_REG + 29;
	@ErrorText(text="Multiple users with same name found in Domino Directory")
	short ERR_REG_NOTUNIQUE = PKG_REG + 30;
	@ErrorText(text="Server name not found in Domino Directory")
	short ERR_REG_NOSUCHSERVER = PKG_REG + 31;
	@ErrorText(text="Multiple servers with the same name found in Domino Directory")
	short ERR_REG_SERVERNOTUNIQUE = PKG_REG + 32;
	@ErrorText(text="The Domino Directory entry does not include a certified public key")
	short ERR_REG_NO_STORED_CERTKEY = PKG_REG + 34;
	@ErrorText(text="The Domino Directory you are registering the server to does not contain a $Servers view.  In order to register a server, you must use a Domino Directory.  You can replace the design of this Address Book with the Domino Directory template.")
	short ERR_REG_NO_SRV_VIEW = PKG_REG + 35;
	@ErrorText(text="The administration request could not be created: %s")
	short ERR_REG_NO_ADMINREQTOCREATEMAIL = PKG_REG + 39;
	@ErrorText(text="The administration process has not been initialized.")
	short ERR_REG_NO_ADMINPROCESS = PKG_REG + 40;
	@ErrorText(text="The distinguished name provided for registration could not be found in the directory")
	short ERR_REG_PROMOTEDN_NOT_FOUND = PKG_REG + 41;
	@ErrorText(text="You must be an NT Administrator or Account Operator to add NT users or groups.")
	short ERR_REG_NT_ACCESS_DENIED = PKG_REG + 43;
	@ErrorText(text="The NT account(s) cannot be added.  A primary domain controller for the current NT domain cannot be found.")
	short ERR_REG_NT_DC_NOT_FOUND = PKG_REG + 44;

	short PKG_SETUP = PKG_REG+51;
	@ErrorText(text="Error creating local cache for mail file : '%s', Error: %e\n")
	short ERR_REG_LOCAL_CACHE_CREATION = (PKG_REG+146);
	@ErrorText(text="Keyring file or stash file could not be created because an existing file already exists.")
	short ERR_REG_KEYRING_EXISTS = (PKG_REG+147);
	@ErrorText(text="Directory Assistance configuration could not be encrypted.  Verify the encryption on the configuration is correct.")
	short ERR_REG_MAB_NO_ENCRYPT = (PKG_REG+148);
	@ErrorText(text="This server cannot access the Directory Assistance document required to connect to the foreign directory because the document is encrypted.  To correct this problem add this server's name to the document's 'Public Encryption keys'.")
	short ERR_REG_ENCRYPTED_DA_DOC = (PKG_REG+149);
	@ErrorText(text="Unable to find applicable configuration in Directory Assistance")
	short ERR_REG_CONFIG_DA_DB = (PKG_REG+150);
	@ErrorText(text="The distinguished name provided for registration matches multiple entries in the directory")
	short ERR_REG_PROMOTEDN_AMBIG = (PKG_REG + 155);
	@ErrorText(text="No modem files are available on your system.")
	short ERR_REG_NOMODEMFILES = (PKG_REG+158);
	@ErrorText(text="Certifier names must be at least three characters long.")
	short ERR_REG_CERT_NAME_TOO_SHORT = (PKG_REG+159);
	@ErrorText(text="You must enter a phone number.")
	short ERR_REG_PHONEREQUIRED = (PKG_REG+160);
	@ErrorText(text="You must enter a filename for the certifier ID.")
	short ERR_REG_CERTREQUIRED = (PKG_REG+161);
	@ErrorText(text="You must enter a filename for the user ID.")
	short ERR_REG_USERREQUIRED = (PKG_REG+162);
	@ErrorText(text="You must enter a filename for the server ID.")
	short ERR_REG_SERVERREQUIRED = (PKG_REG+163);
	@ErrorText(text="Updating Domino Directory entry for %A")
	short ERR_REG_UPDATING_ENTRY = (PKG_REG+167);
	@ErrorText(text="Upgrading the design of your databases")
	short ERR_REG_UPGRADETEMPLATES = (PKG_REG+168);
	@ErrorText(text="You must complete server setup via the Domino setup database.")
	short ERR_REG_LAUNCH_SETUPDB = (PKG_REG+169);
	@ErrorText(text="The alternate language specified for %s was not contained in the new certifier specified.  Certifier changes were not made for this user.")
	short ERR_REG_LANG_TAG_MISSING_FROM_CERT = (PKG_REG+171);
	@ErrorText(text="The certifier was not changed for this user; the existing alternate language for this user did not exist in the new certifier specified.")
	short ERR_REG_CERT_NOT_UPDATED = (PKG_REG+172);
	@ErrorText(text="Do you want to upgrade the design of the Domino Directory? This replaces the standard forms and views with ones from the template.")
	short ERR_REG_UPGRADENAMES = (PKG_REG+173);
	@ErrorText(text="Your current Statistics & Events database has been copied to %p. The database %p will be upgraded when the Event task runs and old messages will be deleted.")
	short ERR_REG_EVENTS4_SAVED = (PKG_REG+180);
	@ErrorText(text="The new certifier specified does not contain the alternate language(s) set for one or more selected users.  The certifier will not be changed for these users.")
	short ERR_REG_MULT_LANG_TAGS_MISSING = (PKG_REG+181);
	@ErrorText(text="A duplicate full or short name was found for this user in a non-primary directory (%a).  Full and short user names must be unique to be registered.")
	short ERR_REG_NOT_PRIMARY_DIRECTORY = (PKG_REG+182);
	@ErrorText(text="Default server task %s will NOT be added to %s in NOTES.INI because %s is set.")
	short ERR_REG_SKIPPED_TASK = (PKG_REG+183);
	@ErrorText(text="A personal sub-directory could not be created for this roaming user.  A sub-directory with the same name already exists.")
	short ERR_REG_PERSONAL_SUBDIR_NOT_UNIQUE = (PKG_REG+184);
	@ErrorText(text="A personal sub-directory could not be created for this roaming user.  Create access was denied at the file system level.")
	short ERR_REG_PERSONAL_SUBDIR_NO_ACCESS = (PKG_REG+185);
	@ErrorText(text="The registration roaming setting conflicts with the roaming policy setting for this user")
	short ERR_REG_ROAMING_CONFLICT = (PKG_REG+187);
	@ErrorText(text="Entry contains no extended information")
	short ERR_REG_BTREE_NO_EXT_INFO = (PKG_REG+190);
	@ErrorText(text="Cancel migration for all entries")
	short ERR_REG_CANCEL_ALL = (PKG_REG+191);
	@ErrorText(text="Upgrade application exceeded the displayable users/groups limit for MS Windows 95/98. Please use MS Windows NT/2000 to run this upgrade application.")
	short ERR_REG_WIN95_ENTRIES_LIMIT = (PKG_REG+192);
	@ErrorText(text="Error upgrading the design of your Domino Directory.  Continue with server upgrade?")
	short ERR_REG_UPGRADENAMES_ERR = (PKG_REG+197);
	@ErrorText(text="The internet address for this user is not unique.")
	short ERR_REG_INETADDR_NOT_UNIQUE = (PKG_REG+209);
	@ErrorText(text="Different Domino Directory matches were found for the Notes hierarchical name check and the migrating user name check. No Domino Directory entry can be overwritten.")
	short ERR_REG_DUSFULLNAME_CONFLICT = (PKG_REG+210);
	@ErrorText(text="The upgrade application '%s' returned this error: %s.")
	short ERR_DUS_EXTENDED_ERROR = (PKG_REG+211);
	@ErrorText(text="No more people available from the current upgrade application.")
	short ERR_DUS_NO_MORE_USERS = (PKG_REG+212);
	@ErrorText(text="No more groups available from the current upgrade application.")
	short ERR_DUS_NO_MORE_GROUPS = (PKG_REG+213);
	@ErrorText(text="No people are available from the current upgrade application.")
	short ERR_DUS_NO_USERS = (PKG_REG+214);
	@ErrorText(text="Context information for the current Notes Upgrade Application has been corrupted.")
	short ERR_DUS_CONTEXT_CORRUPT = (PKG_REG+215);
	@ErrorText(text="The upgrade application dll '%s' could not be found or could not be loaded/initialized.")
	short ERR_DUS_UPGRADE_DLL_FAILED = (PKG_REG+216);
	@ErrorText(text="Person information could not be retrieved from the current upgrade application.")
	short ERR_DUS_RETRIEVE_FAILED = (PKG_REG+217);
	@ErrorText(text="No file path was specified for the current upgrade application.")
	short ERR_DUS_NO_UPGRADE_DLLPATH = (PKG_REG+218);
	@ErrorText(text="Mail file conversion for the migrating user '%s' failed or is incomplete.")
	short ERR_DUS_MAIL_CONVERSION_FAILED = (PKG_REG+219);
	@ErrorText(text="The upgrade application for '%s' returned this error: %s.")
	short ERR_DUS_EXTENDED_ERROR2 = (PKG_REG+220);
	@ErrorText(text="The current upgrade application returned this error: %s.")
	short ERR_DUS_EXTENDED_ERROR3 = (PKG_REG+221);
	@ErrorText(text="The current group '%s' and its members will not be migrated into Notes.")
	short ERR_DUS_SKIP_THIS_GROUP = (PKG_REG+222);
	@ErrorText(text="The registration server is down or the Domino directory on that registration server is unavailable.  Change registration servers and try migration again.")
	short ERR_DUS_REG_SERVER_DOWN = (PKG_REG+223);
	@ErrorText(text="One or more Groupwise dlls required for Groupwise to Notes migration are not present.")
	short ERR_DUS_GROUPWISE_DLLS_ABSENT = (PKG_REG+224);
	@ErrorText(text="One or more Netscape dlls required for Netscape to Notes migration are not present.")
	short ERR_DUS_NETSCAPE_DLLS_ABSENT = (PKG_REG+225);
	@ErrorText(text="The mail system must be set to 'None' for users migrated with the 'Convert mail ONLY' option.")
	short ERR_REG_DUS_MAIL_CONVERSION_ONLY = (PKG_REG+226);
	@ErrorText(text="The certifier you have selected does not contain the alternate language tag '%s' (set for the current user).  If you continue, the alternate language tag will be set to 'none' for the selected user(s).  Do you want to continue?")
	short ERR_REG_CERT_ALT_LANGUAGE_PROMPT = (PKG_REG+228);
	@ErrorText(text="Registration failed:  A policy could not be retrieved from the Domino directory.")
	short ERR_REG_WITH_POLICY_FAILED = (PKG_REG+229);
	@ErrorText(text="An internet password and a password quality of at least 1 are required when registering a user into a hosted organization.")
	short ERR_REG_HOSTED_ORG_USER_REG = (PKG_REG+230);
	@ErrorText(text="Your password is insufficiently complex. Add more characters or varied characters.")
	short ERR_REG_MINPSWDCHARS = (PKG_REG+235);
	@ErrorText(text="The alternate name '%s' is not unique in the Domino Directory.")
	short ERR_REG_ALT_NAME_NOT_UNIQUE = (PKG_REG+237);
	@ErrorText(text="Mail conversion failed.  Either the user could not be found or the original full name was not supplied.")
	short ERR_REG_CONVERT_ONLY_FAILED = (PKG_REG+238);
	@ErrorText(text="An internet password is required for users of the chosen mail system.")
	short ERR_REG_IMAP_REQUIRES_PASSWORD = (PKG_REG+241);
	@ErrorText(text="You must specify a serial port in order to connect via a modem")
	short ERR_NO_SERIAL_PORT = (PKG_REG+243);
	@ErrorText(text="One of the names to be added to the directory already exists in a different entry in the directory.  See the Notes log for details.")
	short ERR_REG_DUPLICATE_NAME = (PKG_REG+245);
	@ErrorText(text="%a did not accept a name change")
	short STR_REG_LOG_NAME_REFUSED = (PKG_REG+246);
	@ErrorText(text="The Domino directory from the currently selected server is not based on the public directory template (pubnames.ntf).")
	short ERR_REG_NAB_NOT_PUBLIC = (PKG_REG+247);
	@ErrorText(text="The type of repository for people and groups is not supported for Domino")
	short ERR_SETUP_UNSUPPORTED_DIR_TYPE = (PKG_REG+248);
	@ErrorText(text="An entry with the specified person name '%s' is already in the Domino Directory. Update the entry?")
	short ERR_REG_UPDATE_USER_PROMPT = (PKG_REG+250);
	@ErrorText(text="The registration server cannot be found, is not responding or was not specified/set.")
	short ERR_REG_NO_REG_SERVER_SPECIFIED = (PKG_REG+251);
	@ErrorText(text="No permission (flag) to modify existing Domino Directory entry (short name is duplicated)")
	short ERR_REG_ADDRBOOK_SHORTNAME_EXISTS = (PKG_REG+252);
	@ErrorText(text="A person entry with the short name '%s' already exists in the Domino Directory. Update the entry?")
	short ERR_REG_UPDATE_USER_SHORTNAME_PROMPT = (PKG_REG+253);
	@ErrorText(text="Entry found is not a person entry")
	short ERR_REG_REQUIRES_PERSON_NOTE = (PKG_REG+254);
	@ErrorText(text="The current certifier ID contains no recovery information and will not allow ID/password recovery on IDs created with this certifier.  The 'EscrowAgent' ID recovery mechanism is no longer supported.\n\nDisplay this warning in the future?")
	short ERR_REG_CERTIFIER_NO_RECOVERY_INFO = (PKG_REG+255);
	@ErrorText(text="Creating administration request to create mail file for %A...")
	short ERR_REG_CREATING_ADMINREQTOCREATE_MAILREPLICA = (PKG_REG2+0);
	@ErrorText(text="Creating mail file replica stub for %A...")
	short ERR_REG_CREATING_MAILREPLICA = (PKG_REG2+1);
	@ErrorText(text="Mail file replica stub(s) for %A could not be created")
	short ERR_REG_NO_MAILREPLICAS_CREATED = (PKG_REG2+2);
	@ErrorText(text="Creation of the mail or roaming file replica stub '%A' failed with the following error:  %s")
	short ERR_REG_USER_FILE_REPLICATION = (PKG_REG2+3);
	@ErrorText(text="Creation of an admin process request to create a mail or roaming file replica on server '%A' failed with this error:  %s")
	short ERR_REG_USER_MAILREPS_ADMINP_REQUEST = (PKG_REG2+4);
	@ErrorText(text="No CA enabled certifiers could be found in the directory.")
	short ERR_REG_NO_CACERTS_AVAILABLE = (PKG_REG2+5);
	@ErrorText(text="You must specify a storage location for this organization.")
	short ERR_REG_MISSING_ORG_STORAGE = (PKG_REG2+6);
	@ErrorText(text="The organization's storage directory must be relative to data directory.")
	short ERR_REG_ORG_STORAGE_MUSTBERELATIVE = (PKG_REG2+7);
	@ErrorText(text="You must specify an internet domain for this organization")
	short ERR_REG_MISSING_ORG_INTERNET_DOMAIN = (PKG_REG2+8);
	@ErrorText(text="Since the organization certifier is CA enabled, you must specify a certificate authority server name.")
	short ERR_REG_MISSING_CA_SERVER = (PKG_REG2+9);
	@ErrorText(text="The Domino Directory on the Directory Server is not enabled for Hosted Organizations.")
	short ERR_REG_NAB_NOT_VIRTUALIZED = (PKG_REG2+10);
	@ErrorText(text="The storage location could not be used for this organization.  A storage location with the same name exists or is already in use.")
	short ERR_REG_ORG_STORAGE_NOT_UNIQUE = (PKG_REG2+11);
	@ErrorText(text="The effective registration policy 'Choose the mail server' field must contain a server that you have administrator rights on.")
	short ERR_REG_POLICY_HOSTING_SERVER_NEEDED = (PKG_REG2+12);
	@ErrorText(text="The effective registration policy 'Choose a password quality' field can not be 'Password is optional' to register an organization.")
	short ERR_REG_POLICY_PASSWORD_QUALITY_NEEDED = (PKG_REG2+13);
	@ErrorText(text="The effective registration policy 'Set Internet Password' field must be a checked to register an organization.")
	short ERR_REG_POLICY_INTERNET_PASSWORD_NEEDED = (PKG_REG2+14);
	@ErrorText(text="The effective registration policy 'Choose the mail server' field must be a DOLS server to register an organization.")
	short ERR_REG_POLICY_DOLS_SERVER_NEEDED = (PKG_REG2+15);
	@ErrorText(text="The effective registration policy 'Create a Notes ID' field must be a checked to support the CA process, DOLS and IBM Notes mail.")
	short ERR_REG_POLICY_ID_CREATION_NEEDED = (PKG_REG2+16);
	@ErrorText(text="The effective registration policy 'In Domino Directory' ID storage field must be a checked to support CA process, DOLS and IBM Notes mail.")
	short ERR_REG_POLICY_ID_IN_NAB_NEEDED = (PKG_REG2+17);
	@ErrorText(text="You must specify a properly formatted IP address.")
	short ERR_REG_BAD_IP_ADDRESS_FORMAT = (PKG_REG2+18);
	@ErrorText(text="The distinguished name provided for registration matches an entry in a non-primary directory")
	short ERR_REG_PROMOTEDN_NONPRIMARY = (PKG_REG2 + 21);
	@ErrorText(text="The distinguished name provided for registration matches an existing Domino person")
	short ERR_REG_PROMOTEDN_EXISTING = (PKG_REG2 + 22);
	@ErrorText(text="The organization's physical storage directory must be an absolute path.")
	short ERR_REG_ORG_STORAGE_MUSTBEABSOLUTE = (PKG_REG2+23);
	@ErrorText(text="A distinguished name is required for registration")
	short ERR_REG_DNREQUIRED = (PKG_REG2 + 25);
	@ErrorText(text="Existing Domino Directory entry (duplicate full name) not updated by administrator.")
	short ERR_REG_USER_NOT_UPDATED_FULLNAME = (PKG_REG2+27);
	@ErrorText(text="Existing Domino Directory entry (duplicate short name) not updated by administrator.")
	short ERR_REG_USER_NOT_UPDATED_SHORTNAME = (PKG_REG2+28);
	@ErrorText(text="Existing UserID file not updated by administrator.")
	short ERR_REG_USERID_NOT_UPDATED = (PKG_REG2+29);
	@ErrorText(text="The specified roaming server is pre 6 and does not support roaming features.  Select a different roaming server.")
	short ERR_REG_ROAMING_SERVER_VERSION = (PKG_REG2+30);
	@ErrorText(text="Only the ASP certifier can be used to register a hosted organization.")
	short ERR_REG_ASP_CERT_NEEDED = (PKG_REG2+31);
	@ErrorText(text="You must remove the original organization directory before you can move the organization storage location.")
	short ERR_REG_ORIGINAL_ORG_DIR_EXISTS = (PKG_REG2+32);
	@ErrorText(text="The organization's physical storage must contain at least one directory.  Drive names are not valid")
	short ERR_REG_ORG_STORAGE_DRIVE_INVALID = (PKG_REG2 + 38);
	@ErrorText(text="Internet address failed with the following error:  %e")
	short ERR_REG_USERREG_BAD_INETADDR = (PKG_REG2+39);
	@ErrorText(text="Creating roaming file replica stubs for %A...")
	short ERR_REG_CREATING_ROAMINGREPLICA = (PKG_REG2+41);
	@ErrorText(text="Roaming file replica stubs for %A could not be created")
	short ERR_REG_NO_ROAMINGREPLICAS_CREATED = (PKG_REG2+42);
	@ErrorText(text="The user could not be added to the group(s) specified.")
	short ERR_REG_GROUPS_ERROR = (PKG_REG2+43);
	@ErrorText(text="%a could not be added to the group: '%a'.")
	short ERR_REG_GROUPS_ERROR_DETAIL = (PKG_REG2+44);
	@ErrorText(text="The specified mail server is pre 6 and does not support the ID in mail file feature.  Select a different mail server.")
	short ERR_REG_ID_IN_MAILFILE_SERVER_VERSION = (PKG_REG2+48);
	@ErrorText(text="LocalDomainAdmins")
	short STR_REG_LOCAL_DOMAIN_ADMINS = (PKG_REG2+50);
	@ErrorText(text="The security policy is set to deny this operation")
	short ERR_REG_SECURITY_POLICY_DENY_OPERATION = (PKG_REG2+51);
	@ErrorText(text="You are not authorized to add Person documents in this Domino Directory")
	short ERR_REG_USER_CREATOR_ROLE = (PKG_REG2+52);
	@ErrorText(text="You are not authorized to modify Person documents in this Domino Directory")
	short ERR_REG_USER_MODIFIER_ROLE = (PKG_REG2+53);
	@ErrorText(text="You are not authorized to add Group documents in this Domino Directory")
	short ERR_REG_GROUP_CREATOR_ROLE = (PKG_REG2+54);
	@ErrorText(text="You are not authorized to modify Group documents in this Domino Directory")
	short ERR_REG_GROUP_MODIFIER_ROLE = (PKG_REG2+55);
	@ErrorText(text="You are not authorized to add Server documents in this Domino Directory")
	short ERR_REG_SERVER_CREATOR_ROLE = (PKG_REG2+56);
	@ErrorText(text="You are not authorized to modify Server documents in this Domino Directory")
	short ERR_REG_SERVER_MODIFIER_ROLE = (PKG_REG2+57);
	@ErrorText(text="You are not authorized to add Policy documents in this Domino Directory")
	short ERR_REG_POLICY_CREATOR_ROLE = (PKG_REG2+58);
	@ErrorText(text="You are not authorized to modify Policy documents in this Domino Directory")
	short ERR_REG_POLICY_MODIFIER_ROLE = (PKG_REG2+59);
	@ErrorText(text="You are not authorized to add that document type to this Domino Directory")
	short ERR_REG_NET_CREATOR_ROLE = (PKG_REG2+60);
	@ErrorText(text="You are not authorized to modify that document type in this Domino Directory")
	short ERR_REG_NET_MODIFIER_ROLE = (PKG_REG2+61);
	@ErrorText(text="The Domino Directory is missing a required item (created during setup)")
	short ERR_REG_BAD_ASP_SETUP = (PKG_REG2+62);
	@ErrorText(text="The Domino Directory on the registration server cannot be a configuration-only (userless) directory")
	short ERR_REG_USERLESS_REGSERVER = (PKG_REG2+63);
	@ErrorText(text="You do not have any of the required roles in the Domino Directory")
	short ERR_REG_NO_ROLES = (PKG_REG2+64);
	@ErrorText(text="The local data directory is client-based and cannot be used for server-based operations")
	short ERR_REG_CLIENT_DATA_DIR = (PKG_REG2+65);
	@ErrorText(text="Creation of the sub-directory %A failed with the following error:  %s")
	short ERR_REG_PERSONAL_SUBDIR_ERROR = (PKG_REG2+66);
	@ErrorText(text="The combination of first, middle and last names is %d byte(s) too long.")
	short ERR_REG_COMMON_NAME_TOO_LONG = (PKG_REG2+67);
	@ErrorText(text="Configuring SSL for %A")
	short STR_REG_SSLCONFIG = (PKG_REG2+68);
	@ErrorText(text="A hostname is required to configure SSL.")
	short ERR_REG_SSL_HOSTNAME = (PKG_REG2+69);
	@ErrorText(text="%a's Certification Log")
	short STR_CERTLOG_TITLE = (PKG_REG2+70);
	@ErrorText(text="%a is the signer of policy %a and will not be deleted until the policy has been signed (saved) by someone else.")
	short ERR_REG_POLICY_SIGNER = (PKG_REG2+71);
	@ErrorText(text="None of %a's internet certificates (issued by the following authorities:  %a) contain the new internet address %s.")
	short ERR_REG_HAS_NO_INET_CERT = (PKG_REG2+73);
	@ErrorText(text="Admin Process: Received the error %e trying to add %a's name to the %s profile of the Directory.")
	short ERR_REG_PROFILE = (PKG_REG2+75);
	@ErrorText(text="Replicating Domino Directory changes...")
	short ERR_REG_REPLICATING_DIR = (PKG_REG2+76);
	@ErrorText(text="The server does not contain storage for the hosted organization")
	short ERR_REG_NO_HOSTED_ORG_STORAGE = (PKG_REG2+78);
	@ErrorText(text="Admin Process: ")
	short ERR_REG_ADMINP_PREFIX = (PKG_REG2+80);
	@ErrorText(text="You are not a Registration Authority for the certifier.")
	short ERR_REG_NOT_RA = (PKG_REG2+84);
	@ErrorText(text="An invalid key width has been supplied.")
	short ERR_REG_INVALID_KEYWIDTH = (PKG_REG2+85);
	@ErrorText(text="An invalid password key width has been supplied.")
	short ERR_REG_INVALID_PASSWORD_KEYWIDTH = (PKG_REG2+86);
	@ErrorText(text="An invalid internet public key width has been supplied.")
	short ERR_REG_INVALID_INETPUB_KEYWIDTH = (PKG_REG2+87);
	@ErrorText(text="You are not authorized to set database quotas")
	short ERR_REG_NO_SETQUOTA_ACCESS = (PKG_REG2+88);
	@ErrorText(text="You are not authorized to create database")
	short ERR_REG_NO_DBCREATE_ACCESS = (PKG_REG2+89);
	@ErrorText(text="You are not authorized to create file system folder")
	short ERR_REG_NO_FOLDERCREATE_ACCESS = (PKG_REG2+90);
	@ErrorText(text="A file with this person's mail file name already exists.  Supply a unique name for this person's mail file.")
	short ERR_REG_DUPLICATE_MAIL_FILE = (PKG_REG2+92);
	@ErrorText(text="A file with this person's mail file name already exists. Overwrite access was denied at the file system level. Supply a unique name for this person's mail file.")
	short ERR_REG_MAIL_FILE_NO_ACCESS = (PKG_REG2+93);
	@ErrorText(text="Insufficient disk space. Please try later.")
	short ERR_REG_INSUFFICIENT_DISK_SPACE_FOR_CACHE = (PKG_REG2+96);
	@ErrorText(text="An internet address is required for users of the selected mail system.")
	short ERR_REG_MAILSYSTEM_REQUIRES_INETADDR = (PKG_REG2+122);
	@ErrorText(text="A forwarding address is required for users of the selected mail system.")
	short ERR_REG_MAILSYSTEM_REQUIRES_FWDADDR = (PKG_REG2+123);
	@ErrorText(text="A Notes ID must be created for a roaming user.")
	short ERR_REG_ROAMING_REQUIRES_ID = (PKG_REG2+124);
	@ErrorText(text="A user of the selected mail system may not roam.")
	short ERR_REG_MAILSYSTEM_NO_ROAMING = (PKG_REG2+125);
	@ErrorText(text="A user of the selected mail system may not store a Notes ID in their mail file.")
	short ERR_REG_MAILSYSTEM_NO_IDINMAIL = (PKG_REG2+126);
	@ErrorText(text="There are multiple matches for the user name you entered.  Please enter your full unique user name.")
	short ERR_REG_UNIQUE_NAME_NEEDED = (PKG_REG2+127);

}
