package com.mindoo.domino.jna.errors.errortexts;

public interface ISecErr extends IGlobalErr {

	@ErrorText(text="Security package software error #1")
	short ERR_SECURE_BUG_1 = PKG_SECURE+1;
	@ErrorText(text="Could not open the ID file")
	short ERR_SECURE_NOKEYFILE = PKG_SECURE+2;
	@ErrorText(text="Network traffic is being encrypted at the server's request...")
	short ERR_SECURE_ENCRYPTED = PKG_SECURE+3;
	@ErrorText(text="Unknown authentication function code")
	short ERR_SECURE_UNKNOWNFCT = PKG_SECURE+4;
	@ErrorText(text="Your ID has not been certified to access the server")
	short ERR_SECURE_NOCLIENTCERT = PKG_SECURE+5;
	@ErrorText(text="The server's ID has not been certified for your access")
	short ERR_SECURE_NOSERVERCERT = PKG_SECURE+6;
	@ErrorText(text="Password handler already established")
	short ERR_SECURE_ESTABLISHED = PKG_SECURE+7;
	@ErrorText(text="Wrong Password. (Passwords are case sensitive - be sure to use correct upper and lower case.)")
	short ERR_SECURE_BADPASSWORD = PKG_SECURE+8;
	@ErrorText(text="Security protocol error #1")
	short ERR_SECURE_PROTOCOL_1 = PKG_SECURE+9;
	@ErrorText(text="Security context is invalid")
	short ERR_SECURE_INVALIDCTX = PKG_SECURE+10;
	@ErrorText(text="Remote user failed authentication")
	short ERR_SECURE_INVRESPONSE = PKG_SECURE+11;
	@ErrorText(text="Authentication using Windows NTLM security is not supported.")
	short ERR_SECURE_WINNTLM_NOT_SUPP = PKG_SECURE+12;
	@ErrorText(text="ID's certificate is invalid")
	short ERR_SECURE_INVCERTKEY = PKG_SECURE+13;
	@ErrorText(text="The remote ID was never received")
	short ERR_SECURE_NOUSERINFO = PKG_SECURE+14;
	@ErrorText(text="Ticket is invalid")
	short ERR_SECURE_INVTICKET = PKG_SECURE+15;
	@ErrorText(text="Remote user's identity is fraudulent")
	short ERR_SECURE_FRAUD = PKG_SECURE+16;
	@ErrorText(text="Authentication has not yet been attempted")
	short ERR_SECURE_UNAUTH = PKG_SECURE+17;
	@ErrorText(text="failed to authenticate")
	short ERR_SECURE_FAILED_AUTH = PKG_SECURE+18;
	@ErrorText(text="You cannot require more passwords than there are")
	short ERR_SECURE_TOO_MANY_PWDS = PKG_SECURE+19;
	@ErrorText(text="You must require at least one password")
	short ERR_SECURE_ZERO_PWDS = PKG_SECURE+20;
	@ErrorText(text="There cannot be more than eight passwords on an ID")
	short ERR_SECURE_MAX_PWDS = PKG_SECURE+21;
	@ErrorText(text="Remote authentication protocol version is no longer supported")
	short ERR_SECURE_OLDAUTHVERSION = PKG_SECURE+22;
	@ErrorText(text="Your ID has not been certified by a certifier that is trusted by the server")
	short ERR_SECURE_NOTRUSTED_CLIENTCERT = PKG_SECURE+23;
	@ErrorText(text="The server's ID has not been certified by a certifier that you trust")
	short ERR_SECURE_NOTRUSTED_SERVERCERT = PKG_SECURE+24;
	@ErrorText(text="Network error: the message content was unexpected or the message has been corrupted")
	short ERR_SECURE_BADMSGDATA = PKG_SECURE+25;
	@ErrorText(text="You must type something; you may not have a zero length password.")
	short ERR_SECURE_ZERO_LENGTH_PW = PKG_SECURE+26;
	@ErrorText(text="Network authentication message is too short")
	short ERR_SECURE_SHORTMSG = PKG_SECURE+27;
	@ErrorText(text="Your certificate has expired")
	short ERR_SECURE_EXPIRED_CERT = PKG_SECURE+28;
	@ErrorText(text="Remote authentication protocol version is not yet supported")
	short ERR_SECURE_FUTUREAUTHVERSION = PKG_SECURE+29;
	@ErrorText(text="Your User ID has expired")
	short ERR_SECURE_EXPIRED_UI = PKG_SECURE+30;
	@ErrorText(text="The Server's ID has expired")
	short ERR_SECURE_EXPIRED_SERVERUI = PKG_SECURE+31;
	@ErrorText(text="Authentication error: the remote name, license, or key changed while authenticating")
	short ERR_SECURE_DISTINFO_CHANGE = PKG_SECURE+33;
	@ErrorText(text="The password and its confirmation value are not the same")
	short ERR_SECURE_PW_NOT_CONFIRMED = PKG_SECURE+34;
	@ErrorText(text="Security protocol error #2")
	short ERR_SECURE_PROTOCOL_2 = PKG_SECURE+35;
	@ErrorText(text="An invalid session encryption key was received")
	short ERR_SECURE_BADSESSKEY = PKG_SECURE+36;
	@ErrorText(text="Security protocol error #4")
	short ERR_SECURE_PROTOCOL_4 = PKG_SECURE+37;
	@ErrorText(text="Security protocol error #5")
	short ERR_SECURE_PROTOCOL_5 = PKG_SECURE+38;
	@ErrorText(text="Security protocol error #6")
	short ERR_SECURE_PROTOCOL_6 = PKG_SECURE+39;
	@ErrorText(text="Unknown authentication message type was received")
	short ERR_SECURE_UNKNOWN_MSG = PKG_SECURE+40;
	@ErrorText(text="Security protocol error #8")
	short ERR_SECURE_PROTOCOL_8 = PKG_SECURE+41;
	@ErrorText(text="Authentication message received out of sequence")
	short ERR_SECURE_RCVUNEXPMSG = PKG_SECURE+42;
	@ErrorText(text="Security protocol error #10")
	short ERR_SECURE_PROTOCOL_10 = PKG_SECURE+43;
	@ErrorText(text="Security protocol error #11")
	short ERR_SECURE_PROTOCOL_11 = PKG_SECURE+44;
	@ErrorText(text="Access denied for upload to the ID Vault - user already in ID Vault")
	short ERR_SECURE_ID_VAULT_UPLOAD_ACCESS_DENIED = PKG_SECURE+45;
	@ErrorText(text="Your public key does not match the one stored in the Address Book")
	short ERR_SECURE_NOKEYMATCH = PKG_SECURE+50;
	@ErrorText(text="The server's certificate has expired")
	short ERR_SECURE_SERVER_EXPIRED_CERT = PKG_SECURE+51;
	@ErrorText(text="The server's Domino Directory does not contain any cross certificates capable of authenticating you.")
	short ERR_SECURE_NO_SERVER_CROSS_CERT = PKG_SECURE+52;
	@ErrorText(text="Your Address Book does not contain any cross certificates capable of authenticating the server.")
	short ERR_SECURE_NO_CLIENT_CROSS_CERT = PKG_SECURE+53;
	@ErrorText(text="The server's ID file has been corrupted, or is not an ID file.")
	short ERR_SECURE_SERVER_ID_CORRUPT = PKG_SECURE+54;
	@ErrorText(text="A passthru message was received without the necessary context")
	short ERR_SECURE_NO_PASSTHRU_CTX = PKG_SECURE+55;
	@ErrorText(text="The session is in the wrong state to accept that request")
	short ERR_SECURE_WRONG_STATE = PKG_SECURE+56;
	@ErrorText(text="The session has been put into Passthru mode")
	short ERR_NETBFR_PASSTHRU = PKG_SECURE+57;
	@ErrorText(text="Passthru function codes is not recognized")
	short ERR_SECURE_ILL_PASSTHRU_FCT = PKG_SECURE+58;
	@ErrorText(text="Would pass through a server more than once")
	short ERR_PASSTHRU_SERVER_ON_PATH = PKG_SECURE+59;
	@ErrorText(text="Server is too many hops away to establish a connection")
	short ERR_PASSTHRU_TOO_DEEP = PKG_SECURE+60;
	@ErrorText(text="Lite transaction attempted over passthru")
	short ERR_LITE_TRANS_VIA_PT = PKG_SECURE+61;
	@ErrorText(text="Security package software error #2")
	short ERR_SECURE_BUG_2 = PKG_SECURE+62;
	@ErrorText(text="Security package software error #3")
	short ERR_SECURE_BUG_3 = PKG_SECURE+63;
	@ErrorText(text="Security package software error #4")
	short ERR_SECURE_BUG_4 = PKG_SECURE+64;
	@ErrorText(text="Security package software error #5")
	short ERR_SECURE_BUG_5 = PKG_SECURE+65;
	@ErrorText(text="Security package software error #6")
	short ERR_SECURE_BUG_6 = PKG_SECURE+66;
	@ErrorText(text="Security package software error #7")
	short ERR_SECURE_BUG_7 = PKG_SECURE+67;
	@ErrorText(text="Security package software error #8")
	short ERR_SECURE_BUG_8 = PKG_SECURE+68;
	@ErrorText(text="Security package software error #9")
	short ERR_SECURE_BUG_9 = PKG_SECURE+69;
	@ErrorText(text="Internal authentication error: missing initialization block")
	short ERR_SECURE_MISSING_INITBLOCK = PKG_SECURE+70;
	@ErrorText(text="Internal authentication error: missing memory object")
	short ERR_SECURE_MISSING_OBJECT = PKG_SECURE+71;
	@ErrorText(text="The proposed alternate name could not be used because an alternate name has already been assigned.")
	short ERR_SECURE_PROPOSED_ALTNAME_NOT_USED = PKG_SECURE+78;
	@ErrorText(text="The Certifying Authority has not been assigned an alternate name which is an ancestor of the alternate name specified.")
	short ERR_SECURE_NOT_ALT_ANCESTOR = PKG_SECURE+79;
	@ErrorText(text="More hops to follow")
	short ERR_PASSTHRU_MORE_HOPS = PKG_SECURE+80;
	@ErrorText(text="Passthru connect to remote server failed")
	short ERR_PASSTHRU_FAILED = PKG_SECURE+81;
	@ErrorText(text="The server just connected to is not a Passthru server")
	short ERR_SECURE_NON_PTSERVER = PKG_SECURE+82;
	@ErrorText(text="Unable to execute your Windows password change")
	short ERR_SECURE_NT_SETPASSWORD = PKG_SECURE+84;
	@ErrorText(text="Enter one of the multiple passwords (press the Esc key to abort): ")
	short ERR_SECURE_MULTI_PSW_PROMPT = (PKG_SECURE+116);
	@ErrorText(text="This ID file requires multiple passwords.")
	short ERR_SECURE_MULTI_PSW_REQUIRED = (PKG_SECURE+117);
	@ErrorText(text="Illegal destination server name")
	short ERR_PT_WILDCARD_DST = PKG_SECURE+120;
	@ErrorText(text="Protocol error: Network authentication was never attempted")
	short ERR_PROTERR_NO_AUTHENTICATION = PKG_SECURE+121;
	@ErrorText(text="Object validity dates not within specified time range")
	short ERR_SECURE_NOT_WITHIN_TIMERANGE = PKG_SECURE+122;
	@ErrorText(text="You must first upgrade this entry to contain a hierarchical name before you can recertify it.")
	short ERR_SECURE_FLAT_PUBLICINFO = PKG_SECURE+123;
	@ErrorText(text="A path to the server could not be determined from the Connection documents in the Name and Address Book")
	short ERR_NO_PATH_FROM_CONN_REC = PKG_SECURE+124;
	@ErrorText(text="You have attempted to pass through a server that does not support passthru")
	short ERR_PASSTHRU_NOT_SUPPORTED = PKG_SECURE+125;
	@ErrorText(text="You are running with a version of the passthru protocol which is no longer supported")
	short ERR_NO_PASSTHRU_BAD_VERSION = PKG_SECURE+126;
	@ErrorText(text="Insufficient memory - search path pool is full.")
	short ERR_JSPATH_POOLFULL = PKG_SECURE+127;
	@ErrorText(text="An unexpected authentication message was received")
	short ERR_SECURE_UNEXPMSG = PKG_SECURE+128;
	@ErrorText(text="Would you like to update your current name to the following:")
	short ERR_SECURE_NEWNAME_QUERY = PKG_SECURE+129;
	@ErrorText(text="The remote client refused the name update")
	short ERR_SECURE_NEWNAME_REFUSED = PKG_SECURE+130;
	@ErrorText(text="The remote system failed to prove its identity")
	short ERR_SECURE_WRONG_CHALLENGE = PKG_SECURE+131;
	@ErrorText(text="Internal error: request to make an unknown Proxy Database entry")
	short ERR_SECURE_UNKNOWN_PROXY_FCT = PKG_SECURE+132;
	@ErrorText(text="Internal error: a required parameter in a subroutine call has not been supplied")
	short ERR_SECURE_MISSING_ARG = PKG_SECURE+133;
	@ErrorText(text="The new name in the supplied Name Change Request does not match the subject name in the supplied certificate")
	short ERR_SECURE_CHANGE_WRONG_NEW_NAME = PKG_SECURE+134;
	@ErrorText(text="The supplied certificate is a cross certificate; a certificate issued by an ancestor of the subject name is required")
	short ERR_SECURE_CROSS_CERT_NOT_ALLOWED = PKG_SECURE+135;
	@ErrorText(text="The name of the authority issuing the Name Change Request does not match the certifier name in the supplied certificate")
	short ERR_SECURE_CHANGE_CERT_ISSUER_MISMATCH = PKG_SECURE+136;
	@ErrorText(text="The name of the authority issuing the Name Change Request is not allowed to make that request.")
	short ERR_SECURE_ILL_CHANGE_ISSUER = PKG_SECURE+137;
	@ErrorText(text="The Name Change Request is of an unknown type")
	short ERR_SECURE_UNKNOWN_CHANGE_TYPE = PKG_SECURE+138;
	@ErrorText(text="The signature on the Name Change Request was found to be invalid")
	short ERR_SECURE_INVALID_CHANGE_SIG = PKG_SECURE+139;
	@ErrorText(text="The signature in one of the supplied certificates was found to be invalid")
	short ERR_SECURE_INVALID_CERT_SIG = PKG_SECURE+140																 ;
	@ErrorText(text="The public keys specified in the Name Change Request do not match those specified in the new certificate")
	short ERR_SECURE_CHANGE_CERT_KEY_MISMATCH = PKG_SECURE+141;
	@ErrorText(text="The information in the supplied certificates from the Address Book entry is out of date")
	short ERR_SECURE_STALE_ABPI = PKG_SECURE+142;
	@ErrorText(text="The Name Change Request specifies a name or key change, but the change allowed is an update from a flat to a hierarchical name")
	short ERR_SECURE_UPGRADE_ONLY = PKG_SECURE+143;
	@ErrorText(text="The new name specified in the Name Change Request is not a hierarchical name")
	short ERR_SECURE_CHANGE_MUST_BE_HI = PKG_SECURE+144;
	@ErrorText(text="When upgrading an name from flat to hierarchical, the flat name must match the first component in the hierarchical name")
	short ERR_SECURE_UPGRADE_NAME_MISMATCH = PKG_SECURE+145;
	@ErrorText(text="When moving a name in the name hierarchy, the first component of the old and new names must be the same")
	short ERR_SECURE_CHANGE_ILL_MOVE_NAMES = PKG_SECURE+146;
	@ErrorText(text="The Name Change Request contains inconsistent or incomplete information")
	short ERR_SECURE_INCONSIST_CHANGE_REQ = PKG_SECURE+147;
	@ErrorText(text="One or more of the fields in the Name Change Request could not be interpreted")
	short ERR_SECURE_CHANGE_UNKNOWN_FIELDS = PKG_SECURE+148;
	@ErrorText(text="The old name in the Name Change Request does not match the name trying to be changed")
	short ERR_SECURE_CHANGE_WRONG_OLD_NAME = PKG_SECURE+149;
	@ErrorText(text="Authentication protocol error: no Name Change Request was sent to the client")
	short ERR_SECURE_NO_CHANGE_REQ = PKG_SECURE+150;
	@ErrorText(text="The hierarchical certificates in your ID file have been updated with new expiration dates")
	short ERR_SECURE_NEWCERTS_QUERY = PKG_SECURE+151;
	@ErrorText(text="There is no appropriate key or certificate stored in the Address Book for this entry")
	short ERR_SECURE_NOKEY_IN_AB = PKG_SECURE+152;
	@ErrorText(text="The signatures in the Name Change Request and Change Signature items did not match")
	short ERR_SECURE_WRONG_CHANGE_SIG = PKG_SECURE+153;
	@ErrorText(text="The name change request document does not contain a Change Signature item")
	short ERR_SECURE_MISSING_CHANGE_SIG = PKG_SECURE+154;
	@ErrorText(text="You must be running with a hierarchical name to access this server")
	short ERR_SECURE_PW_YOU_MUST_BE_HI = PKG_SECURE+155;
	@ErrorText(text="The server requires that you be running Notes version 4.5 or greater in order to test your password")
	short ERR_SECURE_PW_SUPPORT_VERS = PKG_SECURE+156;
	@ErrorText(text="Did not accept the new certificates because they were not issued after the current certificates")
	short ERR_SECURE_CERT_NOT_NEWER = PKG_SECURE+157;
	@ErrorText(text="The certificate stored in the name change request entry is not for the key specified in the name change request")
	short ERR_SECURE_WRONG_NEWABPI = PKG_SECURE+196;
	@ErrorText(text="The keys stored in the Address Book document for this entry are not the same as the keys specified in the name change request")
	short ERR_SECURE_WRONG_OLDABPI = PKG_SECURE+197;
	@ErrorText(text="Error occurred attempting to log to the Certifier Log")
	short ERR_SECURE_CERTLOG_ERROR = PKG_SECURE+200;
	@ErrorText(text="The name cannot be upgraded to hierarchical, it is already hierarchical")
	short ERR_SECURE_NAME_ALREADY_HI = PKG_SECURE+201;
	@ErrorText(text="The selected certifier is not allowed to perform that action")
	short ERR_SECURE_WRONG_CERTIFIER = PKG_SECURE+202;
	@ErrorText(text="The name in the Name Change Request field does not match the name in the Certificate field")
	short ERR_SECURE_CERT_CHANGEREQ_MISMATCH = PKG_SECURE+203;
	@ErrorText(text="The selected certifier is not an ancestor of the entity to be updated")
	short ERR_SECURE_UPDATE_NOT_ANCESTOR = PKG_SECURE+204;
	@ErrorText(text="The move request was not initiated by one of the named entity's ancestors")
	short ERR_SECURE_MOVE_REQ_NOT_ANCESTOR = PKG_SECURE+205;
	@ErrorText(text="The selected certifier is not the target certifier mentioned in the move request")
	short ERR_SECURE_MOVE_REQ_NOT_TARGET = PKG_SECURE+206;
	@ErrorText(text="The note does not contain a valid move request")
	short ERR_SECURE_INVALID_MOVE_REQUEST = PKG_SECURE+207;
	@ErrorText(text="The note does not contain a name")
	short ERR_SECURE_NONAME_IN_NOTE = PKG_SECURE+208;
	@ErrorText(text="The note does not contain either a public key or a certificate")
	short ERR_SECURE_NOPUBKEY_IN_NOTE = PKG_SECURE+209;
	@ErrorText(text="The note does not contain a name Change Request field")
	short ERR_SECURE_NOCHANGEREQ_IN_NOTE = PKG_SECURE+210;
	@ErrorText(text="")
	short STR_SECURE_VIEWRENAME_STATS = PKG_SECURE+211;
	@ErrorText(text="The request note's required ACTION field is missing or is improperly formed")
	short ERR_SECURE_INV_ACTION_ITEM = PKG_SECURE+216;
	@ErrorText(text="The request note's required CERTIFICATE field is missing or is improperly formed")
	short ERR_SECURE_INV_CERT_ITEM = PKG_SECURE+217;
	@ErrorText(text="The request note's required CHANGE REQUEST field is missing or is improperly formed")
	short ERR_SECURE_INV_CHANGE_ITEM = PKG_SECURE+218;
	@ErrorText(text="The port mapper does not allow multiple hops.")
	short ERR_SECURE_MULTIPLEMAPPINGS = PKG_SECURE+219;
	@ErrorText(text="Error in received message type %d (decimal)")
	short ERR_SECURE_RCVMSG_TYPE = PKG_SECURE+220;
	@ErrorText(text="Error changing our name in database: %s (File name: %s)")
	short ERR_SECURE_UPDATE_DB_ERR = PKG_SECURE+222;
	@ErrorText(text="Successfully changed our name in database: %s (File name: %s)")
	short ERR_SECURE_UPDATE_DB_OK = PKG_SECURE+223;
	@ErrorText(text="Error updating local ID file")
	short ERR_SECURE_CHECK_ID_UPDATE = PKG_SECURE+224;
	@ErrorText(text="Your Windows account password does not match your Notes password. To synchronize the passwords, use File - Security - User Security and click Change Password.")
	short ERR_SECURE_PASS_NOT_SAME = PKG_SECURE+236;
	@ErrorText(text="Your new Windows password is set. To complete the synchronization, you must log off and back into your Windows account. Do you want to log off now?")
	short ERR_SECURE_NT_RELOGON = PKG_SECURE+237;
	@ErrorText(text="You have a different password on another copy of your ID file and you must change the password on this copy to match")
	short ERR_SECURE_UNSYNCED_PASSWORD = PKG_SECURE+238;
	@ErrorText(text="The name %s could not be changed to %s in the Readers and Authors fields of the signed and encrypted documents in %s.")
	short ERR_SECURE_NAME_IN_SIGNED_DOCS = PKG_SECURE+239;
	@ErrorText(text="The server you are trying to access requires that your ID file have a single password")
	short ERR_SECURE_NO_MULTIPW = PKG_SECURE+240;
	@ErrorText(text="WARNING: Your password will expire on ")
	short ERR_SECURE_PWD_TO_EXPIRE = PKG_SECURE+241;
	@ErrorText(text="You must change your password. It expired on ")
	short ERR_SECURE_PWD_EXPIRED = PKG_SECURE+242;
	@ErrorText(text="Connection failed because of a problem with clock synchronization and password change intervals. Check your clock setting, change your password, or consult your system administrator")
	short ERR_SECURE_PW_CLOCK_PROBLEM = PKG_SECURE+243;
	@ErrorText(text="Your password has expired. You cannot access this server until you change it")
	short ERR_SECURE_PWD_EXPIRED_AUTH = PKG_SECURE+244;
	@ErrorText(text="The server you are trying to access requires that your ID file have a password")
	short ERR_SECURE_PASSWORD_REQUIRED = PKG_SECURE+245;
	@ErrorText(text="The version of the Notes you are running does not recognize the Template Development key that signed this document")
	short ERR_SECURE_BAD_TEMPLATE_KEY = PKG_SECURE+246;
	@ErrorText(text="The server you are trying to access requires password enhanced authentication, which is not possible with a non-hierarchical ID. Tell your system administrator to either upgrade your ID or remove the requirement on the server.")
	short ERR_SECURE_FLAT_PASSWORD = PKG_SECURE+248;
	@ErrorText(text="You have used this password before. Please choose a new one")
	short ERR_SECURE_PASSWORD_REUSE = PKG_SECURE+249;
	@ErrorText(text="Your password does not match the one stored in your entry in the server's Domino Directory.")
	short ERR_SECURE_PW_MISMATCH = PKG_SECURE+250;
	@ErrorText(text="Your entry in the server's Domino Directory specifies that authentication is not allowed.")
	short ERR_SECURE_AUTH_LOCKOUT = PKG_SECURE+251;
	@ErrorText(text="Your account is locked out; see your system administrator to reset it")
	short ERR_SECURE_PWD_REALLY_EXPIRED = PKG_SECURE+252;
	@ErrorText(text="The new password could not be accepted because it is a repeat of a former password")
	short ERR_SECURE_NEW_PW_REPEAT = PKG_SECURE+253;
	@ErrorText(text="The new password could not be accepted because the change date was in the future. Check for mis-set clocks")
	short ERR_SECURE_NEW_PW_IN_FUTURE = PKG_SECURE+254;
	@ErrorText(text="The signature in the Change Password field was found to be invalid")
	short ERR_SECURE_CHANGE_SIG_INVALID = PKG_SECURE+255;
	@ErrorText(text="Failed to initialize activity logging for passthru.")
	short ERR_SECURE_PT_ACTLOG_INIT = PKG_SECURE2+0;
	@ErrorText(text="Your certificate has not yet been signed by the Certificate Authority.  Try again later.")
	short ERR_SECURE_CERT_NOT_READY = PKG_SECURE2+1;
	@ErrorText(text="The password you entered is not long enough.")
	short ERR_SECURE_BAD_LENGTH_PW = PKG_SECURE2+2;
	@ErrorText(text="None of the components of the proposed new name are different than their old values")
	short ERR_SECURE_NO_NEW_NAME = PKG_SECURE2+3;
	@ErrorText(text="Your ID has password expiration enabled. Password expiration cannot be used with a smartcard-protected ID. Please contact your system administrator to have password expiration disabled.")
	short ERR_SECURE_SC_PASSWORD = PKG_SECURE2+4;
	@ErrorText(text="Both the name and the key assigned to an entity cannot be changed at the same time.")
	short ERR_SECURE_NAME_AND_KEY_CHANGE = PKG_SECURE2+10;
	@ErrorText(text="Your current mail server is unavailable. You are being connected to a backup server.")
	short ERR_SECURE_PHYSICAL_SERVER_AT_DIFFERENT_SITE = PKG_SECURE3+0;
	@ErrorText(text="Unsupported operation for a Notes ID that is enabled for Notes federated login.")
	short ERR_SECURE_NFL_UNSUPPORTED_FUNC = PKG_SECURE3+1;
	@ErrorText(text="This SAML assertion has already been used to authenticate the user to this server, and cannot be used again.")
	short ERR_SECURE_SAML_ASSERTION_REUSE = PKG_SECURE3+2;
	@ErrorText(text="This server is not the intended audience for this SAML assertion.")
	short ERR_SECURE_SAML_UNINTENDED_AUDIENCE = PKG_SECURE3+3;
	@ErrorText(text="User's policy does not allow password authentication with the ID vault. Password has not been reset.")
	short ERR_SECURE_PW_AUTH_NOT_ALLOWED = PKG_SECURE3+4;
	@ErrorText(text="Your password needs to be reset. Contact your administrator if you need help to reset your password.")
	short ERR_SECURE_PW_NOT_SET = PKG_SECURE3+5;
	@ErrorText(text="The SAML assertion failed timestamp validation, which may be caused by clock skew between servers: %1e")
	short ERR_SECURE_SAML_BADTIME = PKG_SECURE3+6;

}
