package com.mindoo.domino.jna.errors.errortexts;

public interface IXmlErr extends IGlobalErr {

	@ErrorText(text="General DXL Importer error")
	short ERR_DXL_I_GENERAL = PKG_XML+1;
	@ErrorText(text="Unknown element: %s")
	short ERR_DXL_UNKNOWN_ELEMENT = PKG_XML+2;
	@ErrorText(text="Unknown %s element attribute: %s")
	short ERR_DXL_UNKNOWN_ATTRIBUTE = PKG_XML+3;
	@ErrorText(text="Unknown %s element attribute value: %s='%s'")
	short ERR_DXL_UNKNOWN_ATTRIBUTE_VALUE = PKG_XML+4;
	@ErrorText(text="Invalid %s element attribute value: %s='%s'")
	short ERR_DXL_INVALID_ATTRIBUTE_VALUE = PKG_XML+5;
	@ErrorText(text="Invalid %s attribute value: %s")
	short ERR_DXL_INVALID_ATTRIBUTE_VALUE_NO_ELEMENT = PKG_XML+6;
	@ErrorText(text="%s element must contain a value")
	short ERR_DXL_MISSING_ELEMENT_VALUE = PKG_XML+7;
	@ErrorText(text="%s element must have %s attribute")
	short ERR_DXL_MISSING_ATTRIBUTE = PKG_XML+8;
	@ErrorText(text="%s element cannot have more than one attribute")
	short ERR_DXL_TOO_MANY_ATTRIBUTES = PKG_XML+9;
	@ErrorText(text="Unexpected %s element child element: %s")
	short ERR_DXL_UNEXPECTED_CHILD_ELEMENT = PKG_XML+10;
	@ErrorText(text="Unknown %s element child element: %s")
	short ERR_DXL_UNKNOWN_CHILD_ELEMENT = PKG_XML+11;
	@ErrorText(text="%s element must contain %s element")
	short ERR_DXL_MISSING_CHILD_ELEMENT = PKG_XML+12;
	@ErrorText(text="%s element must contain %s element or %s element")
	short ERR_DXL_MISSING_CHILD_ELEMENT2 = PKG_XML+13;
	@ErrorText(text="%s element must contain at least one child element")
	short ERR_DXL_MISSING_CHILDREN = PKG_XML+14;
	@ErrorText(text="%s element contains too many child elements")
	short ERR_DXL_TOO_MANY_CHILDREN = PKG_XML+15;
	@ErrorText(text="%s element cannot contain child elements")
	short ERR_DXL_NO_CHILDREN_ALLOWED = PKG_XML+16;
	@ErrorText(text="Unable to access %s record to update %s element's attributes")
	short ERR_DXL_CDRECORD_NOT_FOUND = PKG_XML+17;
	@ErrorText(text="Invalid boolean attribute value (must be 'true' or 'false'): %s")
	short ERR_DXL_INVALID_BOOL = PKG_XML+18;
	@ErrorText(text="Invalid border width attribute value: %s")
	short ERR_DXL_INVALID_BORDER_WIDTH = PKG_XML+19;
	@ErrorText(text="datetime element value is not a valid ISO 8601 date/time string: %s")
	short ERR_DXL_INVALID_DATETIME = PKG_XML+20;
	@ErrorText(text="Number value is invalid or too large: %s")
	short ERR_DXL_INVALID_NUMBER = PKG_XML+21;
	@ErrorText(text="Hexadecimal number value is invalid or too large: %s")
	short ERR_DXL_INVALID_HEX_NUMBER = PKG_XML+22;
	@ErrorText(text="Hexadecimal byte stream contains invalid data or is too large to store in a single note item")
	short ERR_DXL_INVALID_HEX_STREAM = PKG_XML+23;
	@ErrorText(text="Base64 byte stream contains invalid data or is too large to store in a single note item")
	short ERR_DXL_INVALID_BASE64_STREAM = PKG_XML+24;
	@ErrorText(text="Length value is invalid: %s")
	short ERR_DXL_INVALID_LENGTH = PKG_XML+25;
	@ErrorText(text="Invalid unid (universal ID) value: %s")
	short ERR_DXL_INVALID_UNID = PKG_XML+26;
	@ErrorText(text="%s element's attribute value %s='%s': no pardef element with this id has been defined")
	short ERR_DXL_INVALID_PARDEF_ID = PKG_XML+27;
	@ErrorText(text="code element %s cannot be used in %s elements")
	short ERR_DXL_INVALID_CODE_ELEMENT = PKG_XML+28;
	@ErrorText(text="Root element must have a version attribute")
	short ERR_DXL_MISSING_VERSION = PKG_XML+29;
	@ErrorText(text="code element event='%s' is not a valid %s element event")
	short ERR_DXL_INVALID_CODE_EVENT = PKG_XML+30;
	@ErrorText(text="code element event='%s' attribute cannot be used with %s elements in %s elements")
	short ERR_DXL_INCOMPATIBLE_CODE_EVENT = PKG_XML+31;
	@ErrorText(text="document element must be response or conflict to have parent attribute")
	short ERR_DXL_PARENT_WITHOUT_RESPONSE = PKG_XML+32;
	@ErrorText(text="Response or conflict document element must have parent attribute")
	short ERR_DXL_MISSING_PARENT_ATTRIBUTE = PKG_XML+33;
	@ErrorText(text="%s element: %s must be specified as either an attribute or formula element")
	short ERR_DXL_MISSING_LINK_HREF = PKG_XML+34;
	@ErrorText(text="%s element: %s cannot be specified using both an attribute and formula element")
	short ERR_DXL_DUPLICATE_LINK_HREF = PKG_XML+35;
	@ErrorText(text="%s element must have either an imageref name attribute or imageref formula element")
	short ERR_DXL_MISSING_LINK_IMAGEREF = PKG_XML+36;
	@ErrorText(text="%s element cannot have both an imageref name attribute and imageref formula element")
	short ERR_DXL_DUPLICATE_LINK_IMAGEREF = PKG_XML+37;
	@ErrorText(text="A table cannot have more than 256 columns")
	short ERR_DXL_TOO_MANY_TABLE_COLUMNS = PKG_XML+38;
	@ErrorText(text="Maximum table width exceeded")
	short ERR_DXL_TABLE_TOO_WIDE = PKG_XML+39;
	@ErrorText(text="%s attribute %s=%s incompatible with %s value")
	short ERR_DXL_INCOMPATIBLE_ATTRIBUTE = PKG_XML+40;
	@ErrorText(text="Cannot replace existing ACL entry")
	short ERR_DXL_CANNOT_REPLACE_ACL_ENTRY = PKG_XML+41;
	@ErrorText(text="Cannot create output file")
	short ERR_DXL_CANNOT_CREATE_FILE = PKG_XML+42;
	@ErrorText(text="Invalid function parameter")
	short ERR_DXL_INVALID_PARAMETER = PKG_XML+43;
	@ErrorText(text="Attempt to use uninitialized object")
	short ERR_DXL_UNINITIALIZED_OBJECT = PKG_XML+44;
	@ErrorText(text="Function not yet implemented")
	short ERR_DXL_NOT_IMPLEMENTED = PKG_XML+45;
	@ErrorText(text="No database specified")
	short ERR_DXL_NO_DATABASE = PKG_XML+46;
	@ErrorText(text="DXLString: error while translating from Unicode to native character set")
	short ERR_DXL_UNICODE_TRANSLATION_ERROR = PKG_XML+47;
	@ErrorText(text="Unknown DXL class library error")
	short ERR_DXL_UNKNOWN_ERROR = PKG_XML+48;
	@ErrorText(text="Use of %s='%s' attribute requires %s attribute")
	short ERR_DXL_ATTRVAL_DEPENDENCY = PKG_XML+49;
	@ErrorText(text="Use of %s='%s' attribute requires %s or %s attribute")
	short ERR_DXL_ATTRVAL_DEPENDENCY2 = PKG_XML+50;
	@ErrorText(text="Internal DXL class library error: %s")
	short ERR_DXL_INTERNAL_ERROR = PKG_XML+51;
	@ErrorText(text="Use of %s element's %s attribute is not valid with %s child element")
	short ERR_DXL_ATTRVAL_CHILD_LIMITATION = PKG_XML+52;
	@ErrorText(text="%s element must have %s attribute or contain %s element")
	short ERR_DXL_MISSING_ATTR_OR_ELEMENT = PKG_XML+53;
	@ErrorText(text="%s element within %s element is limited to containing only %s")
	short ERR_DXL_GRANDCHILD_RESTRICTION = PKG_XML+54;
	@ErrorText(text="Reader access level is required to access design elements")
	short ERR_DXL_READER_ACCESS_REQUIRED = PKG_XML+55;
	@ErrorText(text="Cannot access design elements because the database design is hidden")
	short ERR_DXL_HIDDEN_DESIGN = PKG_XML+56;
	@ErrorText(text="%s element must have %s or %s attribute")
	short ERR_DXL_MISSING_ATTRIBUTE2 = PKG_XML+57;
	@ErrorText(text="A user name must be specified for applications running on a Domino server")
	short ERR_DXL_USERNAME_REQUIRED = PKG_XML+58;
	@ErrorText(text="Applications running on a Domino server cannot re-create an existing database")
	short ERR_DXL_OVERWRITE_SERVER_DB = PKG_XML+59;
	@ErrorText(text="gif, jpeg, or imageref element was not created properly in %s element from %s element")
	short ERR_DXL_IMAGE_WAS_NOT_CREATED = PKG_XML+60;
	@ErrorText(text="note element's class attribute must match class of note to be replaced")
	short ERR_DXL_NOTE_CLASS_MISMATCH = PKG_XML+61;
	@ErrorText(text="DXLSession is not initialized")
	short ERR_DXL_UNINITIALIZED_SESSION = PKG_XML+62;
	@ErrorText(text="Cannot access a remote database when a user name is specified")
	short ERR_DXL_CANNOT_ACCESS_REMOTE_DB = PKG_XML+63;
	@ErrorText(text="%s element's key attribute value is already defined: %s")
	short ERR_DXL_DUPLICATE_KEY = PKG_XML+64;
	@ErrorText(text="Missing namespace for root element")
	short ERR_DXL_MISSING_NAMESPACE = PKG_XML+65;
	@ErrorText(text="Root element is in an unsupported namespace: %s")
	short ERR_DXL_UNSUPPORTED_NAMESPACE = PKG_XML+66;
	@ErrorText(text="%s element must have a name or alias attribute")
	short ERR_DXL_MISSING_NAME_AND_ALIAS = PKG_XML+67;
	@ErrorText(text="DXLOUTPUTCHARSET_UNICODE is only supported when exporting to a memory buffer")
	short ERR_DXL_CANNOT_EXPORT_UNICODE_TO_FILE = PKG_XML+68;
	@ErrorText(text="Unrecognized ODS data, may come from later Notes version")
	short ERR_DXL_ODS_UNKNOWN = PKG_XML+69;
	@ErrorText(text="Could not load procedure by name")
	short ERR_XML_GET_PROCADDRESS_FAILED = PKG_XML+70;
	@ErrorText(text="Internal error: could not create new DXL session")
	short ERR_XML_NEWSESSION_FAILED = PKG_XML+71;
	@ErrorText(text="XSLT initialization failed")
	short ERR_XML_XSLT_INITIALIZATION_FAILED = PKG_XML+72;
	@ErrorText(text="XSLT transformation failed")
	short ERR_XML_XSLT_TRANSFORMATION_FAILED = PKG_XML+73;
	@ErrorText(text="XML declaration must start with left-angle-bracket followed by '?xml', must have a version='1.0' attribute, may have no additional attributes other than encoding and standalone, and must end in '?&gt;'")
	short ERR_INVALID_XML_DECL_SYNTAX = PKG_XML+74;
	@ErrorText(text="Unrecognized encoding character set name")
	short ERR_INVALID_XML_DECL_ENCODING = PKG_XML+75;
	@ErrorText(text="XML declaration is expressed in a character set that cannot be autodetected")
	short ERR_INVALID_XML_DECL_AUTODETECT = PKG_XML+76;
	@ErrorText(text="Standalone attribute value must be 'yes' or 'no'")
	short ERR_INVALID_XML_DECL_STANDALONE = PKG_XML+77;
	@ErrorText(text="Unable to recognize or load XML reformatter input character set")
	short ERR_XML_REFORMATTER_INPUT_CHARSET = PKG_XML+78;
	@ErrorText(text="Unable to recognize or load XML reformatter output character set")
	short ERR_XML_REFORMATTER_OUTPUT_CHARSET = PKG_XML+79;
	@ErrorText(text="A database's replica ID, when specified in multiple places in DXL, must use the same value in all places")
	short ERR_DXL_INCONSISTENT_REPLICAID_VALUES = PKG_XML+80;
	@ErrorText(text="Unable to read or write to file during processing of %s")
	short ERR_DXL_FILE = PKG_XML+81;
	@ErrorText(text="Invalid string GUID format - use format '{c200e360-38c5-11ce-ae62-08002b2b79ef}'")
	short ERR_DXL_INVALID_GUID_STRING = PKG_XML+82;
	@ErrorText(text="regionid='%s' on %s region element does not match any unclosed region")
	short ERR_DXL_UNMATCHED_REGIONID = PKG_XML+83;
	@ErrorText(text="Unsupported DXL version: %s")
	short ERR_DXL_UNSUPPORTED_VERSION = PKG_XML+84;
	@ErrorText(text="Invalid Property Value for Property specified")
	short ERR_DXL_INVALID_PROPERTY_VALUE = PKG_XML+85;
	@ErrorText(text="Invalid Property specified")
	short ERR_DXL_INVALID_PROPERTY = PKG_XML+86;
	@ErrorText(text="Name exceeds maximum length")
	short ERR_DXL_NAME_TOO_LONG = PKG_XML+87;
	@ErrorText(text="Process to Export is unsupported.")
	short ERR_DXL_EXPORT_UNSUPPORTED = PKG_XML+88;
	@ErrorText(text="DXL exporter failed")
	short ERR_DXL_EXPORTER_FAILED = PKG_XML+89;
	@ErrorText(text="DXL importer failed")
	short ERR_DXL_IMPORTER_FAILED = PKG_XML+90;
	@ErrorText(text="Shared actions note not found; shared actions references will not be found")
	short ERR_DXL_SHARED_ACTIONS_NOT_FOUND = PKG_XML+91		/* warning */;
	@ErrorText(text="Referenced shared action(s) not found - creating dummy action(s)")
	short ERR_DXL_SHARED_ACTION_NOT_FOUND = PKG_XML+92		/* warning */;
	@ErrorText(text="Java compile errors:\n%s")
	short ERR_DXL_JAVA_COMPILE_ERRORS = PKG_XML+93;
	@ErrorText(text="Compiling Java returned 'not found' error - probably a missing script library")
	short ERR_DXL_JAVA_COMPILE_NOT_FOUND = PKG_XML+94;
	@ErrorText(text="DXL exporter discarded non-XML character '%1$s'")
	short ERR_DXL_EXPORTER_BAD_CHAR = PKG_XML+95	/* warning */;
	@ErrorText(text="Shared field note not found; shared field reference has been discarded")
	short ERR_DXL_SHARED_FIELD_NOT_FOUND = PKG_XML+96		/* warning */;
	@ErrorText(text="Invalid color value stored on disk - treated as black")
	short ERR_DXL_INVALID_COLOR = PKG_XML+97		/* warning */;
	@ErrorText(text="Code for event='%s' can only be a %s element")
	short ERR_DXL_CODE_TYPE_LIMIT = PKG_XML+98;
	@ErrorText(text="Missing element")
	short ERR_DXL_MISSING_ELEMENT = PKG_XML+99;
	@ErrorText(text="Deprecated attribute, %s, has overridden attribute %s")
	short ERR_DXL_DEPRECATED_ATTRIBUTE = PKG_XML+100;
	@ErrorText(text="Unexpected CD record sequence; results may be incomplete")
	short ERR_DXL_UNEXPECTED_CD_SEQ = PKG_XML+101;
	@ErrorText(text="Nonoperative element, %s, ignored")
	short ERR_XML_NOOP_ELEMENT = PKG_XML+102;
	@ErrorText(text="Could not create the %s note specified by the DXL because the maximum number of notes with the specified type or name are already in the database")
	short ERR_DXL_COULD_NOT_CREATE_NOTE = PKG_XML+103;
	@ErrorText(text="Could not replace/update a matching '%s' note because the ReplicaRequiredForReplaceUpdate property is true and the DXL and database are not replicas")
	short ERR_DXL_CANNOT_MODIFY_NONREPLICA = PKG_XML+104;
	@ErrorText(text="Attribute 'restrictions' overrides deprecated attribute 'unrestrictedoperations' when both are used together")
	short ERR_DXL_AGENT_RESTRICTIONS_ERR = PKG_XML+105;
	@ErrorText(text="Error postprocessing note %s item %s; results may be incomplete")
	short ERR_DXL_ITEM_POSTPROC = PKG_XML+106;
	@ErrorText(text="%s element found when %s element is required at this poshort in the DXL by this version of the importer")
	short ERR_DXL_MISSING_REQUIRED_ELEMENT = PKG_XML+107;
	@ErrorText(text="%s is not an image type that can be processed by this version of the importer")
	short ERR_DXL_IMAGE_TYPE_UNKNOWN = PKG_XML+108;
	@ErrorText(text="%s is not a code type that can be processed by this version of the importer")
	short ERR_DXL_CODE_TYPE_UNKNOWN = PKG_XML+109;
	@ErrorText(text="%s is not a field choice that can be processed by this version of the importer")
	short ERR_DXL_FIELD_CHOICE_UNKNOWN = PKG_XML+110;
	@ErrorText(text="Attempt to change a readonly property of an XML processor")
	short ERR_XML_PROPERTY_IS_READONLY = PKG_XML+111;
	@ErrorText(text="Invalid value for the specified XSLT property")
	short ERR_XSLT_INVALID_PROPERTY_VALUE = PKG_XML+112;
	@ErrorText(text="Invalid XSLT property specified")
	short ERR_XSLT_INVALID_PROPERTY = PKG_XML+113;
	@ErrorText(text="XML processor received external error: %s")
	short ERR_XML_PROCESSOR_EXTERNAL = PKG_XML+114;
	@ErrorText(text="Fixup processing failed for note %s item %s")
	short ERR_DXL_FIXUP = PKG_XML+115;
	@ErrorText(text="%s element's noteinfo unid is already defined: %s")
	short ERR_DXL_DUPLICATE_UNID = PKG_XML+116;
	@ErrorText(text="Unresolved UNID in note %s item %s; linkage with other note has failed")
	short ERR_DXL_UNRESOLVED_UNID = PKG_XML+117;
	@ErrorText(text="Element %s attribute %s contains too many tokens; tokens after %s are ignored")
	short ERR_DXL_ATTR_VAL_TOO_MANY_TOKENS = PKG_XML+118;
	@ErrorText(text="Import operation incomplete; %s notes(s) imported successfully")
	short ERR_DXL_IMPORTED_NOTES = PKG_XML+119;
	@ErrorText(text="%s element: %s attribute has overridden %s child element; only one should be specified")
	short ERR_DXL_ATTR_OVERRIDE_CHILD_ELEM = PKG_XML+120;
	@ErrorText(text="%s element: %s attribute represents a duplicate attachment name for note ID 0x%s")
	short ERR_DXL_DUPLICATE_ATTACHMENT_NAME = PKG_XML+121;
	@ErrorText(text="Inconsistent data encountered %s")
	short ERR_DXL_INCONSISTENT_DATA = PKG_XML+122;
	@ErrorText(text="Writing data as rawitemdata element due to previous warning")
	short ERR_DXL_WRITING_UNINTERPRETED = PKG_XML+123;
	@ErrorText(text="Writing design element as note element due to previous warning")
	short ERR_DXL_WRITING_DE_AS_NOTE = PKG_XML+124;
	@ErrorText(text="DOM parser failed")
	short ERR_XML_DOMPARSER_FAILED = PKG_XML+128;
	@ErrorText(text="SAX parser failed")
	short ERR_XML_SAXPARSER_FAILED = PKG_XML+129;
	@ErrorText(text="XML reformatter failed")
	short ERR_XML_REFORMATTER_FAILED = PKG_XML+130;
	@ErrorText(text="XSL transformer failed")
	short ERR_XML_XSLTRANSFORMER_FAILED = PKG_XML+131;
	@ErrorText(text="Argument cannot be NULL")
	short ERR_XML_NULL_ARGUMENT = PKG_XML+132;
	@ErrorText(text="%s element must contain exactly %s child elements")
	short ERR_DXL_INVALID_CHILD_ELEMENT_COUNT = PKG_XML+133;
	@ErrorText(text="Not enough memory allocated in buffer.")
	short ERR_DXL_INSUFFICIENT_BUFFER_SIZE = PKG_XML+134;
	@ErrorText(text="DXL composite record pool is full")
	short ERR_DXL_COMPOSITE_POOL_FULL = PKG_XML+135;
	@ErrorText(text="%s element must have %s attribute when %s attribute is specified")
	short ERR_DXL_MISSING_CONTEXT_ATTRIBUTE = PKG_XML+136;
	@ErrorText(text="%s is not a valid target for code event='%s'")
	short ERR_DXL_INVALID_CODE_TARGET = PKG_XML+137;
	@ErrorText(text="%s is not valid for code event='%s'")
	short ERR_DXL_INVALID_CODE_LANGUAGE_ELEMENT = PKG_XML+138;
	@ErrorText(text="Invalid processing instruction: %s")
	short ERR_DXL_INVALID_PROCESSING_INSTRUCTION = PKG_XML+139;
	@ErrorText(text="Invalid processing instruction data: %s")
	short ERR_DXL_INVALID_PROCESSING_INSTRUCTION_DATA = PKG_XML+140;
	@ErrorText(text="DXL Injected Error")
	short ERR_DXL_INJECTED_ERROR = PKG_XML+141;
	@ErrorText(text="Internal error: could not destroy the DXL session")
	short ERR_XML_CLOSESESSION_FAILED = PKG_XML+142;
	@ErrorText(text="Internal error: could not destroy the DXLSource")
	short ERR_DXL_DELETESOURCE_FAILED = PKG_XML+143;
	@ErrorText(text="Invalid element value for this element %s")
	short ERR_DXL_INVALID_ELEMENT_VALUE = PKG_XML+144;
	@ErrorText(text="Use of %s element's %s='%s' attribute requires %s child element")
	short ERR_DXL_ATTRVAL_DEPENDENCY3 = PKG_XML+145;
	@ErrorText(text="%s element must contain one of %s element(s)")
	short ERR_DXL_MISSING_REQUIRED_CHILD_ELEMENT = PKG_XML+146;
	@ErrorText(text="%s element is not allowed to have text content")
	short ERR_DXL_TEXT_CONTENT_NOT_ALLOWED = PKG_XML+147;
	@ErrorText(text="Composite data exceeds maximum length allowed in this context")
	short ERR_DXL_TOO_MUCH_COMPOSITE_DATA = PKG_XML+148;
	@ErrorText(text="%s element attribute %s is out of the valid range")
	short ERR_DXL_ATTRIBUTE_VALUE_OUT_OF_RANGE = PKG_XML+149;
	@ErrorText(text="Additional code %s elements are not allowed in this context")
	short ERR_DXL_TOO_MANY_OF_CODE_TYPE = PKG_XML+150;
	@ErrorText(text="Use of %s element's %s attribute is not valid within %s parent element")
	short ERR_DXL_ATTRVAL_PARENT_LIMITATION = PKG_XML+151;
	@ErrorText(text="%s element is not allowed when within %s element; ignored")
	short ERR_DXL_CONTAINMENT_RESTRICTION = PKG_XML+152;
	@ErrorText(text="%s element requires a %s element that contains %s")
	short ERR_DXL_CHILD_CONTAINMENT_NEED = PKG_XML+153;
	@ErrorText(text="Table right margin must be greater than the left margin.")
	short ERR_DXL_TABLE_LM_EXCEEDS_RM = PKG_XML+154;
	@ErrorText(text="%s should contain only one code type; non %s code has been ignored")
	short ERR_DXL_MULTIPLE_CODE_TYPES = PKG_XML+155;
	@ErrorText(text="Role name %s not found in ACL; unable to add role to ACL entry '%s'")
	short ERR_DXL_ACLENTRY_ROLE_NOT_FOUND = PKG_XML+156;
	@ErrorText(text="Exceeded maximum %s count of %s")
	short ERR_DXL_EXCEEDED_MAX_COUNT = PKG_XML+157;
	@ErrorText(text="Could not serialize the DOM Document. Content may be bad or malformed")
	short ERR_SERIALIZING_DOM_DOCUMENT = PKG_XML+158;
	@ErrorText(text="Shared field note not found; a reference will still be generated")
	short ERR_DXL_SHARED_FIELD_NOT_FOUND_OK = PKG_XML+159		/* warning */;
	@ErrorText(text="Attribute %s=%s not valid in this context")
	short ERR_DXL_ATTRVAL_CONTEXT_LIMITATION = PKG_XML+160;
	@ErrorText(text="Error detected by LotusScript Web Service Provider in web service %s")
	short ERR_WS_DEFAULT_LS_PROVIDER_FAULT = PKG_XML+161;
	@ErrorText(text="Did not find an Envelope element where expected in a SOAP request in web service %s")
	short ERR_WS_ENVELOPE_ELEMENT_NOT_FOUND = PKG_XML+162;
	@ErrorText(text="Did not find a Body element where expected in a SOAP request in web service %s")
	short ERR_WS_BODY_ELEMENT_NOT_FOUND = PKG_XML+163;
	@ErrorText(text="Body element lacks request content in a SOAP request in web service %s")
	short ERR_WS_EMPTY_BODY_ELEMENT = PKG_XML+164;
	@ErrorText(text="Unknown argument %s passed in method %s in web service %s")
	short ERR_WS_UNKNOWN_REQUEST_ARG = PKG_XML+165;
	@ErrorText(text="Attempt to pass duplicate argument %s in method %s in web service %s")
	short ERR_WS_DUPLICATE_REQUEST_ARG = PKG_XML+166;
	@ErrorText(text="Expected argument %s missing in method %s in web service %s")
	short ERR_WS_MISSING_REQUEST_ARG = PKG_XML+167;
	@ErrorText(text="LotusScript web services do not support ArrayType attributes which specify arrays of arrays when the container or target is a LotusScript Type (web service %s, method %s, element %s)")
	short ERR_WS_NO_MULTIDIM_ARRAYS_WITH_TYPES = PKG_XML+168;
	@ErrorText(text="ArrayType attribute %s in web service %s, method %s is missing datatype information")
	short ERR_WS_ARRAY_DATATYPE_MISSING = PKG_XML+169;
	@ErrorText(text="An element (%s) from the SOAP encoding namespace can only be used as a member of an array (web service %s, method %s)")
	short ERR_WS_SOAPENC_ELEMENT_NOT_ARRAY_MEMBER = PKG_XML+170;
	@ErrorText(text="Web service %s is unable to create LotusScript object for %s datatype in method %s")
	short ERR_WS_CANNOT_CREATE_LS_OBJECT = PKG_XML+171;
	@ErrorText(text="Web service %s is unable to create LotusScript array for %s datatype in method %s")
	short ERR_WS_CANNOT_CREATE_LS_ARRAY = PKG_XML+172;
	@ErrorText(text="Web service %s is unable to create LotusScript array iterator in method %s")
	short ERR_WS_CANNOT_CREATE_LS_ARRAY_ITERATOR = PKG_XML+173;
	@ErrorText(text="Web service %s does not have specified service method %s")
	short ERR_WS_SERVICE_METHOD_NOT_FOUND = PKG_XML+174;
	@ErrorText(text="Problem encountered when invoking method %s in web service %s")
	short ERR_WS_SERVICE_METHOD_NOT_CALLED = PKG_XML+175;
	@ErrorText(text="Web service (%s)%s object does not have specified member %s in method %s")
	short ERR_WS_UNKNOWN_MEMBER = PKG_XML+176;
	@ErrorText(text="Web service %s is unable to access the value of a LotusScript XSD proxy object in method %s")
	short ERR_WS_ACCESS_LS_PROXY_VALUE = PKG_XML+177;
	@ErrorText(text="Attempt to use unknown datatype %s in web service %s, method %s")
	short ERR_WS_UNKNOWN_DATATYPE = PKG_XML+178;
	@ErrorText(text="Web service %s is unable to create LotusScript object iterator in method %s")
	short ERR_WS_CANNOT_CREATE_LS_OBJECT_ITERATOR = PKG_XML+179;
	@ErrorText(text="Problem encountered when serializing a response value for %s in web service %s, method %s")
	short ERR_WS_CANNOT_SERIALIZE_RESPONSE_VALUE = PKG_XML+180;
	@ErrorText(text="Invalid boolean value passed to web service %s, method %s in element %s")
	short ERR_WS_INVALID_BOOLEAN_VALUE = PKG_XML+181;
	@ErrorText(text="Invalid single value passed to web service %s, method %s in element %s")
	short ERR_WS_INVALID_SINGLE_VALUE = PKG_XML+182;
	@ErrorText(text="Invalid double value passed to web service %s, method %s in element %s")
	short ERR_WS_INVALID_DOUBLE_VALUE = PKG_XML+183;
	@ErrorText(text="Invalid integer or long value passed to web service %s, method %s in element %s")
	short ERR_WS_INVALID_INTEGER_VALUE = PKG_XML+184;
	@ErrorText(text="Invalid unsigned byte value passed to web service %s, method %s in element %s")
	short ERR_WS_INVALID_UNSIGNED_BYTE_VALUE = PKG_XML+185;
	@ErrorText(text="SOAP multi-reference error in web service %s, method %s: href with no element having corresponding id attribute in element %s")
	short ERR_WS_UNRESOLVED_HREF = PKG_XML+186;
	@ErrorText(text="SOAP multi-reference loop detected in web service %s, method %s, element %s")
	short ERR_WS_MULTIREFERENCE_LOOP = PKG_XML+187;
	@ErrorText(text="Error occurred during processing of note ID 0x%lx")
	short ERR_DXL_ERROR_DURING_NOTEID = PKG_XML+200;
	@ErrorText(text="DXL string table pool is full")
	short ERR_DXL_STRINGTABLE_POOL_FULL = PKG_XML+201;
	@ErrorText(text="Unable to add namespace definition '%s' to element '%s' when deserializing a message-style SOAP request into a DOM tree")
	short ERR_WS_CANNOT_ADD_NAMESPACE_DEF = PKG_XML+202;
	@ErrorText(text="Unable to add attribute '%s' to element '%s' when deserializing a message-style SOAP request into a DOM tree")
	short ERR_WS_CANNOT_ADD_ATTRIBUTE = PKG_XML+203;
	@ErrorText(text="Base64 value contains invalid data or is too large to store in a LotusScript array in element %s in web service %s, method %s")
	short ERR_WS_INVALID_BASE64_VALUE = PKG_XML+204;
	@ErrorText(text="Unable to convert member %s in the SOAP request to the expected datatype (web service %s, method %s)")
	short ERR_WS_CANNOT_CONVERT_INPUT_MEMBER = PKG_XML+205;
	@ErrorText(text="LotusScript Error: %s")
	short ERR_DXL_LOTUSSCRIPT_COMPILE_MSG = PKG_XML+206;
	@ErrorText(text="Holder object %s in web service %s, method %s has no public members")
	short ERR_WS_HOLDER_HAS_NO_PUBLIC_MEMBERS = PKG_XML+207;
	@ErrorText(text="Ignoring deprecated DXL construct '%s'.")
	short ERR_DXL_DEPRECATED_IGNORED = PKG_XML+208;
	@ErrorText(text="List object %s in web service %s, method %s has no public array member")
	short ERR_WS_LIST_HAS_NO_PUBLIC_ARRAY_MEMBER = PKG_XML+209;
	@ErrorText(text="Web service %s is unable to reset LotusScript array iterator in method %s")
	short ERR_WS_CANNOT_RESET_LS_OBJECT_ITERATOR = PKG_XML+210;
	@ErrorText(text="value \"%s\" at element \"%s\"")
	short ERR_WS_ELEMENT_VALUE_PATH_ADDON = PKG_XML+211;
	@ErrorText(text="Array at element %s in web service %s, method %s contains too many dimensions")
	short ERR_WS_ARRAY_TOOMANY_DIMENSIONS = PKG_XML+212;
	@ErrorText(text="LotusScript web services do not support jagged (non-rectangular) arrays (web service %s, method %s, element %s)")
	short ERR_WS_NO_JAGGED_ARRAYS = PKG_XML+213;
	@ErrorText(text="Unable to deserialize badly formed SOAP array.")
	short ERR_WS_BAD_SOAP_ARRAY = PKG_XML+214;
	@ErrorText(text="LotusScript web services do not support empty arrays of non-nilable types (web service %s, method %s, element %s)")
	short ERR_WS_NO_EMPTY_ARRAYS_FOR_NONNILABLE = PKG_XML+215;
	@ErrorText(text="LotusScript web services do not support the SOAP attributes position or offset")
	short ERR_WS_SOAPARRAY_NOSUPPORT_POS_OR_OFFSET = PKG_XML+216;
	@ErrorText(text="Shared column %s not found")
	short ERR_DXL_SHARED_COLUMN_NOT_FOUND = PKG_XML+217;
	@ErrorText(text="Composite app WSDL: Actions may have only one input.")
	short ERR_CAPP_MULTI_INPUTS = PKG_XML+218;
	@ErrorText(text="Composite app WSDL: Multiple output properties may not be bound together.")
	short ERR_CAPP_MULTI_OUTPUTS = PKG_XML+219;
	@ErrorText(text="Composite app WSDL: Invalid XML data.")
	short ERR_CAPP_INVALID_XML = PKG_XML+220;
	@ErrorText(text="RESOURCELINK not a Named element")
	short ERR_DXL_RESOURCELINK_NOT_NAMEDELEMENT = PKG_XML+221;
	@ErrorText(text="Web service processing error: %s")
	short ERR_DXL_WEB_SERVICE_PROCESSING = PKG_XML+222;
	@ErrorText(text="webservice not imported because source code and WSDL both changed since export and warnwsdlmodified='true'")
	short ERR_DXL_WS_NOTIMP_CHANGED_SRCWSDL = PKG_XML+223;
	@ErrorText(text="webservice not imported because source code changed since export and warnwsdlmodified='true'")
	short ERR_DXL_WS_NOTIMP_CHANGED_SRC = PKG_XML+224;
	@ErrorText(text="webservice not imported because WSDL changed since export and warnwsdlmodified='true'")
	short ERR_DXL_WS_NOTIMP_CHANGED_WSDL = PKG_XML+225;
	@ErrorText(text="Internal DXL error while processing %s element")
	short ERR_DXL_INTERNAL_ERROR_ELEMENT = PKG_XML+226;
	@ErrorText(text="An internal error occurred while processing the web service request")
	short ERR_WS_INTERNAL_ERROR = PKG_XML+227;
	@ErrorText(text="General DXL table Importer error")
	short ERR_DXL_TABLE_GENERAL = PKG_XML+228;
	@ErrorText(text="An invalid formula was encountered, but ignored since it is not currently referenced.")
	short ERR_DXL_INVALID_FORMULA_WARNING = PKG_XML+229;
	@ErrorText(text="Can't emit <compositedata> with parent <%S>, record was discarded.")
	short ERR_DXL_INVALID_PARENT_WARNING = PKG_XML+230;
	@ErrorText(text="Record was not imported because the correct location could not be found.")
	short ERR_DXL_INVALID_LOCATION_WARNING = PKG_XML+231;
	@ErrorText(text="Compiled %s element cannot contain child elements")
	short ERR_DXL_COMPILED_NO_CHILDREN_ALLOWED = PKG_XML+232;
	@ErrorText(text="Multiple items of the same name are not allowed.")
	short ERR_DXL_ISVAPI_DUPLICATE_ITEM_ERROR = PKG_XML+233;
	@ErrorText(text="Form validation error: %s")
	short ERR_DXL_ISVAPI_FORM_VALIDATION_ERROR = PKG_XML+234;

}
