package com.mindoo.domino.jna.structs;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesGlobalInstanceId32 extends BaseStructure {
	/**
	 * database Creation time/date<br>
	 * C type : DBID
	 */
	public NotesTimeDate File;
	/**
	 * note Modification time/date<br>
	 * C type : TIMEDATE
	 */
	public NotesTimeDate Note;
	/**
	 * note ID within database<br>
	 * C type : NOTEID
	 */
	public int NoteID;
	public NotesGlobalInstanceId32() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("File", "Note", "NoteID");
	}
	/**
	 * @param File database Creation time/date<br>
	 * C type : DBID<br>
	 * @param Note note Modification time/date<br>
	 * C type : TIMEDATE<br>
	 * @param NoteID note ID within database<br>
	 * C type : NOTEID
	 */
	public NotesGlobalInstanceId32(NotesTimeDate File, NotesTimeDate Note, int NoteID) {
		super();
		this.File = File;
		this.Note = Note;
		this.NoteID = NoteID;
	}
	public NotesGlobalInstanceId32(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NotesGlobalInstanceId32 implements Structure.ByReference {

	};
	public static class ByValue extends NotesGlobalInstanceId32 implements Structure.ByValue {

	};
}
