package com.mindoo.domino.jna.structs;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesObjectDescriptor extends Structure {
	/** Type of object (OBJECT_xxx) */
	public short ObjectType;
	/** Object ID of the object in THIS FILE */
	public int RRV;
	public NotesObjectDescriptor() {
		super();
		setAlignType(Structure.ALIGN_NONE);
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ObjectType", "RRV");
	}
	/**
	 * @param ObjectType Type of object (OBJECT_xxx)<br>
	 * @param RRV Object ID of the object in THIS FILE
	 */
	public NotesObjectDescriptor(short ObjectType, int RRV) {
		super();
		setAlignType(Structure.ALIGN_NONE);
		this.ObjectType = ObjectType;
		this.RRV = RRV;
	}
	public NotesObjectDescriptor(Pointer peer) {
		super(peer);
		setAlignType(Structure.ALIGN_NONE);
	}
	public static class ByReference extends NotesObjectDescriptor implements Structure.ByReference {
		
	};
	public static class ByValue extends NotesObjectDescriptor implements Structure.ByValue {
		
	};
}
