package com.mindoo.domino.jna.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesBlockIdStruct extends BaseStructure {
	/**
	 * pool handle<br>
	 * C type : DHANDLE
	 */
	public int pool;
	/**
	 * block handle<br>
	 * C type : BLOCK
	 */
	public short block;
	
	/**
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	public NotesBlockIdStruct() {
		super();
//		setAlignType(Structure.ALIGN_NONE);
		
	}
	
	public static NotesBlockIdStruct newInstance() {
		return AccessController.doPrivileged(new PrivilegedAction<NotesBlockIdStruct>() {

			@Override
			public NotesBlockIdStruct run() {
				return new NotesBlockIdStruct();
			}
		});
	}
	
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("pool", "block");
	}
	
	/**
	 * @param pool pool handle<br>
	 * C type : DHANDLE<br>
	 * @param block block handle<br>
	 * C type : BLOCK
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 */
	public NotesBlockIdStruct(int pool, short block) {
		super();
//		setAlignType(Structure.ALIGN_NONE);
		this.pool = pool;
		this.block = block;
	}
	
	public static NotesBlockIdStruct newInstance(final int pool, final short block) {
		return AccessController.doPrivileged(new PrivilegedAction<NotesBlockIdStruct>() {

			@Override
			public NotesBlockIdStruct run() {
				return new NotesBlockIdStruct(pool, block);
			}
		});
	}

	/**
	 * @deprecated only public to be used by JNA; use static newInstance method instead to run in AccessController.doPrivileged block
	 * 
	 * @param peer pointer
	 */
	public NotesBlockIdStruct(Pointer peer) {
		super(peer);
//		setAlignType(Structure.ALIGN_NONE);
	}
	
	public static NotesBlockIdStruct newInstance(final Pointer p) {
		return AccessController.doPrivileged(new PrivilegedAction<NotesBlockIdStruct>() {

			@Override
			public NotesBlockIdStruct run() {
				return new NotesBlockIdStruct(p);
			}
		});
	}
	
	public static class ByReference extends NotesBlockIdStruct implements Structure.ByReference {
		public static NotesBlockIdStruct.ByReference newInstance() {
			return AccessController.doPrivileged(new PrivilegedAction<NotesBlockIdStruct.ByReference>() {

				@Override
				public NotesBlockIdStruct.ByReference run() {
					return new NotesBlockIdStruct.ByReference();
				}
			});
		}
	};
	public static class ByValue extends NotesBlockIdStruct implements Structure.ByValue {
		public static NotesBlockIdStruct.ByValue newInstance() {
			return AccessController.doPrivileged(new PrivilegedAction<NotesBlockIdStruct.ByValue>() {

				@Override
				public NotesBlockIdStruct.ByValue run() {
					return new NotesBlockIdStruct.ByValue();
				}
			});
		}
	};
}
