package com.mindoo.domino.jna.internal.structs.html;
import java.security.AccessController;
import java.security.PrivilegedAction;

import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HtmlApi_UrlComponentStruct extends Union {
	/** C type : HTMLAPI_URLTargetComponent */
	public HtmlApi_UrlTargetComponentStruct Target;
	/** C type : HTMLAPI_URLArg */
	public HtmlApi_UrlArgStruct Arg;
	
	public HtmlApi_UrlComponentStruct() {
		super();
	}
	
	/** @param Target C type : HTMLAPI_URLTargetComponent */
	public HtmlApi_UrlComponentStruct(HtmlApi_UrlTargetComponentStruct Target) {
		super();
		this.Target = Target;
		setType(HtmlApi_UrlTargetComponentStruct.class);
	}
	
	public static HtmlApi_UrlComponentStruct newInstance(final HtmlApi_UrlTargetComponentStruct Target) {
		return AccessController.doPrivileged(new PrivilegedAction<HtmlApi_UrlComponentStruct>() {

			@Override
			public HtmlApi_UrlComponentStruct run() {
				return new HtmlApi_UrlComponentStruct(Target);
			}
		});
	}

	
	/** @param Arg C type : HTMLAPI_URLArg */
	public HtmlApi_UrlComponentStruct(HtmlApi_UrlArgStruct Arg) {
		super();
		this.Arg = Arg;
		setType(HtmlApi_UrlArgStruct.class);
	}
	
	public static HtmlApi_UrlComponentStruct newInstance(final HtmlApi_UrlArgStruct Target) {
		return AccessController.doPrivileged(new PrivilegedAction<HtmlApi_UrlComponentStruct>() {

			@Override
			public HtmlApi_UrlComponentStruct run() {
				return new HtmlApi_UrlComponentStruct(Target);
			}
		});
	}

	
	public HtmlApi_UrlComponentStruct(Pointer peer) {
		super(peer);
	}

	public static HtmlApi_UrlComponentStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged(new PrivilegedAction<HtmlApi_UrlComponentStruct>() {

			@Override
			public HtmlApi_UrlComponentStruct run() {
				return new HtmlApi_UrlComponentStruct(peer);
			}
		});
	}

	public static class ByReference extends HtmlApi_UrlComponentStruct implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends HtmlApi_UrlComponentStruct implements com.sun.jna.Structure.ByValue {
		
	};
}
