package com.mindoo.domino.jna.internal.structs.html;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.mindoo.domino.jna.internal.structs.BaseStructure;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class HtmlApi_UrlArgStruct extends BaseStructure {
	/**
	 * CmdArgID identifier<br>
	 * C type : CmdArgID
	 */
	public int Id;
	
	/**
	 * type of target or arg value (e.g., CAVT_String, CAVT_Int, etc.)<br>
	 * C type : CmdArgValueType
	 */
	public int Type;
	/** C type : Value */
	public ValueUnion val;
	
	public HtmlApi_UrlArgStruct() {
		super();
	}
	
	protected List<String> getFieldOrder() {
		return Arrays.asList("Id", "Type", "val");
	}
	
	/**
	 * @param Id CmdArgID identifier, C type : CmdArgID<br>
	 * @param Type type of target or arg value (e.g., CAVT_String, CAVT_Int, etc.), C type : CmdArgValueType<br>
	 * @param val C type : Value
	 */
	public HtmlApi_UrlArgStruct(int Id, int Type, ValueUnion val) {
		super();
		this.Id = Id;
		this.Type = Type;
		this.val = val;
	}

	public static HtmlApi_UrlArgStruct newInstance(final int Id, final int Type, final ValueUnion val) {
		return AccessController.doPrivileged(new PrivilegedAction<HtmlApi_UrlArgStruct>() {

			@Override
			public HtmlApi_UrlArgStruct run() {
				return new HtmlApi_UrlArgStruct(Id, Type, val);
			}
		});
	}

	
	public HtmlApi_UrlArgStruct(Pointer peer) {
		super(peer);
	}

	public static HtmlApi_UrlArgStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged(new PrivilegedAction<HtmlApi_UrlArgStruct>() {

			@Override
			public HtmlApi_UrlArgStruct run() {
				return new HtmlApi_UrlArgStruct(peer);
			}
		});
	}

	public static class ByReference extends HtmlApi_UrlArgStruct implements Structure.ByReference {
		
	};
	
	public static class ByValue extends HtmlApi_UrlArgStruct implements Structure.ByValue {
		
	};
}
