package com.mindoo.domino.jna.internal.structs;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesMIMEPartStruct extends BaseStructure {
	/** MIME_PART Version */
	public short wVersion;
	public int dwFlags;
	/** Type of MIME_PART body */
	public byte cPartType;
	public byte cSpare;
	/**
	 * Bytes of variable length part data<br>
	 * NOT including data in DB object
	 */
	public short wByteCount;
	/** Length of the boundary string */
	public short wBoundaryLen;
	/** Length of the headers */
	public short wHeadersLen;
	public short wSpare;
	public int dwSpare;
	
	public NotesMIMEPartStruct() {
		super();
	}
	
	public static NotesMIMEPartStruct newInstance() {
		return AccessController.doPrivileged(new PrivilegedAction<NotesMIMEPartStruct>() {

			@Override
			public NotesMIMEPartStruct run() {
				return new NotesMIMEPartStruct();
			}
		});
	}
	
	protected List<String> getFieldOrder() {
		return Arrays.asList("wVersion", "dwFlags", "cPartType", "cSpare", "wByteCount", "wBoundaryLen", "wHeadersLen", "wSpare", "dwSpare");
	}
	
	/**
	 * @param wVersion MIME_PART Version
	 * @param dwFlags flags
	 * @param cPartType Type of MIME_PART body
	 * @param cSpare spare BYTE
	 * @param wByteCount Bytes of variable length part data NOT including data in DB object
	 * @param wBoundaryLen Length of the boundary string
	 * @param wHeadersLen Length of the headers
	 * @param wSpare spare WORD
	 * @param dwSpare spare DWORD
	 */
	public NotesMIMEPartStruct(short wVersion, int dwFlags, byte cPartType, byte cSpare, short wByteCount, 
			short wBoundaryLen, short wHeadersLen, short wSpare, int dwSpare) {
		super();
		this.wVersion = wVersion;
		this.dwFlags = dwFlags;
		this.cPartType = cPartType;
		this.cSpare = cSpare;
		this.wByteCount = wByteCount;
		this.wBoundaryLen = wBoundaryLen;
		this.wHeadersLen = wHeadersLen;
		this.wSpare = wSpare;
		this.dwSpare = dwSpare;
	}
	
	public static NotesMIMEPartStruct newInstance(final short wVersion, final int dwFlags, final byte cPartType,
			final byte cSpare, final short wByteCount, final short wBoundaryLen, final short wHeadersLen,
			final short wSpare, final int dwSpare) {
		
		return AccessController.doPrivileged(new PrivilegedAction<NotesMIMEPartStruct>() {

			@Override
			public NotesMIMEPartStruct run() {
				return new NotesMIMEPartStruct(wVersion, dwFlags, cPartType, cSpare, wByteCount, wBoundaryLen,
						wHeadersLen, wSpare, dwSpare);
			}
		});
	}
	
	public NotesMIMEPartStruct(Pointer peer) {
		super(peer);
	}
	
	public static NotesMIMEPartStruct newInstance(final Pointer peer) {
		return AccessController.doPrivileged(new PrivilegedAction<NotesMIMEPartStruct>() {

			@Override
			public NotesMIMEPartStruct run() {
				return new NotesMIMEPartStruct(peer);
			}
		});
	}
	
	public static class ByReference extends NotesMIMEPartStruct implements Structure.ByReference {
		
	};
	
	public static class ByValue extends NotesMIMEPartStruct implements Structure.ByValue {
		
	};
}
