package com.mindoo.domino.jna.internal.structs;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.mindoo.domino.jna.internal.NotesConstants;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesResultsSortColumnStruct extends BaseStructure {
	/**
	 * programmatic name \ufffd used for all reference<br>
	 * C type : char[MAX_CMD_VALLEN]
	 */
	public byte[] name = new byte[NotesConstants.MAX_CMD_VALLEN];
	/**
	 * view column title (view results only)<br>
	 * C type : char[MAX_CMD_VALLEN]
	 */
	public byte[] title = new byte[NotesConstants.MAX_CMD_VALLEN];
	/**
	 * optional default formula for the sort column, provides simplified formula argument<br>
	 * C type : MEMHANDLE
	 */
	public int hColFormula;
	/** Flag it being set prior to being overridden */
	public boolean bColFormulaSet;
	/** When hColFormula is dereferenced, this gets incremented for subsequent unlocks */
	public int numformulalocks;
	/**
	 * ASC, DESC or none<br>
	 * C type : DESIGN_COMPONENT_ATTR
	 */
	public int sortorder;
	/** column is sorted, not returned */
	public boolean bHidden;
	/** categorized (unique values only) */
	public boolean bCategorized;
	/** a column whose values are aggregated across categorized keys */
	public boolean bAggregate;
	/**
	 * AVG, MAX, MIN, SUM, COUNT, COUNTVALS, STDDEV<br>
	 * C type : QUEP_AGGREGATE_TYPE
	 */
	public int aggtype;
	/**
	 * Support all data types for @@min or @@max (can't be both)<br>
	 * C type : ITEM_TABLE*
	 */
	public Pointer pMinMaxVal;
	/** for @@countvals (count distinct values, this category) */
	public int dwCtVals;
	/**
	 * The sum of all values this column, this category<br>
	 * C type : NUMBER
	 */
	public double numAggSum;
	/**
	 * Current Max or Minimum value<br>
	 * C type : NUMBER
	 */
	public double numMaxMin;
	/**
	 * Final result, per category<br>
	 * C type : NUMBER
	 */
	public double numAggResult;
	/** rightmost set of columns which generate array elements for categorization */
	public boolean bCategLeaf;
	/** Leftmost categorized column (they can nest) */
	public boolean bFirstCateg;
	/** Rightmost categorized column */
	public boolean bLastCateg;
	/** Keep track of when we need to snip off an array and attach it */
	public boolean bCategBreak;
	/** Count the breaks for commas in JSON */
	public int dwCategBreaks;
	/** Pre-count the columns participating in this category (category breaks on multiple column values) */
	public short wColsInCateg;
	/** Either a categorized column, or part of a multiple-column category value */
	public boolean bCategorizedKey;
	/** DBPath and NoteID columns are NOT specified by customer code, but generated and internally */
	public boolean bGenerated;
	/** The number of TYPE_NUMBER entries this category (for producing @@avg and @@count) */
	public int dwEntries;
	/** The number of occurrences (including LIST occurrences) of a column field */
	public int dwColOccs;
	/**
	 * Copy of last ITEM_TABLE for comparison<br>
	 * C type : char*
	 */
	public Pointer pdwCurItemValue;
	
	public NotesResultsSortColumnStruct() {
		super();
	}

	@Override
	protected int getOverrideAlignment() {
		return Structure.ALIGN_DEFAULT;
	}

	@SuppressWarnings("nls")
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("name", "title", "hColFormula", "bColFormulaSet", "numformulalocks", "sortorder", "bHidden", "bCategorized", "bAggregate", "aggtype", "pMinMaxVal", "dwCtVals", "numAggSum", "numMaxMin", "numAggResult", "bCategLeaf", "bFirstCateg", "bLastCateg", "bCategBreak", "dwCategBreaks", "wColsInCateg", "bCategorizedKey", "bGenerated", "dwEntries", "dwColOccs", "pdwCurItemValue");
	}
	public NotesResultsSortColumnStruct(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NotesResultsSortColumnStruct implements Structure.ByReference {

	};
	public static class ByValue extends NotesResultsSortColumnStruct implements Structure.ByValue {

	};

	public static NotesResultsSortColumnStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesResultsSortColumnStruct>) () -> {
			return new NotesResultsSortColumnStruct();
		});
	}

}
