package com.mindoo.domino.jna.internal.structs;

import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NotesSSOTokenItemStruct extends BaseStructure {
	/** C type : MEMHANDLE */
	public int mhItem;
	/** C type : char* */
	public Pointer ptr;
	public int dwLength;
	
	public NotesSSOTokenItemStruct() {
		super();
	}
	
	public static NotesSSOTokenItemStruct newInstance() {
		return AccessController.doPrivileged((PrivilegedAction<NotesSSOTokenItemStruct>) () -> {
			return new NotesSSOTokenItemStruct();
		});
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("mhItem", "ptr", "dwLength");
	}
	
	/**
	 * @param mhItem C type : MEMHANDLE<br>
	 * @param ptr C type : char*
	 */
	public NotesSSOTokenItemStruct(int mhItem, Pointer ptr, int dwLength) {
		super();
		this.mhItem = mhItem;
		this.ptr = ptr;
		this.dwLength = dwLength;
	}
	public NotesSSOTokenItemStruct(Pointer peer) {
		super(peer);
	}
	
	public static NotesSSOTokenItemStruct newInstance(Pointer peer) {
		return AccessController.doPrivileged((PrivilegedAction<NotesSSOTokenItemStruct>) () -> {
			return new NotesSSOTokenItemStruct();
		});
	}

	public static class ByReference extends NotesSSOTokenItemStruct implements Structure.ByReference {
		
	};
	
	public static NotesSSOTokenItemStruct.ByReference newInstanceByReference() {
		return AccessController.doPrivileged((PrivilegedAction<NotesSSOTokenItemStruct.ByReference>) () -> {
			return new NotesSSOTokenItemStruct.ByReference();
		});
	}

	public static class ByValue extends NotesSSOTokenItemStruct implements Structure.ByValue {
		
	};
}
